function buildProfiles(seriesConfig, variants) {
  return variants.map((variant) => ({
    id: `${seriesConfig.idPrefix}-${variant.slug}`,
    title: `${seriesConfig.titlePrefix}・${variant.role}`,
    parentCategory: seriesConfig.parentCategory,
    series: seriesConfig.series,
    themeHint: [seriesConfig.themeHint, variant.themeHint || variant.role].join(" "),
    aliases: [...new Set([seriesConfig.parentCategory, seriesConfig.series, seriesConfig.titlePrefix, variant.role, ...(seriesConfig.aliases || []), ...(variant.aliases || [])])],
    identity: variant.identity || `${seriesConfig.identityPrefix}${variant.role}`,
    palette: variant.palette || seriesConfig.palette,
    costumeCore: variant.costumeCore || seriesConfig.costumeCore,
    jewelry: variant.jewelry || seriesConfig.jewelry,
    prop: variant.prop,
    place: variant.place || seriesConfig.place,
    foreground: variant.foreground || seriesConfig.foreground,
    midground: variant.midground,
    background: variant.background || seriesConfig.background,
    action: /wave5-(dynasty|travel|xianxia)-/.test(seriesConfig.idPrefix || "")
      ? `${seriesConfig.titlePrefix}${variant.role}：${variant.action}；動作需呼應${seriesConfig.themeHint}的材質、風向、光源與前景物件。`
      : variant.action,
    lighting: variant.lighting || seriesConfig.lighting,
    atmosphere: variant.atmosphere || seriesConfig.atmosphere,
    cupSize: variant.cupSize || seriesConfig.cupSize,
  }));
}

const historicalVariants = [
  {
    slug: "folding-fan-beauty",
    role: "折扇名姝",
    aliases: ["折扇", "名姝"],
    prop: "折扇與題字花箋",
    midground: "真人角色半倚案角側身回望",
    action: "人物一手收住折扇於腰側，一手壓住花箋邊角，肩線微轉像剛從詩席抽身",
  },
  {
    slug: "rail-leaning-lady",
    role: "憑欄才媛",
    aliases: ["憑欄", "才媛"],
    prop: "欄邊團扇與流蘇香囊",
    midground: "真人角色倚在長欄前緣停步",
    action: "人物一手扶欄，一手垂持香囊，裙襬沿欄影展開後回眸定格",
  },
  {
    slug: "scroll-keeper",
    role: "把卷女史",
    aliases: ["書卷", "女史"],
    prop: "卷軸與玉鎮紙",
    midground: "真人角色坐在書案邊緣回身看向鏡頭",
    action: "人物一手按住卷軸，一手扶案起身未起，像正要把秘聞收入袖中",
  },
  {
    slug: "zither-shadow",
    role: "停弦幽姬",
    aliases: ["琴姬", "停弦"],
    prop: "古琴與酒盞",
    midground: "真人角色斜坐琴榻前緣偏頭回望",
    action: "人物一手勾住琴弦餘音，一手扶榻側收住披帛，保留演奏後的停頓感",
  },
  {
    slug: "lantern-step",
    role: "分燈閨秀",
    aliases: ["宮燈", "閨秀"],
    prop: "宮燈與細穗手串",
    midground: "真人角色提燈沿石階轉身停步",
    action: "人物一手提燈照亮裙角，一手輕拂袖緣，步伐像被身後呼喚暫時留住",
  },
  {
    slug: "sword-snow",
    role: "拂雪劍姝",
    aliases: ["劍姝", "拂雪"],
    prop: "細劍與披風",
    midground: "真人角色立在雪痕石階前緣微蹲起勢",
    action: "人物一手按住劍鞘，一手收起披風，腰腿重心前傾形成準備出手的張力",
  },
  {
    slug: "curtain-smile",
    role: "分簾柔媛",
    aliases: ["分簾", "柔媛"],
    prop: "珠簾與白玉梳",
    midground: "真人角色自簾後探身回眸",
    action: "人物一手分開珠簾，一手把玉梳垂在腿側，半藏半露形成曖昧戲劇節奏",
  },
  {
    slug: "rain-listener",
    role: "聽雨夫人",
    aliases: ["聽雨", "夫人"],
    prop: "油紙傘與青瓷茶盞",
    midground: "真人角色坐在窗邊矮榻輕側身",
    action: "人物一手扶著傘柄，一手端住茶盞靠近膝側，眼神越過雨幕看回鏡頭",
  },
];

const dynastyVariants = [
  {
    slug: "rail-empress",
    role: "倚欄皇后",
    aliases: ["皇后", "倚欄"],
    prop: "玉如意與宮燈",
    midground: "真人皇后倚在朱欄前緣正要回身",
    action: "人物一手扶欄，一手垂持玉如意，廣袖與披帛沿欄角垂展後帶出回眸",
  },
  {
    slug: "turning-consort",
    role: "回袖貴妃",
    aliases: ["貴妃", "回袖"],
    prop: "牡丹團扇與酒盞",
    midground: "真人貴妃在花階半轉身停步",
    action: "人物一手收住團扇，一手帶起長袖與裙角，像被夜宴喝采聲定住在半步之間",
  },
  {
    slug: "curtain-princess",
    role: "分簾公主",
    aliases: ["公主", "分簾"],
    prop: "珠簾與金燈",
    midground: "真人公主由珠簾後探身而出",
    action: "人物一手分開珠簾，一手托起小金燈，肩頸前探形成柔亮的臨場感",
  },
  {
    slug: "mirror-zhaoyi",
    role: "對鏡昭儀",
    aliases: ["昭儀", "對鏡"],
    prop: "銅鏡與花枝",
    midground: "真人昭儀坐在鏡案側前方微偏頭",
    action: "人物一手扶鏡框，一手捻住花枝，像在宴前照影時忽然聽見腳步聲",
  },
  {
    slug: "music-lady",
    role: "停弦樂姬",
    aliases: ["樂姬", "停弦"],
    prop: "琵琶與拍板",
    midground: "真人樂姬斜坐榻沿抱住琵琶回望",
    action: "人物一手壓住琴弦，一手將拍板垂在腿側，樂音收束的瞬間帶出成熟眼神",
  },
  {
    slug: "couch-princess",
    role: "倚榻王姬",
    aliases: ["王姬", "倚榻"],
    prop: "羽扇與絲枕",
    midground: "真人王姬側倚軟榻前端神情從容",
    action: "人物一手扶榻邊，一手把羽扇半掩在膝側，肩線鬆開形成柔美但不慵散的姿態",
  },
  {
    slug: "lantern-matron",
    role: "捧燈命婦",
    aliases: ["命婦", "捧燈"],
    prop: "雙耳宮燈與香篋",
    midground: "真人命婦提燈穿過長廊時回身停步",
    action: "人物一手捧燈照亮衣紋，一手扣住香篋，步態留有剛走過長廊的前進感",
  },
  {
    slug: "stair-maid",
    role: "轉階宮人",
    aliases: ["宮人", "轉階"],
    prop: "花箋與長披帛",
    midground: "真人宮人沿石階轉身下階",
    action: "人物一手提住裙角，一手收住花箋，身體側轉帶出石階與披帛的連續線條",
  },
  {
    slug: "fan-commandery",
    role: "撫扇郡主",
    aliases: ["郡主", "撫扇"],
    prop: "金邊團扇與花燈",
    midground: "真人郡主立在高欄旁側身倚近",
    action: "人物一手扶欄，一手以團扇輕貼腰側，肩頸越過欄影回望鏡頭",
  },
  {
    slug: "pond-lady",
    role: "臨池淑媛",
    aliases: ["淑媛", "臨池"],
    prop: "蓮燈與玉杯",
    midground: "真人淑媛沿池畔石階緩步回身",
    action: "人物一手托蓮燈，一手垂持玉杯，腳步像剛繞過池邊花影而停在鏡頭前",
  },
];

const wuxiaVariants = [
  {
    slug: "sword-step",
    role: "踏雪劍姝",
    aliases: ["劍姝", "踏雪"],
    prop: "長劍與風雪披風",
    midground: "真人劍姝踏在石階前端收勢回望",
    action: "人物一手按住劍柄，一手牽起披風，腳步還保留剛從雪坡掠下的動勢",
  },
  {
    slug: "banner-general",
    role: "掠旗女將",
    aliases: ["女將", "掠旗"],
    prop: "戰旗與長槍",
    midground: "真人女將立在旌旗下方半跨步",
    action: "人物一手持槍尾壓低重心，一手攬住戰旗，髮尾與旗角同時被風帶起",
  },
  {
    slug: "boat-shadow",
    role: "踏浪俠影",
    aliases: ["俠影", "踏浪"],
    prop: "短刀與斗笠",
    midground: "真人俠影踩在船舷或木橋邊緣側身回看",
    action: "人物一手扶住斗笠，一手垂持短刀，身體順著浪線形成俐落傾角",
  },
  {
    slug: "bow-princess",
    role: "引弓郡主",
    aliases: ["郡主", "引弓"],
    prop: "短弓與羽箭",
    midground: "真人郡主立在城牆箭垛前緣微蹲起勢",
    action: "人物一手持弓下垂，一手勾住箭羽，像剛完成瞄準後偏頭確認遠方局勢",
  },
  {
    slug: "spear-commander",
    role: "回槍女帥",
    aliases: ["女帥", "回槍"],
    prop: "紅纓槍與馬韁",
    midground: "真人女帥站在馬旁回槍停步",
    action: "人物一手握槍橫收，一手扣住馬韁，身體從前行轉為回身形成強烈敘事感",
  },
];

const xianxiaVariants = [
  {
    slug: "wind-goddess",
    role: "御風神姬",
    aliases: ["神姬", "御風"],
    prop: "風鈴與飛紗",
    midground: "真人神姬迎風立在雲階前端半轉身",
    action: "人物一手牽起飛紗，一手扶住風鈴，腳步與披帛像正被天風托起",
  },
  {
    slug: "lantern-celestial",
    role: "執燈仙妃",
    aliases: ["仙妃", "執燈"],
    prop: "月燈與玉珮",
    midground: "真人仙妃提燈由仙橋緩步走來",
    action: "人物一手提燈貼近裙側，一手扶住玉珮，步態保持剛穿過雲橋的連續節奏",
  },
  {
    slug: "moon-sword",
    role: "攬月劍主",
    aliases: ["劍主", "攬月"],
    prop: "仙劍與月輪",
    midground: "真人劍主立在高台邊緣側身收劍",
    action: "人物一手按住劍脊，一手牽住披風邊緣，像把一道月華斂回身側",
  },
  {
    slug: "dragon-tide",
    role: "聽潮龍女",
    aliases: ["龍女", "聽潮"],
    prop: "水紋玉盞與潮珠",
    midground: "真人龍女坐在水階前端回身望向鏡頭",
    action: "人物一手托住潮珠，一手扶水階，裙紗沿階面與水霧自然垂落",
  },
  {
    slug: "herb-valley",
    role: "採藥靈妃",
    aliases: ["靈妃", "採藥"],
    prop: "藥籃與靈草",
    midground: "真人靈妃半蹲於花谷石徑側邊抬眸",
    action: "人物一手捧著藥籃，一手摘起靈草，抬頭時保留採藥中的前後動作連貫",
  },
  {
    slug: "phoenix-rider",
    role: "乘鸞聖女",
    aliases: ["聖女", "乘鸞"],
    prop: "鸞羽與金鈴",
    midground: "真人聖女立在鸞臺欄邊展袖回眸",
    action: "人物一手扶欄，一手揚起鸞羽披帛，像剛從高階迎風轉身而立",
  },
  {
    slug: "cloud-princess",
    role: "倚雲帝姬",
    aliases: ["帝姬", "倚雲"],
    prop: "雲紋團扇與星石",
    midground: "真人帝姬斜倚雲榻前端神情清醒",
    action: "人物一手扶住雲榻，一手把團扇垂在膝側，肩線鬆弛但保留高位角色的威儀",
  },
  {
    slug: "zither-envoy",
    role: "撫琴仙使",
    aliases: ["仙使", "撫琴"],
    prop: "古琴與流光酒盞",
    midground: "真人仙使在琴台側坐轉身望來",
    action: "人物一手停在琴弦上，一手扶住酒盞，像在仙宴中剛把一段曲意收回胸前",
  },
  {
    slug: "fox-queen",
    role: "照雪狐后",
    aliases: ["狐后", "照雪"],
    prop: "狐火與白羽扇",
    midground: "真人狐后立在雪林前景光裡回身定格",
    action: "人物一手托住狐火，一手將羽扇收在身後，身體輕扭形成尾火與雪霧的視覺旋律",
  },
  {
    slug: "lotus-reclining",
    role: "臥蓮仙尊",
    aliases: ["仙尊", "臥蓮"],
    prop: "蓮盞與流霞枕",
    midground: "真人仙尊側倚蓮台前端凝望鏡頭",
    action: "人物一手扶蓮台，一手托住蓮盞，長袖與外紗順著台階垂下形成飄逸層次",
  },
];

const silkroadVariants = [
  {
    slug: "veil-princess",
    role: "回紗王姬",
    aliases: ["王姬", "回紗"],
    prop: "金紗面簾與香盒",
    midground: "真人王姬側身穿過拱門後回望",
    action: "人物一手拂開面簾，一手托住香盒，髮飾與薄紗一起沿身側滑落",
  },
  {
    slug: "dance-priestess",
    role: "旋燈祭姬",
    aliases: ["祭姬", "旋燈"],
    prop: "銅燈與鈴鐲",
    midground: "真人祭姬在神殿臺階半旋身停步",
    action: "人物一手提住銅燈，一手揚起披紗，像舞步剛收在腳尖前方",
  },
  {
    slug: "caravan-lady",
    role: "牽駝女官",
    aliases: ["女官", "牽駝"],
    prop: "駝鈴與絲路卷圖",
    midground: "真人女官站在駝隊前端拉住韁繩回身",
    action: "人物一手扣住韁繩，一手壓住卷圖，腳步保留剛經過沙丘坡面的前進勢能",
  },
  {
    slug: "balcony-singer",
    role: "倚樓樂伎",
    aliases: ["樂伎", "倚樓"],
    prop: "箜篌與葡萄酒杯",
    midground: "真人樂伎斜坐樓台欄邊向下回眸",
    action: "人物一手搭住欄杆，一手托著酒杯，箜篌靠在腿側形成異域夜宴氣息",
  },
  {
    slug: "moon-envoy",
    role: "照月使臣",
    aliases: ["使臣", "照月"],
    prop: "銀盤與寶石短杖",
    midground: "真人使臣立在月庭中央微微前傾",
    action: "人物一手托銀盤，一手持短杖垂落，肩頸向鏡頭前送形成迎賓般的戲劇感",
  },
];

const darkRoyalVariants = [
  {
    slug: "couch-empress",
    role: "倚榻魔后",
    aliases: ["魔后", "倚榻"],
    prop: "水晶酒盞與絲枕",
    midground: "真人魔后側倚臥榻前端，臉部明亮清楚",
    action: "人物一手扶榻邊，一手托住酒盞，真絲睡袍與罩紗沿榻角自然垂墜形成成熟夜宴氣場",
  },
  {
    slug: "gauze-enchantress",
    role: "撩紗夜姬",
    aliases: ["夜姬", "撩紗"],
    prop: "薄紗披帛與腰鏈",
    midground: "真人夜姬由帷幕邊緣側身探出回眸",
    action: "人物一手拂起薄紗，一手壓住垂墜腰鏈，肩頸線條在燭影間形成柔亮轉折",
  },
  {
    slug: "chair-queen",
    role: "扶椅冕下",
    aliases: ["冕下", "扶椅"],
    prop: "黑金高背椅與玫瑰酒杯",
    midground: "真人冕下半倚椅背斜向鏡頭",
    action: "人物一手扶住椅背，一手垂持酒杯，晨袍式外層在腿側疊出高訂夜宴輪廓",
  },
  {
    slug: "banquet-host",
    role: "側臥宴主",
    aliases: ["宴主", "側臥"],
    prop: "葡萄串與寶石托盤",
    midground: "真人宴主半臥於長榻，視線越過肩側看向鏡頭",
    action: "人物一手扶著托盤，一手收住榻上的薄紗罩裙，身體側線延長但不誇張扭曲",
  },
  {
    slug: "soul-glance",
    role: "回眸裁魂",
    aliases: ["回眸", "裁魂"],
    prop: "黑羽扇與紫晶項鍊",
    midground: "真人裁魂者緩步經過月窗後回身停步",
    action: "人物一手垂握黑羽扇，一手輕觸鎖骨項鍊，回眸動勢像剛把整座夜宴留在身後",
  },
  {
    slug: "curtain-lord",
    role: "分帳魅主",
    aliases: ["魅主", "分帳"],
    prop: "絲絨床幔與燭台",
    midground: "真人魅主自床幔之後半步走出",
    action: "人物一手分開帷幕，一手提住燭台，垂墜腰鏈在步伐裡自然晃動形成成熟誘惑氛圍",
  },
  {
    slug: "stair-priestess",
    role: "斜坐祭女",
    aliases: ["祭女", "斜坐"],
    prop: "月石法典與銀燭",
    midground: "真人祭女斜坐石階前端偏頭看來",
    action: "人物一手扶著石階，一手抱住法典，真絲外層沿腿線流下形成高密度海報質感",
  },
  {
    slug: "chain-queen",
    role: "垂鏈妖后",
    aliases: ["妖后", "垂鏈"],
    prop: "垂墜腰鏈與長柄酒杯",
    midground: "真人妖后立在月宴花廳邊緣半靠柱身",
    action: "人物一手輕觸腰鏈，一手持長柄酒杯垂在腿側，姿態像剛從華麗夜宴中轉身離席",
  },
];

const westernVariants = [
  {
    slug: "balustrade-duchess",
    role: "倚欄女公",
    aliases: ["女公", "倚欄"],
    prop: "羽毛扇與金杯",
    midground: "真人女公倚在石欄前緣回身停步",
    action: "人物一手扶欄，一手垂持羽毛扇，裙撐與披肩在石欄陰影裡形成華麗輪廓",
  },
  {
    slug: "opera-countess",
    role: "停幕伯爵夫人",
    aliases: ["伯爵夫人", "歌劇"],
    prop: "面具與歌劇手冊",
    midground: "真人伯爵夫人站在歌劇幕前微偏頭",
    action: "人物一手持面具垂在身側，一手壓住手冊邊角，像剛從包廂步入舞台前廳",
  },
  {
    slug: "rose-marchioness",
    role: "捻花侯爵",
    aliases: ["侯爵", "玫瑰"],
    prop: "玫瑰與蕾絲手套",
    midground: "真人侯爵斜坐在花園椅前端抬眸",
    action: "人物一手捻住玫瑰枝，一手扶椅側，長裙與蕾絲形成柔亮而不僵直的坐姿線條",
  },
  {
    slug: "waltz-heiress",
    role: "回舞名媛",
    aliases: ["名媛", "回舞"],
    prop: "水晶酒杯與緞帶手套",
    midground: "真人名媛停在旋舞後的半轉身角度",
    action: "人物一手托著酒杯，一手收住裙側，腳尖與裙擺仍保留剛轉身時的圓弧動態",
  },
  {
    slug: "library-lady",
    role: "把卷女爵",
    aliases: ["女爵", "書閣"],
    prop: "古籍與金邊眼鏡",
    midground: "真人女爵靠在書閣長桌邊緣回望",
    action: "人物一手壓住古籍，一手摘下眼鏡垂於指間，像在密談前收住一句未說出口的台詞",
  },
  {
    slug: "fountain-princess",
    role: "臨泉公主",
    aliases: ["公主", "臨泉"],
    prop: "珍珠手包與披肩",
    midground: "真人公主走近噴泉邊緣後停步回身",
    action: "人物一手攬住披肩，一手持手包貼近裙側，身體順著噴泉弧線形成柔和前傾",
  },
];

const travelVariants = [
  {
    slug: "walking-traveler",
    role: "回身旅人",
    aliases: ["旅人", "回身"],
    prop: "相機與薄外套",
    midground: "真人旅人在街角或步道上行進後回身看向鏡頭",
    action: "人物一手扶住相機帶，一手牽起外套邊緣，腳步保留正在前行的節奏",
  },
  {
    slug: "railing-viewer",
    role: "倚景行者",
    aliases: ["行者", "倚景"],
    prop: "欄杆與咖啡杯",
    midground: "真人旅人靠近欄邊側身望景後回眸",
    action: "人物一手扶欄，一手垂持咖啡杯，肩頸從風景方向轉回鏡頭形成輕鬆電影感",
  },
  {
    slug: "umbrella-muse",
    role: "扶傘映旅",
    aliases: ["雨旅", "扶傘"],
    prop: "雨傘與手提包",
    midground: "真人旅人撐傘站在階梯或石路轉角",
    action: "人物一手扶傘柄，一手提住包袋，濕地反光與裙角動態把畫面撐滿",
  },
  {
    slug: "seated-postcard",
    role: "側坐漫遊",
    aliases: ["側坐", "漫遊"],
    prop: "明信片與草帽",
    midground: "真人旅人坐在矮牆或長椅前端抬眸",
    action: "人物一手壓住明信片，一手扶著草帽邊緣，坐姿保留旅途中短暫歇腳的鬆弛感",
  },
  {
    slug: "dress-swing",
    role: "拂裙遠望",
    aliases: ["拂裙", "遠望"],
    prop: "飄帶披肩與地標地圖",
    midground: "真人旅人站在景點前沿著風向半轉身",
    action: "人物一手拂起裙角或披肩，一手握住地圖，髮絲與衣料共同帶出地點氣流感",
  },
];

const modernVariants = [
  {
    slug: "crosswalk-lead",
    role: "回街女主",
    aliases: ["女主", "街拍"],
    prop: "手機與風衣",
    midground: "真人女主走過街口後回身看來",
    action: "人物一手握手機，一手拉住風衣下襬，腳步停在斑馬線邊緣仍保有節奏",
  },
  {
    slug: "glass-lean",
    role: "倚窗總監",
    aliases: ["總監", "落地窗"],
    prop: "文件夾與咖啡杯",
    midground: "真人總監倚近玻璃窗邊微偏頭",
    action: "人物一手扶住窗邊，一手拿著文件夾與咖啡杯，姿態像會議後短暫抽離城市噪音",
  },
  {
    slug: "night-cafe",
    role: "提杯名流",
    aliases: ["名流", "咖啡館"],
    prop: "咖啡杯與墨鏡",
    midground: "真人名流坐在街角咖啡館外緣回眸",
    action: "人物一手提杯，一手把墨鏡垂在腿側，坐姿俐落但不端正僵硬",
  },
  {
    slug: "platform-thriller",
    role: "扶箱旅監",
    aliases: ["旅監", "月台"],
    prop: "行李箱與車票",
    midground: "真人旅監站在月台側前方回身停步",
    action: "人物一手扶住行李箱拉桿，一手捏著車票，身體剛從前行收住成電影般懸念感",
  },
  {
    slug: "neon-agent",
    role: "按耳特務",
    aliases: ["特務", "霓虹"],
    prop: "耳機與資料卡",
    midground: "真人特務站在霓虹巷口光帶裡偏身回看",
    action: "人物一手按住耳機，一手垂持資料卡，光影沿著外套與長靴把角色邊線拉得乾淨有力",
  },
];

const fairyVariants = [
  {
    slug: "petal-queen",
    role: "捻瓣花后",
    aliases: ["花后", "捻瓣"],
    prop: "花瓣與晶露杯",
    midground: "真人花后側倚花架前端回眸",
    action: "人物一手捻住花瓣，一手托著晶露杯，薄紗與花藤一起沿身側垂下形成夢幻層次",
  },
  {
    slug: "dew-spirit",
    role: "扶露仙靈",
    aliases: ["仙靈", "扶露"],
    prop: "露珠瓶與藤枝",
    midground: "真人仙靈走在花徑中途回身停步",
    action: "人物一手提起露珠瓶，一手扶著藤枝，腳步像正穿過晨霧與花雨",
  },
  {
    slug: "swing-princess",
    role: "側坐藤姬",
    aliases: ["藤姬", "側坐"],
    prop: "花藤鞦韆與花束",
    midground: "真人藤姬坐在鞦韆前端偏頭看來",
    action: "人物一手握住藤繩，一手抱住花束，坐姿保留鞦韆剛停止時的微微擺盪",
  },
  {
    slug: "butterfly-keeper",
    role: "迎蝶守護者",
    aliases: ["守護者", "迎蝶"],
    prop: "晶蝶與玻璃花枝",
    midground: "真人守護者站在花房中央伸手迎向前景蝶影",
    action: "人物一手托住玻璃花枝，一手向前迎蝶，肩線前送形成溫柔而完整的迎接姿態",
  },
  {
    slug: "lake-muse",
    role: "臨湖夢使",
    aliases: ["夢使", "臨湖"],
    prop: "月燈與水紗",
    midground: "真人夢使沿著湖畔石徑半轉身凝望鏡頭",
    action: "人物一手提月燈，一手拂起水紗，衣料與湖霧一起延展成高亮童話海報感",
  },
];

const historicalSeries = [
  {
    idPrefix: "wave5-historical-threekingdoms-luoshui",
    titlePrefix: "洛水金波",
    parentCategory: "歷史小說名著人物",
    series: "三國風華／洛水名姝",
    themeHint: "三國 名姝 洛水 金波",
    identityPrefix: "三國風華洛水名姝",
    palette: "水藍、胭脂紅與淡金色",
    costumeCore: "漢末華服長裙、流光披帛與垂墜廣袖",
    jewelry: "金步搖、玉佩與珍珠耳墜",
    place: "洛水宮苑與畫橋之間",
    foreground: "落花、水霧、宮燈與絲紗壓鏡",
    background: "洛水橋影、宮闕燈火、曲欄與深層月色",
    lighting: "高亮月夜主光、宮燈暖補光、珠玉反射與水面 sparkle highlights",
    atmosphere: "高密度亮場古典名著海報",
    aliases: ["三國演義", "洛水"],
  },
  {
    idPrefix: "wave5-historical-honglou-garden",
    titlePrefix: "大觀留香",
    parentCategory: "歷史小說名著人物",
    series: "紅樓金釵／花廊綺夢",
    themeHint: "紅樓夢 金釵 花廊 綺夢",
    identityPrefix: "紅樓金釵花廊綺夢",
    palette: "藕粉、湖青與香檳金",
    costumeCore: "清雅襖裙、細紗披帛與織花長比甲",
    jewelry: "玉簪、珍珠耳墜與花玉禁步",
    place: "大觀園花廊與書閣暖庭",
    foreground: "花影、團扇、書卷與窗紗前景",
    background: "大觀園曲橋、花窗、暖閣與深院燈影",
    lighting: "亮場春庭柔光、花影反射、珠玉高光與暖閣景深",
    atmosphere: "高密度亮場古典名著海報",
    aliases: ["紅樓夢", "大觀園"],
  },
  {
    idPrefix: "wave5-historical-jinyong-jianghu",
    titlePrefix: "江湖照影",
    parentCategory: "歷史小說名著人物",
    series: "金庸群俠／風露長歌",
    themeHint: "金庸 武俠 風露 長歌",
    identityPrefix: "金庸群俠風露長歌",
    palette: "竹青、墨黑與冷銀色",
    costumeCore: "江湖俠女勁裝、飄帶披風與貼身長靴",
    jewelry: "銀簪、玉扣與細鏈護腕",
    place: "竹林古道與山門石階之間",
    foreground: "竹葉、劍光、低霧與披風近景",
    background: "山門、石橋、遠峰與江湖夜燈",
    lighting: "明亮月色側光、竹影反射、金屬冷高光與霧中輪廓光",
    atmosphere: "高密度亮場江湖海報",
    aliases: ["金庸", "江湖"],
  },
  {
    idPrefix: "wave5-historical-watermargin-fort",
    titlePrefix: "寨影流霞",
    parentCategory: "歷史小說名著人物",
    series: "水滸傳奇／水寨邊歌",
    themeHint: "水滸 水寨 邊歌 俠影",
    identityPrefix: "水滸傳奇水寨邊歌",
    palette: "赭紅、松煙黑與舊金色",
    costumeCore: "寨中俠姝短襖長裙、束帶披風與皮革長靴",
    jewelry: "木珠髮飾、銅扣與流蘇腰飾",
    place: "水寨碼頭與木樓戰亭之間",
    foreground: "船槳、旗角、水氣與木欄壓鏡",
    background: "木樓、戰旗、河道燈火與深層山影",
    lighting: "高亮水寨火光、月色反射、濕木高光與戰旗輪廓光",
    atmosphere: "高密度亮場名著江湖海報",
    aliases: ["水滸傳", "水寨"],
  },
  {
    idPrefix: "wave5-historical-liaozhai-ghostmoon",
    titlePrefix: "幽窗月痕",
    parentCategory: "歷史小說名著人物",
    series: "聊齋綺譚／狐月花樓",
    themeHint: "聊齋 狐月 花樓 幽窗",
    identityPrefix: "聊齋綺譚狐月花樓",
    palette: "月白、暗玫瑰與煙紫色",
    costumeCore: "薄紗長裙、柔霧外袍與垂墜腰飾",
    jewelry: "月石髮飾、細珠耳墜與銀鏈",
    place: "花樓月窗與古院水亭之間",
    foreground: "珠簾、花瓣、狐火與月紗前景",
    background: "古院燈影、雕窗、曲橋與月色薄霧",
    lighting: "高亮月窗主光、燭火補光、珠玉柔高光與狐火散景",
    atmosphere: "高密度亮場奇譚海報",
    aliases: ["聊齋志異", "狐月"],
  },
];

const dynastySeries = [
  {
    idPrefix: "wave5-dynasty-han-lantern",
    titlePrefix: "漢闕流燈",
    parentCategory: "中國歷代服裝",
    series: "漢代宮闕／流燈華儀",
    themeHint: "漢代 宮闕 流燈 華儀",
    identityPrefix: "漢闕流燈華儀",
    palette: "赭紅、墨玉與鎏金色",
    costumeCore: "曲裾深衣、垂地廣袖與流金披帛",
    jewelry: "鳳紋步搖、玉璧腰佩與鎏金耳墜",
    place: "漢宮流燈長廊與水宴欄側",
    foreground: "宮燈、帷幕、玉案與金煙壓鏡",
    background: "重檐殿閣、朱柱、流燈水影與深宮夜色",
    lighting: "高亮宮燈主光、水面反射、金玉高光與層疊燭影",
    atmosphere: "高密度亮場華麗宮廷海報",
    aliases: ["漢代", "宮闕"],
  },
  {
    idPrefix: "wave5-dynasty-wei-brocade",
    titlePrefix: "魏庭錦照",
    parentCategory: "中國歷代服裝",
    series: "魏晉風流／錦照瓊席",
    themeHint: "魏晉 風流 錦照 瓊席",
    identityPrefix: "魏庭錦照瓊席",
    palette: "月白、石青與暖金色",
    costumeCore: "魏晉寬袖長衫、流雲披帛與飄帶深衣",
    jewelry: "玉簪、月石耳墜與流蘇禁步",
    place: "魏庭花席與曲水高臺",
    foreground: "花箋、曲水杯、紗幕與月影前景",
    background: "高臺畫屏、曲水流觴、遠亭與清夜天光",
    lighting: "高亮月庭主光、席間暖燈、絲紗透光與玉飾反射",
    atmosphere: "高密度亮場華麗古典海報",
    aliases: ["魏晉", "風流"],
  },
  {
    idPrefix: "wave5-dynasty-sui-ceremony",
    titlePrefix: "隋宮霞儀",
    parentCategory: "中國歷代服裝",
    series: "隋宮禮宴／霞儀花殿",
    themeHint: "隋代 禮宴 霞儀 花殿",
    identityPrefix: "隋宮霞儀花殿",
    palette: "胭脂紅、米金與象牙白",
    costumeCore: "隋宮重工長裙、流霞披帛與珠繡半臂",
    jewelry: "金步搖、紅玉耳飾與細珠頸鏈",
    place: "隋宮花殿與金欄長階",
    foreground: "花枝、金燈、珠簾與披帛壓鏡",
    background: "花殿、金欄、彩亭與遠層宮門燈火",
    lighting: "高亮花宴主光、燭火補照、珠寶 sparkle highlights 與白紗透光",
    atmosphere: "高密度亮場華麗宮廷海報",
    aliases: ["隋代", "花殿"],
  },
  {
    idPrefix: "wave5-dynasty-tang-peony",
    titlePrefix: "唐庭花照",
    parentCategory: "中國歷代服裝",
    series: "盛唐華宴／牡丹金庭",
    themeHint: "盛唐 華宴 牡丹 金庭",
    identityPrefix: "盛唐花照金庭",
    palette: "牡丹紅、孔雀綠與鎏金色",
    costumeCore: "盛唐寬領長裙、多層披帛與透光罩紗",
    jewelry: "花鈿金冠、寶石耳墜與細鏈腰飾",
    place: "盛唐夜宴花庭與牡丹石臺",
    foreground: "櫻花、牡丹、宮燈、珠寶與薄紗壓鏡",
    background: "花亭、宮殿燈火、畫屏、石階與長安夜景",
    lighting: "高亮商業奇幻主光、珠寶高光、宮燈暖補光與花瓣散景",
    atmosphere: "高密度亮場華麗海報",
    aliases: ["唐代", "盛唐", "花宴"],
  },
  {
    idPrefix: "wave5-dynasty-song-incense",
    titlePrefix: "宋閣焚香",
    parentCategory: "中國歷代服裝",
    series: "宋韻雅集／焚香書庭",
    themeHint: "宋代 雅集 焚香 書庭",
    identityPrefix: "宋閣焚香書庭",
    palette: "豆青、月白與淡金色",
    costumeCore: "宋制褙子、細摺長裙與柔紗披帛",
    jewelry: "玉簪、珍珠耳墜與香囊腰佩",
    place: "宋閣書庭與花窗香案",
    foreground: "香煙、卷軸、花窗影與青瓷前景",
    background: "書架、庭竹、畫屏、花窗與晨光深景",
    lighting: "亮場晨光主照、香煙 volumetric light、青瓷反射與玉飾高光",
    atmosphere: "高密度亮場華麗宋韻海報",
    aliases: ["宋代", "雅集"],
  },
  {
    idPrefix: "wave5-dynasty-yuan-desert",
    titlePrefix: "元庭霜馬",
    parentCategory: "中國歷代服裝",
    series: "元代王庭／霜馬行歌",
    themeHint: "元代 王庭 霜馬 行歌",
    identityPrefix: "元庭霜馬行歌",
    palette: "沙金、霜白與墨藍色",
    costumeCore: "元代袍裙、毛邊短氅與皮革腰封",
    jewelry: "銀飾耳環、松石髮扣與金屬護腕",
    place: "元庭營帳與雪原馬道",
    foreground: "毛氅、馬鞍、雪沫與營火前景",
    background: "王帳、旗影、霜野與遠山天光",
    lighting: "高亮霜原天光、營火暖補光、金屬反射與雪面高光",
    atmosphere: "高密度亮場異域宮廷海報",
    aliases: ["元代", "王庭"],
  },
  {
    idPrefix: "wave5-dynasty-ming-peony",
    titlePrefix: "明宮織霞",
    parentCategory: "中國歷代服裝",
    series: "明宮花朝／織霞金殿",
    themeHint: "明代 花朝 織霞 金殿",
    identityPrefix: "明宮織霞金殿",
    palette: "牡丹紅、翡翠綠與宮金色",
    costumeCore: "明制織金長裙、霞帔與多層披帛",
    jewelry: "點翠髮冠、金絲耳墜與花玉禁步",
    place: "明宮花朝花庭與金殿石階",
    foreground: "牡丹、花燈、團扇與流蘇近景",
    background: "彩亭、花海、宮燈、紅牆與深層廊院",
    lighting: "高亮花朝主光、宮燈暖補、珠翠高光與花瓣散景",
    atmosphere: "高密度亮場華麗宮廷海報",
    aliases: ["明代", "花朝"],
  },
  {
    idPrefix: "wave5-dynasty-qing-palace",
    titlePrefix: "清苑珠影",
    parentCategory: "中國歷代服裝",
    series: "清宮珠庭／月廊晚照",
    themeHint: "清代 珠庭 月廊 晚照",
    identityPrefix: "清苑珠影月廊",
    palette: "孔雀藍、胭脂粉與暖金色",
    costumeCore: "清宮旗裝、珠繡外褂與垂地披肩",
    jewelry: "點翠頭面、珍珠耳飾與金絲頸鍊",
    place: "清宮珠庭與月廊花廳",
    foreground: "珠簾、花器、燭影與鏡面壓鏡",
    background: "花窗、月廊、紅牆、宮燈與深層庭院",
    lighting: "亮場月廊主光、燭火補光、鏡面反射與珠飾 sparkle highlights",
    atmosphere: "高密度亮場華麗宮廷海報",
    aliases: ["清代", "清宮"],
  },
  {
    idPrefix: "wave5-dynasty-republic-cheongsam",
    titlePrefix: "海上流金",
    parentCategory: "中國歷代服裝",
    series: "民國綺影／流金畫報",
    themeHint: "民國 綺影 流金 畫報",
    identityPrefix: "海上流金畫報",
    palette: "酒紅、墨綠與香檳金",
    costumeCore: "修身旗袍、真絲披肩與珍珠腰鏈",
    jewelry: "珍珠耳墜、翡翠胸針與細金腕錶",
    place: "海上公館與花窗舞廳之間",
    foreground: "羽毛扇、酒杯、雨痕與霓虹反射",
    background: "雕花樓梯、畫框、舞廳燈火與城市夜景",
    lighting: "高亮商業畫報主光、絲綢高光、玻璃反射與暖金補照",
    atmosphere: "高密度亮場華麗民國海報",
    aliases: ["民國", "旗袍"],
  },
  {
    idPrefix: "wave5-dynasty-ethnic-festival",
    titlePrefix: "華裳映節",
    parentCategory: "中國歷代服裝",
    series: "華夏盛節／彩紋彩堂",
    themeHint: "華夏 盛節 彩紋 彩堂",
    identityPrefix: "華裳映節彩堂",
    palette: "寶石藍、珊瑚紅與亮金色",
    costumeCore: "節慶華服、彩紋披帛與多層飄帶",
    jewelry: "銀鈴頭飾、彩珠耳墜與流蘇腰帶",
    place: "彩堂節宴與花燈廣場",
    foreground: "花燈、彩帶、銀鈴與花瓣前景",
    background: "彩堂、節旗、歌臺、燈海與夜色人間",
    lighting: "高亮節宴主光、花燈補照、彩珠高光與花火散景",
    atmosphere: "高密度亮場華麗盛節海報",
    aliases: ["華服", "節慶"],
  },
];

const wuxiaSeries = [
  {
    idPrefix: "wave5-wuxia-snowridge",
    titlePrefix: "雪嶺寒鋒",
    parentCategory: "武俠江湖 / 戰場女將",
    series: "雪嶺劍門／寒鋒夜雪",
    themeHint: "雪嶺 劍門 寒鋒 夜雪",
    identityPrefix: "雪嶺劍門寒鋒",
    palette: "雪白、墨黑與冷銀色",
    costumeCore: "俠女勁裝、長披風與綁腿長靴",
    jewelry: "銀簪、冰紋腰扣與細鏈護腕",
    place: "雪嶺石階與劍門山道",
    foreground: "雪沫、劍光、披風與松枝壓鏡",
    background: "山門、雪松、峭壁與冷月天光",
    lighting: "高亮雪地反光、月色側光、金屬冷高光與霧雪景深",
    atmosphere: "高密度亮場武俠海報",
    aliases: ["雪嶺", "劍門"],
  },
  {
    idPrefix: "wave5-wuxia-desert-frontier",
    titlePrefix: "邊城流焰",
    parentCategory: "武俠江湖 / 戰場女將",
    series: "大漠邊城／落日征袍",
    themeHint: "大漠 邊城 落日 征袍",
    identityPrefix: "大漠邊城征袍",
    palette: "赭紅、沙金與墨綠色",
    costumeCore: "邊城女將戰袍、披風與皮革護具",
    jewelry: "金屬耳環、松石腰帶與革扣護腕",
    place: "大漠城牆與烽火馬道",
    foreground: "風沙、戰旗、馬鞍與披風前景",
    background: "城牆、烽火、騎影與落日天幕",
    lighting: "高亮落日主光、烽火補照、金屬反射與風沙 haze",
    atmosphere: "高密度亮場戰場海報",
    aliases: ["邊城", "大漠"],
  },
  {
    idPrefix: "wave5-wuxia-riverfort",
    titlePrefix: "水寨驚瀾",
    parentCategory: "武俠江湖 / 戰場女將",
    series: "煙波水寨／驚瀾夜歌",
    themeHint: "煙波 水寨 驚瀾 夜歌",
    identityPrefix: "煙波水寨驚瀾",
    palette: "湖青、木棕與淡金色",
    costumeCore: "江湖短襖長裙、防水披肩與快靴",
    jewelry: "木珠髮帶、銀扣與流蘇腰飾",
    place: "水寨碼頭與橋亭木欄",
    foreground: "船槳、水霧、欄影與酒旗壓鏡",
    background: "碼頭木樓、燈火、河道與遠處夜山",
    lighting: "高亮水面反射、碼頭燈火、木紋高光與濕氣柔霧",
    atmosphere: "高密度亮場江湖海報",
    aliases: ["水寨", "煙波"],
  },
  {
    idPrefix: "wave5-wuxia-warbanner",
    titlePrefix: "戰旗金鼓",
    parentCategory: "武俠江湖 / 戰場女將",
    series: "戰場旌風／金鼓烈歌",
    themeHint: "戰場 旌風 金鼓 烈歌",
    identityPrefix: "戰場旌風金鼓",
    palette: "赤金、玄黑與銅橙色",
    costumeCore: "女帥戰甲、披風與重靴",
    jewelry: "金屬冠片、甲片耳飾與護臂",
    place: "戰鼓高臺與軍陣前沿",
    foreground: "戰鼓、旌旗、甲片與煙塵前景",
    background: "軍陣、長城、烽煙與高天雲層",
    lighting: "高亮戰場主光、火光補照、金屬高光與煙塵透視",
    atmosphere: "高密度亮場史詩戰場海報",
    aliases: ["戰場", "女將"],
  },
  {
    idPrefix: "wave5-wuxia-rain-agency",
    titlePrefix: "梅雨鏢聲",
    parentCategory: "武俠江湖 / 戰場女將",
    series: "梅雨鏢局／夜巷行令",
    themeHint: "梅雨 鏢局 夜巷 行令",
    identityPrefix: "梅雨鏢局行令",
    palette: "墨青、煙灰與暖金色",
    costumeCore: "鏢師勁裝、短斗篷與束袖長裙",
    jewelry: "銀釦髮簪、皮革腰帶與護手",
    place: "雨夜長巷與鏢局門樓",
    foreground: "雨絲、燈籠、水痕與斗篷壓鏡",
    background: "門樓、石巷、招牌與深層燈影",
    lighting: "高亮雨夜補光、濕地反射、燈籠暖光與霧化邊緣光",
    atmosphere: "高密度亮場江湖電影海報",
    aliases: ["鏢局", "雨夜"],
  },
  {
    idPrefix: "wave5-wuxia-pine-temple",
    titlePrefix: "松風玄觀",
    parentCategory: "武俠江湖 / 戰場女將",
    series: "松風古觀／玄門行雪",
    themeHint: "松風 古觀 玄門 行雪",
    identityPrefix: "松風古觀玄門",
    palette: "松綠、霧白與冷金色",
    costumeCore: "道門女俠長衫、披帛短氅與綁帶長靴",
    jewelry: "玉簪、木珠手串與符印腰佩",
    place: "古觀石庭與松風山徑",
    foreground: "符紙、松針、劍穗與晨霧前景",
    background: "古觀、石燈、山徑與雲層深景",
    lighting: "高亮山霧主光、石燈暖補、金屬反射與松針散景",
    atmosphere: "高密度亮場玄門武俠海報",
    aliases: ["古觀", "玄門"],
  },
];

const xianxiaSeries = [
  {
    idPrefix: "wave5-xianxia-moonpalace",
    titlePrefix: "月闕霓輝",
    parentCategory: "仙俠神話 / 古裝陸劇",
    series: "月宮仙闕／霓輝長宴",
    themeHint: "月宮 仙闕 霓輝 長宴",
    identityPrefix: "月闕霓輝仙闕",
    palette: "月白、銀藍與淡金色",
    costumeCore: "月宮長裙、透明飛紗與流光披帛",
    jewelry: "月石髮冠、銀鏈耳飾與星紋腰佩",
    place: "月闕仙橋與雲階花庭",
    foreground: "月紗、星塵、仙燈與花瓣壓鏡",
    background: "月橋、雲海、仙殿、花樹與遠層星河",
    lighting: "高亮月色主光、仙燈補照、珠玉高光與星塵景深",
    atmosphere: "高密度亮場華麗仙俠海報",
    aliases: ["月宮", "仙闕"],
  },
  {
    idPrefix: "wave5-xianxia-penglai",
    titlePrefix: "蓬萊潮月",
    parentCategory: "仙俠神話 / 古裝陸劇",
    series: "蓬萊海國／潮月靈宴",
    themeHint: "蓬萊 海國 潮月 靈宴",
    identityPrefix: "蓬萊潮月海國",
    palette: "海藍、珠白與香檳金",
    costumeCore: "海國仙裙、水紗外層與珠鏈腰飾",
    jewelry: "珍珠冠飾、海晶耳墜與貝光頸鏈",
    place: "蓬萊潮庭與海橋水榭",
    foreground: "水珠、潮紗、蓮燈與貝影前景",
    background: "潮庭、海橋、玉階、浪光與遠處仙島",
    lighting: "高亮潮光主照、水面反射、珍珠高光與海霧柔化光",
    atmosphere: "高密度亮場華麗仙俠海報",
    aliases: ["蓬萊", "海國"],
  },
  {
    idPrefix: "wave5-xianxia-phoenix",
    titlePrefix: "鸞庭焰照",
    parentCategory: "仙俠神話 / 古裝陸劇",
    series: "青鸞天闕／焰照花朝",
    themeHint: "青鸞 天闕 焰照 花朝",
    identityPrefix: "鸞庭焰照天闕",
    palette: "石榴紅、金橙與孔雀綠",
    costumeCore: "鳳紋仙裙、火羽披帛與垂地長袖",
    jewelry: "鸞羽金冠、紅玉耳墜與金鈴腰飾",
    place: "青鸞高臺與花朝金庭",
    foreground: "火羽、花瓣、金燈與彩紗壓鏡",
    background: "高臺、花庭、金闕、燈海與雲層深景",
    lighting: "高亮花朝主光、金燈補照、火羽高光與花瓣散景",
    atmosphere: "高密度亮場華麗仙俠海報",
    aliases: ["青鸞", "花朝"],
  },
  {
    idPrefix: "wave5-xianxia-frost",
    titlePrefix: "霜宮琉夜",
    parentCategory: "仙俠神話 / 古裝陸劇",
    series: "玄冰神域／琉夜霜庭",
    themeHint: "玄冰 神域 琉夜 霜庭",
    identityPrefix: "霜宮琉夜神域",
    palette: "冰藍、銀白與霜紫色",
    costumeCore: "玄冰仙裙、霜紗斗篷與水晶腰鏈",
    jewelry: "冰晶冠飾、銀雪耳墜與霜鏈臂釧",
    place: "霜宮冰橋與月雪神庭",
    foreground: "冰晶、雪霧、月燈與長紗前景",
    background: "冰橋、神庭、極光、雪林與琉璃殿影",
    lighting: "高亮冰面反射、月光主照、冰晶高光與雪霧散景",
    atmosphere: "高密度亮場華麗仙俠海報",
    aliases: ["玄冰", "神域"],
  },
  {
    idPrefix: "wave5-xianxia-herbvalley",
    titlePrefix: "藥谷星岫",
    parentCategory: "仙俠神話 / 古裝陸劇",
    series: "星河藥谷／靈露仙庭",
    themeHint: "星河 藥谷 靈露 仙庭",
    identityPrefix: "藥谷星岫仙庭",
    palette: "嫩綠、露白與淡金色",
    costumeCore: "藥谷仙裙、薄霧外紗與藤葉腰封",
    jewelry: "花葉冠、玉露耳墜與靈草手鏈",
    place: "藥谷花階與靈泉花廊",
    foreground: "靈草、露珠、玉瓶與花霧前景",
    background: "靈泉、花谷、木橋、藥閣與晨光山影",
    lighting: "高亮晨光主照、露珠 sparkle highlights、花霧漫射與玉瓶反光",
    atmosphere: "高密度亮場華麗仙俠海報",
    aliases: ["藥谷", "靈露"],
  },
  {
    idPrefix: "wave5-xianxia-swordsect",
    titlePrefix: "雲巔劍照",
    parentCategory: "仙俠神話 / 古裝陸劇",
    series: "雲巔劍宗／劍照天階",
    themeHint: "雲巔 劍宗 劍照 天階",
    identityPrefix: "雲巔劍照天階",
    palette: "雲白、墨青與冷銀色",
    costumeCore: "劍修長袍、束腰披風與流線長靴",
    jewelry: "銀簪、劍穗腰扣與玉石護腕",
    place: "雲巔石階與劍宗天台",
    foreground: "劍穗、流雲、低霧與光帶壓鏡",
    background: "天台、石門、雲海、遠峰與晨曦",
    lighting: "高亮雲海反射、晨曦主光、金屬冷高光與霧中輪廓光",
    atmosphere: "高密度亮場華麗仙俠海報",
    aliases: ["劍宗", "雲巔"],
  },
  {
    idPrefix: "wave5-xianxia-peachrealm",
    titlePrefix: "桃源瓊夢",
    parentCategory: "仙俠神話 / 古裝陸劇",
    series: "桃源靈境／瓊夢春庭",
    themeHint: "桃源 靈境 瓊夢 春庭",
    identityPrefix: "桃源瓊夢春庭",
    palette: "桃粉、嫩綠與香檳金",
    costumeCore: "桃源靈裙、柔紗披帛與花枝腰鏈",
    jewelry: "花冠、粉晶耳墜與花葉手鏈",
    place: "桃源花橋與春庭水榭",
    foreground: "桃花、花霧、珠燈與飄紗前景",
    background: "花橋、水榭、桃林、仙亭與暖色雲海",
    lighting: "高亮春庭主光、花霧散射、珠燈補照與花瓣景深",
    atmosphere: "高密度亮場華麗仙俠海報",
    aliases: ["桃源", "靈境"],
  },
  {
    idPrefix: "wave5-xianxia-dragoncourt",
    titlePrefix: "龍闕流潮",
    parentCategory: "仙俠神話 / 古裝陸劇",
    series: "龍宮潮庭／流潮夜宴",
    themeHint: "龍宮 潮庭 流潮 夜宴",
    identityPrefix: "龍闕流潮夜宴",
    palette: "孔雀藍、珠白與金綠色",
    costumeCore: "龍宮禮裙、水紋外紗與垂珠披帛",
    jewelry: "龍紋冠飾、珍珠耳墜與海珠腰鏈",
    place: "龍宮潮庭與珊瑚水階",
    foreground: "珊瑚、潮珠、水紗與水光前景",
    background: "潮庭、龍柱、海橋、玉階與深海光帶",
    lighting: "高亮水紋主光、潮珠反射、海底體積光與珍珠高光",
    atmosphere: "高密度亮場華麗仙俠海報",
    aliases: ["龍宮", "潮庭"],
  },
  {
    idPrefix: "wave5-xianxia-foxforest",
    titlePrefix: "狐月森歌",
    parentCategory: "仙俠神話 / 古裝陸劇",
    series: "九尾月森／狐火花境",
    themeHint: "九尾 月森 狐火 花境",
    identityPrefix: "狐月森歌花境",
    palette: "月白、暗玫瑰與霧紫色",
    costumeCore: "狐族長裙、柔霧薄紗與尾火腰飾",
    jewelry: "月石冠、細珠耳墜與狐火頸鏈",
    place: "狐月花境與月森石橋",
    foreground: "狐火、花瓣、銀霧與珠簾壓鏡",
    background: "月森、石橋、花樹、燈盞與霧光深景",
    lighting: "高亮月色主光、狐火補照、銀霧反光與花瓣散景",
    atmosphere: "高密度亮場華麗仙俠海報",
    aliases: ["九尾", "月森"],
  },
  {
    idPrefix: "wave5-xianxia-glassshrine",
    titlePrefix: "琉璃梵光",
    parentCategory: "仙俠神話 / 古裝陸劇",
    series: "琉璃梵境／梵光蓮臺",
    themeHint: "琉璃 梵境 梵光 蓮臺",
    identityPrefix: "琉璃梵光蓮臺",
    palette: "琉璃白、蓮粉與淺金色",
    costumeCore: "梵境長裙、半透外紗與垂地雲袖",
    jewelry: "琉璃冠、金珠耳飾與蓮瓣腰鏈",
    place: "梵境蓮臺與琉璃月廊",
    foreground: "琉璃燈、蓮花、薄霧與垂紗前景",
    background: "蓮臺、月廊、白塔、花海與雲光深景",
    lighting: "高亮琉璃反射、暖燈補照、蓮瓣高光與雲霧漫射",
    atmosphere: "高密度亮場華麗仙俠海報",
    aliases: ["琉璃", "梵境"],
  },
];

const silkroadSeries = [
  {
    idPrefix: "wave5-silkroad-dunhuang",
    titlePrefix: "敦煌飛彩",
    parentCategory: "東方異域 / 絲路西域",
    series: "敦煌妙舞／飛彩月壁",
    themeHint: "敦煌 妙舞 飛彩 月壁",
    identityPrefix: "敦煌飛彩月壁",
    palette: "石榴紅、松石綠與沙金色",
    costumeCore: "敦煌飛天長裙、半透明披帛與金線腰封",
    jewelry: "金鈴頭飾、青金石耳墜與流蘇臂釧",
    place: "敦煌壁殿與月色石階",
    foreground: "飛紗、燭台、花瓣與壁畫前景",
    background: "石窟壁畫、拱門、宮燈與月色大漠",
    lighting: "高亮殿燈主光、月色補照、金飾反射與飛紗透光",
    atmosphere: "高密度亮場異域海報",
    aliases: ["敦煌", "飛天"],
  },
  {
    idPrefix: "wave5-silkroad-kucha",
    titlePrefix: "龜茲絃月",
    parentCategory: "東方異域 / 絲路西域",
    series: "龜茲樂舞／絃月珠庭",
    themeHint: "龜茲 樂舞 絃月 珠庭",
    identityPrefix: "龜茲絃月珠庭",
    palette: "孔雀藍、琥珀金與葡萄紫",
    costumeCore: "西域舞姬長裙、珠鍊披紗與露肩外層",
    jewelry: "寶石頭鏈、金鈴耳飾與垂珠腰鏈",
    place: "龜茲珠庭與樂舞高臺",
    foreground: "珠簾、箜篌、葡萄與金燈前景",
    background: "拱廊、樂臺、彩壁與夜宴燈火",
    lighting: "高亮夜宴主光、琥珀反射、寶石高光與葡萄色空氣透視",
    atmosphere: "高密度亮場異域海報",
    aliases: ["龜茲", "樂舞"],
  },
  {
    idPrefix: "wave5-silkroad-loulan",
    titlePrefix: "樓蘭香霧",
    parentCategory: "東方異域 / 絲路西域",
    series: "樓蘭香城／香霧花庭",
    themeHint: "樓蘭 香城 香霧 花庭",
    identityPrefix: "樓蘭香霧花庭",
    palette: "琥珀橙、玫瑰紅與深青色",
    costumeCore: "樓蘭王裔紗裙、長披肩與金片腰飾",
    jewelry: "琥珀冠飾、玫瑰金耳墜與流蘇項鍊",
    place: "樓蘭花庭與香霧水池",
    foreground: "香煙、玫瑰、紗幔與金盤前景",
    background: "拱門、水池、花燈與大漠夜色",
    lighting: "高亮香庭主光、燭火補照、琥珀高光與香霧柔焦",
    atmosphere: "高密度亮場異域海報",
    aliases: ["樓蘭", "香城"],
  },
  {
    idPrefix: "wave5-silkroad-persian",
    titlePrefix: "波庭月錦",
    parentCategory: "東方異域 / 絲路西域",
    series: "波斯月庭／月錦流歌",
    themeHint: "波斯 月庭 月錦 流歌",
    identityPrefix: "波庭月錦流歌",
    palette: "祖母綠、深藍與亮金色",
    costumeCore: "波斯宮廷長裙、金絲面紗與垂墜披帛",
    jewelry: "寶石額鏈、金環耳飾與細鏈腰飾",
    place: "波斯月庭與噴泉拱廊",
    foreground: "面紗、玫瑰、噴泉水珠與地毯前景",
    background: "拱廊、月庭、噴泉、宮燈與藍夜天幕",
    lighting: "高亮月庭主光、噴泉反射、金飾高光與深藍空氣層次",
    atmosphere: "高密度亮場異域海報",
    aliases: ["波斯", "月庭"],
  },
];

const darkRoyalSeries = [
  {
    idPrefix: "wave5-dark-succubus-nocturne",
    titlePrefix: "夜綺裁心",
    parentCategory: "奇幻異世界 / 暗黑王族",
    series: "夜宴魅魔／綺帳裁魂",
    themeHint: "魅魔 夜宴 綺帳 裁魂",
    identityPrefix: "夜綺裁心魅魔",
    palette: "酒紅、黑金與香檳粉",
    costumeCore: "寶石紅真絲睡袍、晨袍式外層、薄紗罩裙與垂墜腰鏈",
    jewelry: "紅寶耳墜、細鏈鎖骨飾與垂墜腰鏈",
    place: "夜宴床幔與花燭月廳",
    foreground: "絲枕、酒盞、花瓣、床幔與燭影壓鏡",
    background: "月光窗紗、宮殿臥榻、玫瑰花飾與深層燈火",
    lighting: "高亮夜宴主光、燭火補照、真絲高光、寶石反射與月紗柔光",
    atmosphere: "高密度亮場暗黑浪漫海報",
    cupSize: "K",
    aliases: ["魅魔", "夜宴"],
  },
  {
    idPrefix: "wave5-dark-bloodmoon-royal",
    titlePrefix: "血月流宴",
    parentCategory: "奇幻異世界 / 暗黑王族",
    series: "血月王庭／絲絨夜詠",
    themeHint: "血月 王庭 絲絨 夜詠",
    identityPrefix: "血月流宴王庭",
    palette: "深紅、黑曜石與古金色",
    costumeCore: "深紅真絲晨袍、透光薄紗內搭、開衩罩裙與水晶腰鏈",
    jewelry: "黑曜耳飾、血珀頸鏈與寶石腰飾",
    place: "血月高窗與絲絨宴榻",
    foreground: "絲絨靠枕、黑玫瑰、金杯與帷幕前景",
    background: "高窗月影、王座欄柱、夜宴燭海與深色花屏",
    lighting: "高亮月窗主光、燭海補照、絲絨反射與寶石 sparkle highlights",
    atmosphere: "高密度亮場暗黑浪漫海報",
    cupSize: "K",
    aliases: ["血月", "王庭"],
  },
  {
    idPrefix: "wave5-dark-fallen-feather",
    titlePrefix: "墮羽低歌",
    parentCategory: "奇幻異世界 / 暗黑王族",
    series: "墮羽神殿／黑羽冕座",
    themeHint: "墮羽 神殿 黑羽 冕座",
    identityPrefix: "墮羽低歌神殿",
    palette: "黑羽灰、月銀與暗紫色",
    costumeCore: "月銀睡袍、黑羽披肩、半透薄紗內襯與垂鏈腰封",
    jewelry: "銀羽耳飾、黑羽項鍊與月石腰鏈",
    place: "墮羽神殿與月台石榻",
    foreground: "黑羽、燭台、石玫瑰與薄霧前景",
    background: "高柱、月台、彩窗、羽幕與深色殿影",
    lighting: "高亮月台主光、彩窗反射、銀羽高光與霧光分層",
    atmosphere: "高密度亮場暗黑奇幻海報",
    cupSize: "K",
    aliases: ["墮羽", "黑羽"],
  },
  {
    idPrefix: "wave5-dark-frost-silk",
    titlePrefix: "霜綃留燭",
    parentCategory: "奇幻異世界 / 暗黑王族",
    series: "冰綃寢宮／霜燭低歌",
    themeHint: "冰綃 寢宮 霜燭 低歌",
    identityPrefix: "霜綃留燭寢宮",
    palette: "冰藍、霧白與香檳銀",
    costumeCore: "冰藍真絲睡袍、霜白罩紗、柔軟晨袍外層與水晶腰鏈",
    jewelry: "水晶耳墜、雪銀頸鏈與霜花手鏈",
    place: "霜燭寢宮與冰窗暖榻",
    foreground: "冰晶、絲枕、銀燭與薄紗前景",
    background: "冰窗月光、暖榻、銀屏、雪枝與宮燈",
    lighting: "高亮冰窗主光、銀燭補照、真絲反光與冰晶 sparkle highlights",
    atmosphere: "高密度亮場暗黑浪漫海報",
    cupSize: "K",
    aliases: ["冰綃", "寢宮"],
  },
  {
    idPrefix: "wave5-dark-violet-opera",
    titlePrefix: "紫曜綺歌",
    parentCategory: "奇幻異世界 / 暗黑王族",
    series: "紫曜歌劇／薔燼花廳",
    themeHint: "紫曜 歌劇 薔燼 花廳",
    identityPrefix: "紫曜綺歌花廳",
    palette: "紫晶、玫瑰黑與琥珀金",
    costumeCore: "紫晶睡袍、玫瑰色薄紗內搭、流動罩裙與寶石腰鏈",
    jewelry: "紫晶耳墜、玫金鎖骨鏈與琥珀腰飾",
    place: "薔燼花廳與歌劇臥榻",
    foreground: "玫瑰、燭台、珠簾與絲絨椅背前景",
    background: "歌劇高窗、花廳、月影、燈海與深層幕簾",
    lighting: "高亮歌劇主光、琥珀燭火、真絲高光與紫晶反射",
    atmosphere: "高密度亮場暗黑浪漫海報",
    cupSize: "K",
    aliases: ["紫曜", "歌劇"],
  },
];

const westernSeries = [
  {
    idPrefix: "wave5-western-versailles",
    titlePrefix: "凡宮晨玫",
    parentCategory: "西方古典 / 歐陸史詩",
    series: "凡爾賽花鏡／晨玫金庭",
    themeHint: "凡爾賽 花鏡 晨玫 金庭",
    identityPrefix: "凡宮晨玫金庭",
    palette: "玫瑰粉、宮金與象牙白",
    costumeCore: "宮廷禮裙、蕾絲披肩與層疊裙撐",
    jewelry: "珍珠冠飾、玫瑰金耳墜與胸針",
    place: "凡爾賽花鏡與噴泉庭園",
    foreground: "玫瑰、噴泉水珠、羽扇與欄影前景",
    background: "花鏡、噴泉、修剪花園、雕像與宮殿長廊",
    lighting: "高亮花園主光、噴泉反射、金飾高光與玫瑰散景",
    atmosphere: "高密度亮場歐陸史詩海報",
    aliases: ["凡爾賽", "花鏡"],
  },
  {
    idPrefix: "wave5-western-venetian",
    titlePrefix: "威城金幕",
    parentCategory: "西方古典 / 歐陸史詩",
    series: "威尼斯歌劇／金幕夜詠",
    themeHint: "威尼斯 歌劇 金幕 夜詠",
    identityPrefix: "威城金幕夜詠",
    palette: "酒紅、古金與夜藍色",
    costumeCore: "歌劇禮服、絲絨披肩與層疊裙撐",
    jewelry: "古金花冠、紅寶耳墜與面具胸針",
    place: "威尼斯歌劇院與金幕前廳",
    foreground: "面具、紅幕、金欄與燭影前景",
    background: "歌劇包廂、吊燈、金幕與深層長廊",
    lighting: "高亮劇院金光、絲絨反射、吊燈 sparkle highlights 與夜藍輪廓光",
    atmosphere: "高密度亮場歐陸史詩海報",
    aliases: ["威尼斯", "歌劇"],
  },
  {
    idPrefix: "wave5-western-vienna",
    titlePrefix: "維廳流樂",
    parentCategory: "西方古典 / 歐陸史詩",
    series: "維也納金廳／流樂夜宴",
    themeHint: "維也納 金廳 流樂 夜宴",
    identityPrefix: "維廳流樂夜宴",
    palette: "香檳金、象牙白與酒紅色",
    costumeCore: "華爾滋禮裙、薄紗披肩與束腰長手套",
    jewelry: "水晶耳飾、金鍊頸飾與胸針",
    place: "維也納金廳與舞會長廳",
    foreground: "樂譜、酒杯、吊燈光斑與紗裙前景",
    background: "金廳、樂隊臺、拱頂、鏡面與舞會人影遠景",
    lighting: "高亮舞廳主光、吊燈補照、水晶高光與鏡面反射",
    atmosphere: "高密度亮場歐陸史詩海報",
    aliases: ["維也納", "金廳"],
  },
  {
    idPrefix: "wave5-western-florence",
    titlePrefix: "佛城穹彩",
    parentCategory: "西方古典 / 歐陸史詩",
    series: "佛羅倫斯穹頂／彩穹日宴",
    themeHint: "佛羅倫斯 穹頂 彩穹 日宴",
    identityPrefix: "佛城穹彩日宴",
    palette: "橄欖綠、陶紅與古金色",
    costumeCore: "文藝復興長裙、披肩外層與垂感腰封",
    jewelry: "古金髮鏈、祖母綠耳墜與戒指",
    place: "佛羅倫斯穹頂陽臺與石柱長廊",
    foreground: "石柱、畫冊、花束與日光前景",
    background: "穹頂、紅瓦、鐘樓、陽臺與遠層城景",
    lighting: "高亮日宴主光、石牆反射、金屬高光與暖色空氣透視",
    atmosphere: "高密度亮場歐陸史詩海報",
    aliases: ["佛羅倫斯", "穹頂"],
  },
  {
    idPrefix: "wave5-western-seville",
    titlePrefix: "塞宮燦影",
    parentCategory: "西方古典 / 歐陸史詩",
    series: "塞維亞玫宮／燦影暮宴",
    themeHint: "塞維亞 玫宮 燦影 暮宴",
    identityPrefix: "塞宮燦影暮宴",
    palette: "深紅、黑蕾絲與古金色",
    costumeCore: "西班牙宮廷禮裙、蕾絲肩披與層疊裙襬",
    jewelry: "玫瑰髮飾、金環耳墜與寶石胸針",
    place: "塞維亞玫宮與噴泉拱庭",
    foreground: "玫瑰、折扇、噴泉水珠與黑蕾絲前景",
    background: "拱庭、壁磚、噴泉、暮色天空與暖燈長廊",
    lighting: "高亮暮宴主光、暖燈補照、蕾絲透光與水珠高光",
    atmosphere: "高密度亮場歐陸史詩海報",
    aliases: ["塞維亞", "玫宮"],
  },
];

const travelSeries = [
  {
    idPrefix: "wave5-travel-taipei",
    titlePrefix: "台北雨虹",
    parentCategory: "世界景點旅拍",
    series: "台北城景／雨虹夜街",
    themeHint: "台北 城景 雨虹 夜街",
    identityPrefix: "台北雨虹夜街",
    palette: "霓虹粉、夜藍與冷銀色",
    costumeCore: "都會旅拍長裙、輕風衣與真絲內搭",
    jewelry: "銀色耳飾、細鍊項鍊與皮革腰包",
    place: "台北雨夜街口與霓虹騎樓",
    foreground: "雨滴、招牌反光、雨傘與濕地前景",
    background: "騎樓、車流、招牌、高樓與霓虹倒影",
    lighting: "高亮霓虹邊緣光、濕地反射、車燈補照與夜霧景深",
    atmosphere: "高密度亮場城市旅拍海報",
    aliases: ["台北", "雨夜"],
  },
  {
    idPrefix: "wave5-travel-jiufen",
    titlePrefix: "九份燈階",
    parentCategory: "世界景點旅拍",
    series: "山城夜路／燈階茶香",
    themeHint: "九份 山城 燈階 茶香",
    identityPrefix: "九份燈階茶香",
    palette: "酒紅、墨綠與燈籠金",
    costumeCore: "復古長裙、披肩外套與細紋絲巾",
    jewelry: "珍珠耳飾、金色髮夾與小巧手包",
    place: "九份石階與紅燈茶樓",
    foreground: "燈籠、石階、雨傘與茶煙前景",
    background: "茶樓、山城屋頂、海面遠光與夜霧",
    lighting: "高亮燈籠主光、濕石反射、茶樓暖補光與山霧層次",
    atmosphere: "高密度亮場景點旅拍海報",
    aliases: ["九份", "山城"],
  },
  {
    idPrefix: "wave5-travel-kyoto",
    titlePrefix: "京町花隱",
    parentCategory: "世界景點旅拍",
    series: "京都花町／紙燈春巷",
    themeHint: "京都 花町 紙燈 春巷",
    identityPrefix: "京町花隱春巷",
    palette: "櫻粉、靛藍與暖米色",
    costumeCore: "改良和風長裙、短外褂與腰帶",
    jewelry: "珍珠耳飾、花簪與布結手包",
    place: "京都花町石路與紙燈小巷",
    foreground: "紙燈、花瓣、木格窗與和傘前景",
    background: "石路、町屋、櫻樹、暖燈與遠層巷景",
    lighting: "高亮春巷主光、紙燈補照、花瓣反射與木窗暖光",
    atmosphere: "高密度亮場景點旅拍海報",
    aliases: ["京都", "花町"],
  },
  {
    idPrefix: "wave5-travel-paris",
    titlePrefix: "巴黎金橋",
    parentCategory: "世界景點旅拍",
    series: "巴黎河岸／金橋暮色",
    themeHint: "巴黎 河岸 金橋 暮色",
    identityPrefix: "巴黎金橋暮色",
    palette: "香檳金、象牙白與黑色",
    costumeCore: "高級旅拍洋裝、長版風衣與絲巾",
    jewelry: "珍珠耳飾、細金腕錶與手拿包",
    place: "巴黎石橋與塞納河岸",
    foreground: "欄杆、咖啡杯、橋燈與河面反光前景",
    background: "石橋、河岸建築、遠層鐵塔與暮色天際線",
    lighting: "高亮暮色主光、橋燈補照、河面反射與金色空氣透視",
    atmosphere: "高密度亮場景點旅拍海報",
    aliases: ["巴黎", "塞納河"],
  },
  {
    idPrefix: "wave5-travel-venice",
    titlePrefix: "水城晨影",
    parentCategory: "世界景點旅拍",
    series: "威尼斯水巷／晨影花船",
    themeHint: "威尼斯 水巷 晨影 花船",
    identityPrefix: "水城晨影花船",
    palette: "湖藍、象牙白與古金色",
    costumeCore: "輕盈長裙、薄披肩與寬腰帶",
    jewelry: "珍珠耳飾、古金髮夾與小手包",
    place: "威尼斯運河橋與花船碼頭",
    foreground: "船槳、欄杆、水紋與面具前景",
    background: "運河、橋梁、彩色建築與晨霧光帶",
    lighting: "高亮晨光主照、水面反射、橋影補光與霧氣層次",
    atmosphere: "高密度亮場景點旅拍海報",
    aliases: ["威尼斯", "水巷"],
  },
  {
    idPrefix: "wave5-travel-santorini",
    titlePrefix: "聖島藍崖",
    parentCategory: "世界景點旅拍",
    series: "聖托里尼／藍崖白亭",
    themeHint: "聖托里尼 藍崖 白亭 海風",
    identityPrefix: "聖島藍崖白亭",
    palette: "海藍、純白與日光金",
    costumeCore: "海島長裙、白色罩衫與飄帶披肩",
    jewelry: "金色耳飾、藍石項鍊與涼感手鍊",
    place: "聖托里尼藍崖與白牆露臺",
    foreground: "白牆、花盆、海風紗與欄影前景",
    background: "藍頂教堂、愛琴海、層層白屋與日光天空",
    lighting: "高亮海島日光、白牆反射、海面高光與清透空氣",
    atmosphere: "高密度亮場景點旅拍海報",
    aliases: ["聖托里尼", "愛琴海"],
  },
  {
    idPrefix: "wave5-travel-marrakech",
    titlePrefix: "紅城暮香",
    parentCategory: "世界景點旅拍",
    series: "馬拉喀什／暮香拱庭",
    themeHint: "馬拉喀什 暮香 拱庭 異域",
    identityPrefix: "紅城暮香拱庭",
    palette: "陶紅、祖母綠與亮金色",
    costumeCore: "異域旅拍長裙、薄紗罩衫與金屬腰鏈",
    jewelry: "金環耳飾、彩石項鍊與手鐲",
    place: "馬拉喀什拱庭與香料市集",
    foreground: "地毯、香料盤、噴泉水珠與紗幔前景",
    background: "拱庭、市集、暖牆、棕櫚與暮色天光",
    lighting: "高亮暮色主光、暖牆反射、金屬高光與空氣香霧",
    atmosphere: "高密度亮場景點旅拍海報",
    aliases: ["馬拉喀什", "拱庭"],
  },
  {
    idPrefix: "wave5-travel-cappadocia",
    titlePrefix: "風谷曙空",
    parentCategory: "世界景點旅拍",
    series: "卡帕多奇亞／曙空石谷",
    themeHint: "卡帕多奇亞 曙空 石谷 熱氣球",
    identityPrefix: "風谷曙空石谷",
    palette: "沙粉、天藍與日出金",
    costumeCore: "旅行長裙、針織外套與飄帶披肩",
    jewelry: "小金耳飾、編繩項鍊與皮革腰包",
    place: "卡帕多奇亞石谷與熱氣球觀景點",
    foreground: "草帽、熱氣球繩、岩壁與晨霧前景",
    background: "奇岩、熱氣球群、谷地與日出天空",
    lighting: "高亮日出主光、岩壁反射、氣球點色與晨霧層次",
    atmosphere: "高密度亮場景點旅拍海報",
    aliases: ["卡帕多奇亞", "熱氣球"],
  },
  {
    idPrefix: "wave5-travel-iceland",
    titlePrefix: "冰洲暮藍",
    parentCategory: "世界景點旅拍",
    series: "冰島黑沙／暮藍極境",
    themeHint: "冰島 黑沙 暮藍 極境",
    identityPrefix: "冰洲暮藍極境",
    palette: "冰藍、黑沙灰與月白色",
    costumeCore: "極地旅拍大衣、針織內搭與長靴",
    jewelry: "銀色耳釘、圍巾扣與皮革手套",
    place: "冰島黑沙灘與海蝕岩岸",
    foreground: "黑沙、海風、圍巾與浪花前景",
    background: "玄武岩、海浪、雲層與極境天光",
    lighting: "高亮海天漫射、浪花反光、黑沙對比與冷色空氣透視",
    atmosphere: "高密度亮場景點旅拍海報",
    aliases: ["冰島", "黑沙"],
  },
  {
    idPrefix: "wave5-travel-swiss",
    titlePrefix: "湖鎮晨鐘",
    parentCategory: "世界景點旅拍",
    series: "瑞士湖鎮／晨鐘雪光",
    themeHint: "瑞士 湖鎮 晨鐘 雪光",
    identityPrefix: "湖鎮晨鐘雪光",
    palette: "湖綠、象牙白與松木金",
    costumeCore: "湖鎮旅拍長裙、針織披肩與短靴",
    jewelry: "珍珠耳飾、木質項鍊與細帶手包",
    place: "瑞士湖鎮碼頭與花窗小街",
    foreground: "湖水、欄杆、花箱與圍巾前景",
    background: "湖鎮屋頂、鐘樓、雪山與晨光天空",
    lighting: "高亮晨光主照、湖面反射、木窗暖補光與雪山高光",
    atmosphere: "高密度亮場景點旅拍海報",
    aliases: ["瑞士", "湖鎮"],
  },
  {
    idPrefix: "wave5-travel-prague",
    titlePrefix: "布城晨霧",
    parentCategory: "世界景點旅拍",
    series: "布拉格石橋／晨霧鐘影",
    themeHint: "布拉格 石橋 晨霧 鐘影",
    identityPrefix: "布城晨霧鐘影",
    palette: "石灰灰、酒紅與暖金色",
    costumeCore: "古城旅拍長裙、毛呢大衣與絲巾",
    jewelry: "金色耳飾、復古腕錶與小手包",
    place: "布拉格石橋與老城鐘樓街",
    foreground: "石欄、咖啡杯、霧氣與鴿影遠景",
    background: "石橋、鐘樓、尖塔、暖燈與晨霧街景",
    lighting: "高亮晨霧漫射、街燈補照、石牆反射與金色景深",
    atmosphere: "高密度亮場景點旅拍海報",
    aliases: ["布拉格", "石橋"],
  },
  {
    idPrefix: "wave5-travel-singapore",
    titlePrefix: "海灣花穹",
    parentCategory: "世界景點旅拍",
    series: "新加坡濱海／花穹流光",
    themeHint: "新加坡 濱海 花穹 流光",
    identityPrefix: "海灣花穹流光",
    palette: "翠綠、香檳金與夜藍色",
    costumeCore: "城市度假長裙、薄西裝外套與高跟鞋",
    jewelry: "金屬耳飾、簡鍊項鍊與手拿包",
    place: "濱海花穹與超級樹步道",
    foreground: "玻璃穹頂反光、花束、欄杆與光點前景",
    background: "超級樹、花穹、城市燈海與濱海夜景",
    lighting: "高亮城市夜光、玻璃反射、花穹補照與濱海景深",
    atmosphere: "高密度亮場景點旅拍海報",
    aliases: ["新加坡", "濱海灣"],
  },
];

const modernSeries = [
  {
    idPrefix: "wave5-modern-taipei",
    titlePrefix: "台城霓步",
    parentCategory: "現代都市 / 街拍電影",
    series: "台北夜街／霓步主場",
    themeHint: "台北 夜街 霓步 主場",
    identityPrefix: "台城霓步主場",
    palette: "夜藍、霓虹粉與冷銀色",
    costumeCore: "俐落風衣、真絲內搭與高腰長褲",
    jewelry: "銀色耳飾、金屬腰帶與細鍊項鍊",
    place: "台北霓虹街口與騎樓雨道",
    foreground: "招牌反射、濕地、雨絲與透明傘前景",
    background: "騎樓、車流、高樓、霓虹與廣告屏光帶",
    lighting: "高亮霓虹主光、濕地反射、車燈補照與城市夜霧",
    atmosphere: "高密度亮場都市電影海報",
    aliases: ["台北", "霓虹"],
  },
  {
    idPrefix: "wave5-modern-seoul",
    titlePrefix: "清潭流光",
    parentCategory: "現代都市 / 街拍電影",
    series: "首爾清潭／流光名場",
    themeHint: "首爾 清潭 流光 名場",
    identityPrefix: "清潭流光名場",
    palette: "奶油白、焦糖棕與黑色",
    costumeCore: "短版外套、針織洋裝與長靴",
    jewelry: "珍珠耳飾、細金項鍊與迷你手袋",
    place: "首爾清潭街角與精品咖啡館",
    foreground: "玻璃倒影、咖啡杯、街燈與櫥窗前景",
    background: "街樹、店面燈光、城市 bokeh 與遠層車流",
    lighting: "高亮咖啡館主光、櫥窗反射、街燈補照與奶油色柔光",
    atmosphere: "高密度亮場都市電影海報",
    aliases: ["首爾", "清潭"],
  },
  {
    idPrefix: "wave5-modern-shanghai",
    titlePrefix: "海上玻光",
    parentCategory: "現代都市 / 街拍電影",
    series: "上海都芯／玻光敘事",
    themeHint: "上海 都芯 玻光 敘事",
    identityPrefix: "海上玻光敘事",
    palette: "炭黑、象牙白與冷銀色",
    costumeCore: "結構西裝、長版大衣與真絲襯衫",
    jewelry: "鑽石耳飾、金屬腕錶與細皮帶",
    place: "上海高樓玻璃辦公層與外灘欄岸",
    foreground: "玻璃反射、文件夾、咖啡杯與欄影前景",
    background: "天際線、燈帶、城市反光與外灘夜景",
    lighting: "高亮辦公冷光、城市反射、銀色高光與玻璃景深",
    atmosphere: "高密度亮場都市電影海報",
    aliases: ["上海", "玻璃城"],
  },
  {
    idPrefix: "wave5-modern-hongkong",
    titlePrefix: "港灣夜速",
    parentCategory: "現代都市 / 街拍電影",
    series: "香港維港／夜速霓景",
    themeHint: "香港 維港 夜速 霓景",
    identityPrefix: "港灣夜速霓景",
    palette: "黑色、卡其與霓虹金",
    costumeCore: "長版風衣、黑色內搭與高跟靴",
    jewelry: "金色耳飾、皮革腰帶與小手包",
    place: "香港維港海旁與高架街道",
    foreground: "欄杆、咖啡杯、海風紗與車燈前景",
    background: "維港燈海、摩天樓、海旁步道與夜霧",
    lighting: "高亮港灣霓光、海面反射、車燈補照與風衣邊緣光",
    atmosphere: "高密度亮場都市電影海報",
    aliases: ["香港", "維港"],
  },
  {
    idPrefix: "wave5-modern-tokyo",
    titlePrefix: "東京電雨",
    parentCategory: "現代都市 / 街拍電影",
    series: "東京賽博／電雨追光",
    themeHint: "東京 賽博 電雨 追光",
    identityPrefix: "東京電雨追光",
    palette: "黑色、電藍與紫紅色",
    costumeCore: "機能外套、貼合內搭與防水腰封",
    jewelry: "金屬耳飾、透明面板吊飾與發光腕帶",
    place: "東京賽博巷口與雨夜廣告街",
    foreground: "雨滴、霓虹牌、資料卡與濕牆前景",
    background: "招牌、管線、濕地、城市光帶與遠景車流",
    lighting: "高亮霓虹電光、濕地反射、紫紅 rim light 與雨霧層次",
    atmosphere: "高密度亮場都市電影海報",
    aliases: ["東京", "賽博"],
  },
  {
    idPrefix: "wave5-modern-paris",
    titlePrefix: "左岸金影",
    parentCategory: "現代都市 / 街拍電影",
    series: "巴黎左岸／金影片場",
    themeHint: "巴黎 左岸 金影 片場",
    identityPrefix: "左岸金影片場",
    palette: "象牙白、酒紅與暖金色",
    costumeCore: "時裝週洋裝、長風衣與高跟鞋",
    jewelry: "珍珠耳飾、腕錶與手拿包",
    place: "巴黎左岸石街與時裝週外場",
    foreground: "石街、咖啡桌、欄杆與車燈前景",
    background: "歐式街景、櫥窗、街燈、遠橋與夜暮天空",
    lighting: "高亮片場補光、街燈暖照、石街反射與金色景深",
    atmosphere: "高密度亮場都市電影海報",
    aliases: ["巴黎", "左岸"],
  },
];

const fairySeries = [
  {
    idPrefix: "wave5-fairy-rosehall",
    titlePrefix: "玫庭香曜",
    parentCategory: "花園童話 / 自然精靈",
    series: "玫瑰花廊／香曜晨庭",
    themeHint: "玫瑰 花廊 香曜 晨庭",
    identityPrefix: "玫庭香曜晨庭",
    palette: "玫瑰粉、奶油白與香檳金",
    costumeCore: "玫瑰禮裙、半透薄紗與花瓣腰飾",
    jewelry: "玫瑰金冠、珍珠耳墜與花瓣手鏈",
    place: "玫瑰花廊與噴泉晨庭",
    foreground: "玫瑰、茶杯、蕾絲桌布與花霧前景",
    background: "拱門、噴泉、花牆、玻璃溫室與晨光",
    lighting: "高亮晨庭主光、噴泉反射、花瓣高光與柔霧散景",
    atmosphere: "高密度亮場童話海報",
    aliases: ["玫瑰", "花廊"],
  },
  {
    idPrefix: "wave5-fairy-wisteria",
    titlePrefix: "紫藤月徑",
    parentCategory: "花園童話 / 自然精靈",
    series: "紫藤月庭／月徑霧歌",
    themeHint: "紫藤 月庭 月徑 霧歌",
    identityPrefix: "紫藤月徑霧歌",
    palette: "霧紫、月白與銀色",
    costumeCore: "紫藤薄紗禮服、花藤披帛與細藤腰封",
    jewelry: "銀藤冠、紫晶耳墜與花穗項鍊",
    place: "紫藤月庭與花徑小橋",
    foreground: "紫藤、月燈、露珠與花瓣前景",
    background: "藤架、小橋、花海、月光與玻璃溫室",
    lighting: "高亮月庭主光、露珠 sparkle highlights、銀色柔光與花瓣景深",
    atmosphere: "高密度亮場童話海報",
    aliases: ["紫藤", "月庭"],
  },
  {
    idPrefix: "wave5-fairy-lilylake",
    titlePrefix: "百合晨露",
    parentCategory: "花園童話 / 自然精靈",
    series: "百合水庭／晨露靈波",
    themeHint: "百合 水庭 晨露 靈波",
    identityPrefix: "百合晨露靈波",
    palette: "百合白、湖綠與淡金色",
    costumeCore: "百合長裙、透明水紗與葉片腰飾",
    jewelry: "百合花冠、珍珠耳墜與金葉頸鏈",
    place: "百合水庭與湖畔石徑",
    foreground: "百合、露珠、水紗與玻璃水盞前景",
    background: "池水、噴泉、花亭、白橋與晨光",
    lighting: "高亮晨光主照、水面反射、百合白高光與柔和 bokeh",
    atmosphere: "高密度亮場童話海報",
    aliases: ["百合", "水庭"],
  },
  {
    idPrefix: "wave5-fairy-sunmeadow",
    titlePrefix: "向陽琥境",
    parentCategory: "花園童話 / 自然精靈",
    series: "向日葵原／琥境夏歌",
    themeHint: "向日葵 原野 琥境 夏歌",
    identityPrefix: "向陽琥境夏歌",
    palette: "向日葵黃、天空藍與麥穗金",
    costumeCore: "夏日花神長裙、麥穗披肩與金葉腰飾",
    jewelry: "向日葵冠、金色耳飾與琥珀項鍊",
    place: "向日葵花田與木柵小徑",
    foreground: "向日葵、草帽、麥穗與花粉前景",
    background: "大片花田、木柵欄、藍天與遠山",
    lighting: "高亮夏日主光、花瓣反射、金色 haze 與清透天空",
    atmosphere: "高密度亮場童話海報",
    aliases: ["向日葵", "花田"],
  },
  {
    idPrefix: "wave5-fairy-fernmist",
    titlePrefix: "蕨庭煙翠",
    parentCategory: "花園童話 / 自然精靈",
    series: "蕨庭森林／煙翠露谷",
    themeHint: "蕨庭 森林 煙翠 露谷",
    identityPrefix: "蕨庭煙翠露谷",
    palette: "苔綠、露白與木金色",
    costumeCore: "森林精靈長裙、葉脈披肩與藤蔓腰封",
    jewelry: "木葉花冠、露珠耳墜與藤紋手鏈",
    place: "蕨庭森林與露谷木橋",
    foreground: "蕨葉、露珠、蘑菇與霧絲前景",
    background: "古樹、木橋、螢光花、溪流與晨霧",
    lighting: "高亮森林光束、露珠高光、霧氣漫射與綠意反射",
    atmosphere: "高密度亮場童話海報",
    aliases: ["蕨庭", "森林"],
  },
  {
    idPrefix: "wave5-fairy-crystalbutterfly",
    titlePrefix: "晶蝶花穹",
    parentCategory: "花園童話 / 自然精靈",
    series: "晶蝶花房／花穹流光",
    themeHint: "晶蝶 花房 花穹 流光",
    identityPrefix: "晶蝶花穹流光",
    palette: "薄荷綠、粉藍與透明銀",
    costumeCore: "晶蝶禮服、透明披帛與水晶腰飾",
    jewelry: "水晶髮冠、透明耳墜與銀線手鏈",
    place: "晶蝶花房與玻璃穹頂步道",
    foreground: "晶蝶、玻璃花枝、光斑與透明紗前景",
    background: "溫室屋頂、花架、水晶植物與陽光",
    lighting: "高亮玻璃折射光、粉藍高光、柔和 bloom 與清透空氣",
    atmosphere: "高密度亮場童話海報",
    aliases: ["晶蝶", "花房"],
  },
];

export const FIFTH_WAVE_PROFILE_DEFS = [
  ...historicalSeries.flatMap((seriesConfig) => buildProfiles(seriesConfig, historicalVariants)),
  ...dynastySeries.flatMap((seriesConfig) => buildProfiles(seriesConfig, dynastyVariants)),
  ...wuxiaSeries.flatMap((seriesConfig) => buildProfiles(seriesConfig, wuxiaVariants)),
  ...xianxiaSeries.flatMap((seriesConfig) => buildProfiles(seriesConfig, xianxiaVariants)),
  ...silkroadSeries.flatMap((seriesConfig) => buildProfiles(seriesConfig, silkroadVariants)),
  ...darkRoyalSeries.flatMap((seriesConfig) => buildProfiles(seriesConfig, darkRoyalVariants)),
  ...westernSeries.flatMap((seriesConfig) => buildProfiles(seriesConfig, westernVariants)),
  ...travelSeries.flatMap((seriesConfig) => buildProfiles(seriesConfig, travelVariants)),
  ...modernSeries.flatMap((seriesConfig) => buildProfiles(seriesConfig, modernVariants)),
  ...fairySeries.flatMap((seriesConfig) => buildProfiles(seriesConfig, fairyVariants)),
];
