export const TANG_MUSICIAN_PROFILE_DEFS = [
  {
    id: "wave4-tangmusic-pearl-lute-courtesan",
    title: "唐珠回韻・琵琶歌伎",
    parentCategory: "中國歷代服裝",
    series: "大唐歌宴／珠閣琵琶",
    themeHint: "大唐 歌伎 琵琶 夜宴",
    aliases: ["大唐歌伎", "琵琶歌伎", "夜宴樂姬", "珠閣樂伎"],
    identity: "大唐珠閣琵琶歌伎",
    palette: "石榴紅、珠金與孔雀綠",
    costumeCore: "盛唐低胸長裙、珠繡披帛與透光外紗",
    jewelry: "金鈴步搖、寶石耳墜與珠鏈腰飾",
    prop: "琵琶與酒盞",
    place: "長安珠閣夜宴臺",
    foreground: "珠簾、花瓣、酒盞與琵琶邊框",
    midground: "真人歌伎坐於矮榻前緣抱琵琶回眸",
    background: "宮燈、畫屏、花宴賓席與長廊燈火",
    action: "人物一手按住琵琶弦，一手扶榻邊半坐回望，像剛停住一段勾人慢板",
    lighting: "高亮夜宴主光、珠寶 sparkle highlights 與琵琶木面反射",
  },
  {
    id: "wave4-tangmusic-lantern-steps-singer",
    title: "長安燈階・慢板歌姬",
    parentCategory: "中國歷代服裝",
    series: "大唐歌宴／燈階清唱",
    themeHint: "大唐 歌姬 燈階 花宴",
    aliases: ["大唐歌姬", "慢板歌姬", "長安花宴", "燈階歌伎"],
    identity: "長安燈階慢板歌姬",
    palette: "牡丹紅、香檳金與象牙白",
    costumeCore: "盛唐歌姬長裙、花雲披帛與層疊罩紗",
    jewelry: "花鈿金冠、流蘇耳飾與玉珠腰鏈",
    prop: "花枝與檀板",
    place: "長安花庭燈階",
    foreground: "花枝、宮燈、檀板與飄紗",
    midground: "真人歌姬沿燈階側身停步",
    background: "花庭、彩亭、夜宴屏風與深層宮廊",
    action: "人物一手提住檀板，一手收起披帛踏下石階回眸，像被喝彩聲喚住",
    lighting: "亮場花宴主光、宮燈補光與絲綢珠金高光",
  },
  {
    id: "wave4-tangmusic-cloud-harp-performer",
    title: "雲臺流拍・箜篌樂姬",
    parentCategory: "中國歷代服裝",
    series: "大唐歌宴／雲臺箜篌",
    themeHint: "大唐 樂姬 箜篌 雲臺",
    aliases: ["大唐樂姬", "箜篌樂姬", "雲臺歌宴", "飛紗樂伎"],
    identity: "雲臺箜篌樂姬",
    palette: "赤金、雲白與湖青色",
    costumeCore: "高腰襦裙、赤金披帛與飛紗長袖",
    jewelry: "鳳羽髮飾、玉石耳墜與鈴飾臂釧",
    prop: "箜篌與雲紋坐墊",
    place: "雲臺樂殿高階",
    foreground: "箜篌弦、雲紗、金粉與花瓣",
    midground: "真人樂姬跪坐在高階坐墊上回身停拍",
    background: "殿柱、壁畫飛天、金燈與高窗日光",
    action: "人物一手勾弦，一手扶坐墊側邊半跪回望，像剛把高潮樂句收在唇邊",
    lighting: "高亮天光與金燈交疊、箜篌弦高光與赤金反射",
  },
  {
    id: "wave4-tangmusic-peony-banquet-dancer",
    title: "牡丹花筵・翻袖伎人",
    parentCategory: "中國歷代服裝",
    series: "大唐歌宴／牡丹花筵",
    themeHint: "大唐 伎人 花筵 翻袖",
    aliases: ["大唐伎人", "翻袖歌伎", "牡丹花宴", "翻袖樂姬"],
    identity: "牡丹花筵翻袖伎人",
    palette: "牡丹紅、孔雀綠與鎏金色",
    costumeCore: "盛唐水袖長裙、飛花披帛與珠繡罩紗",
    jewelry: "花鈿步搖、金玉耳墜與彩珠腰飾",
    prop: "檀板與牡丹花枝",
    place: "牡丹花筵石臺",
    foreground: "牡丹、花瓣、檀板與長袖壓鏡",
    midground: "真人伎人旋袖停在石臺邊緣",
    background: "宮燈、畫亭、花海與殿閣燈火",
    action: "人物一手揚起水袖，一手垂收檀板，腰肩帶出半轉身動勢後停住眼神",
    lighting: "亮場海報主光、花瓣反射與鎏金邊緣光",
  },
  {
    id: "wave4-tangmusic-golden-rail-choir-lady",
    title: "金欄夜拍・清歌樂姝",
    parentCategory: "中國歷代服裝",
    series: "大唐歌宴／金欄清歌",
    themeHint: "大唐 清歌 樂姝 金欄",
    aliases: ["大唐歌宴", "清歌樂姝", "金欄夜宴", "宮廷歌伎"],
    identity: "金欄夜拍清歌樂姝",
    palette: "胭脂紅、玉白與琥珀金",
    costumeCore: "盛唐歌姬華裙、薄霧披肩與珠鏈腰封",
    jewelry: "金步搖、細珠耳墜與月石頸鏈",
    prop: "小金燈與花箋",
    place: "金欄夜宴高臺",
    foreground: "欄杆、花箋、金燈與披肩",
    midground: "真人樂姝倚在金欄旁半坐停步",
    background: "高臺、宮燈、花庭與深層宮階",
    action: "人物一手扶欄，一手持花箋垂落半倚高臺，像剛在唱畢之後偏頭看向鏡頭",
    lighting: "高亮宮燈主照、花箋暖反射與玉白絲紗高光",
  },
  {
    id: "wave4-tangmusic-brocade-screen-soloist",
    title: "錦屏回曲・領調歌姬",
    parentCategory: "中國歷代服裝",
    series: "大唐歌宴／錦屏獨唱",
    themeHint: "大唐 獨唱 歌姬 錦屏",
    aliases: ["領調歌姬", "大唐獨唱", "錦屏歌伎", "內廷樂姬"],
    identity: "錦屏獨唱領調歌姬",
    palette: "蓮粉、金色與水青色",
    costumeCore: "盛唐高腰長裙、織金花紗與長幅披帛",
    jewelry: "寶石花冠、耳鏈與細緻腕飾",
    prop: "團扇與玉笛",
    place: "錦屏花廳內廷",
    foreground: "團扇、錦屏邊框、玉笛與薄紗",
    midground: "真人歌姬由屏風後探身回眸",
    background: "花廳、宮燈、酒席案几與長廊深景",
    action: "人物一手分開屏風邊緣，一手把團扇垂在腿側，像剛自屏後走入主場",
    lighting: "高亮花廳燈光、錦屏反射與寶石點光",
  },
  {
    id: "wave4-tangmusic-moon-porch-bellsinger",
    title: "月廊金鈴・醉拍歌伶",
    parentCategory: "中國歷代服裝",
    series: "大唐歌宴／月廊醉拍",
    themeHint: "大唐 歌伶 月廊 金鈴",
    aliases: ["歌伶", "醉拍歌伶", "月廊夜宴", "金鈴樂姬"],
    identity: "月廊金鈴醉拍歌伶",
    palette: "月白、石榴紅與鎏金色",
    costumeCore: "盛唐長裙、金鈴披帛與垂墜罩紗",
    jewelry: "金鈴臂釧、月石耳飾與細鏈腰飾",
    prop: "酒盞與拍板",
    place: "月廊水榭宴席",
    foreground: "酒盞、拍板、水影與珠簾",
    midground: "真人歌伶倚在榻沿側身坐停",
    background: "月窗、水榭、宮燈與遠處荷池倒影",
    action: "人物一手端住酒盞靠近膝側，一手將拍板收在腰旁，像正要接下一段醉拍",
    lighting: "月光與燈光雙主光、水面反射與金鈴 sparkle highlights",
  },
  {
    id: "wave4-tangmusic-vermilion-drum-lady",
    title: "朱鼓流霞・催拍伎姝",
    parentCategory: "中國歷代服裝",
    series: "大唐歌宴／朱鼓催拍",
    themeHint: "大唐 伎姝 鼓樂 流霞",
    aliases: ["鼓樂歌伎", "催拍伎姝", "朱鼓樂姬", "大唐歌宴"],
    identity: "朱鼓流霞催拍伎姝",
    palette: "朱紅、金橙與孔雀藍",
    costumeCore: "盛唐鼓樂華裙、霞色披帛與流動長袖",
    jewelry: "鳳羽髮冠、金珠耳飾與彩玉臂釧",
    prop: "腰鼓與金槌",
    place: "流霞樂殿前臺",
    foreground: "鼓槌、紗袖、宮燈與花瓣",
    midground: "真人伎姝半蹲在前臺鼓側",
    background: "樂殿、長廊、燈樓與舞宴深景",
    action: "人物一手按住腰鼓邊，一手持鼓槌下垂半蹲回望，像剛把節拍敲在燈海裡",
    lighting: "亮場舞宴主光、鼓面高光與朱紅寶石反射",
  },
  {
    id: "wave4-tangmusic-amber-veil-vocalist",
    title: "琥珀輕綃・試曲歌姬",
    parentCategory: "中國歷代服裝",
    series: "大唐歌宴／輕綃試曲",
    themeHint: "大唐 歌姬 試曲 輕綃",
    aliases: ["試曲歌姬", "輕綃歌伎", "大唐歌姬", "琥珀歌宴"],
    identity: "琥珀輕綃試曲歌姬",
    palette: "琥珀金、藕粉與象牙白",
    costumeCore: "盛唐試曲長裙、半透外紗與垂地披帛",
    jewelry: "琥珀步搖、珍珠耳飾與金線腰鏈",
    prop: "玉簫與香爐",
    place: "輕綃試曲暖閣",
    foreground: "香爐、玉簫、紗幕與燭影",
    midground: "真人歌姬坐於矮凳側前方",
    background: "暖閣、花窗、燈架與屏風層次",
    action: "人物一手扶凳側，一手將玉簫放在腿旁，肩頸微轉回望，像在試曲前停住氣息",
    lighting: "暖閣高亮柔光、琥珀反射與紗幕透光",
  },
  {
    id: "wave4-tangmusic-peach-garden-chorus",
    title: "桃庭新聲・海棠歌姝",
    parentCategory: "中國歷代服裝",
    series: "大唐歌宴／春庭新聲",
    themeHint: "大唐 歌姝 春庭 海棠",
    aliases: ["海棠歌姝", "春庭歌伎", "大唐歌姬", "桃庭樂姬"],
    identity: "桃庭新聲海棠歌姝",
    palette: "海棠粉、芽綠與香檳金",
    costumeCore: "盛唐春宴長裙、海棠披帛與柔霧罩紗",
    jewelry: "海棠花冠、珠串耳墜與玉珠腰飾",
    prop: "海棠花枝與金杯",
    place: "桃庭春宴花階",
    foreground: "海棠、花杯、薄紗與花瓣",
    midground: "真人歌姝在花階邊回身坐停",
    background: "春庭、宮燈、花樹與彩亭遠影",
    action: "人物一手握花枝，一手扶住石階邊緣半坐回眸，像剛在新曲開場時被定格",
    lighting: "高亮春宴主光、花瓣反射與香檳金高光",
  },
];

export const FOURTH_WAVE_PROFILE_DEFS = [
  {
    id: "wave4-western-venetian-opera-duchess",
    title: "威城金幕・歌劇女公",
    parentCategory: "西方古典 / 歐陸史詩",
    series: "歐陸史詩／威城歌劇",
    themeHint: "歐陸 歌劇 女公 金幕",
    aliases: ["歌劇女公", "威尼斯歌劇", "歐陸史詩", "巴洛克"],
    identity: "威城金幕歌劇女公",
    palette: "酒紅、古金與象牙白",
    costumeCore: "歐陸晚宴禮裙、歌劇披肩與層疊裙撐",
    jewelry: "古金冠飾、寶石耳墜與胸針",
    prop: "面具與歌劇手冊",
    place: "威城歌劇院金幕前廳",
    foreground: "面具、紅幕、金欄與燭影",
    midground: "真人女公倚在扶欄旁回身停步",
    background: "歌劇院弧形包廂、金幕、吊燈與長廳深景",
    action: "人物一手持面具垂在身側，一手扶欄回眸，像剛離開包廂走向前臺",
    lighting: "高亮劇院金光、絲絨反射與吊燈 sparkle highlights",
  },
  {
    id: "wave4-western-marble-hall-priestess",
    title: "羅殿晨輝・大理石祭姬",
    parentCategory: "西方古典 / 歐陸史詩",
    series: "歐陸史詩／石殿晨儀",
    themeHint: "歐陸 石殿 祭姬 晨儀",
    aliases: ["石殿祭姬", "歐陸祭司", "大理石聖殿", "文藝復興"],
    identity: "羅殿晨輝大理石祭姬",
    palette: "象牙白、月金與天青色",
    costumeCore: "古典垂褶長裙、金邊披巾與細緻罩紗",
    jewelry: "月桂冠、金葉耳飾與細鏈腕環",
    prop: "香爐與銀杯",
    place: "大理石聖殿拱廳",
    foreground: "香霧、石柱邊影與銀杯",
    midground: "真人祭姬立於石階前緣回身停步",
    background: "巨柱、拱頂、天窗與遠處神壇光束",
    action: "人物一手托銀杯，一手輕扶石柱回眸，像剛結束晨儀轉向鏡頭",
    lighting: "高亮天窗主光、大理石反射與月金邊緣光",
  },
  {
    id: "wave4-western-versailles-rose-princess",
    title: "凡宮玫徑・晨宴公主",
    parentCategory: "西方古典 / 歐陸史詩",
    series: "歐陸史詩／凡宮晨宴",
    themeHint: "歐陸 公主 花園 晨宴",
    aliases: ["凡爾賽公主", "晨宴公主", "法式花園", "歐陸宮廷"],
    identity: "凡宮玫徑晨宴公主",
    palette: "玫瑰粉、象牙白與香檳金",
    costumeCore: "宮廷禮裙、蕾絲外層與花瓣披肩",
    jewelry: "珍珠頭飾、寶石耳釘與腰鍊",
    prop: "玫瑰扇與花束",
    place: "凡宮玫瑰花園長徑",
    foreground: "玫瑰、欄杆、花扇與露珠",
    midground: "真人公主沿花徑半轉身停步",
    background: "花園雕像、噴泉、宮殿窗列與晨光",
    action: "人物一手提起玫瑰扇，一手收住裙側踏步回眸，像剛離開清晨花宴",
    lighting: "高亮晨光、玫瑰反射與珠寶點光",
  },
  {
    id: "wave4-western-cathedral-choir-countess",
    title: "聖堂暮詠・長階女伯",
    parentCategory: "西方古典 / 歐陸史詩",
    series: "歐陸史詩／聖堂暮詠",
    themeHint: "歐陸 聖堂 女伯 暮詠",
    aliases: ["女伯", "聖堂長階", "哥德聖堂", "歐陸史詩"],
    identity: "聖堂暮詠長階女伯",
    palette: "深藍、舊金與石灰白",
    costumeCore: "長裙、披肩與修身外套",
    jewelry: "舊金耳飾、十字胸針與戒指",
    prop: "詩冊與小燭臺",
    place: "聖堂石階拱廊",
    foreground: "詩冊、燭臺、石柱與彩窗光斑",
    midground: "真人女伯坐在石階前緣半回身",
    background: "高拱彩窗、長椅、燭火與穹頂",
    action: "人物一手扶石階，一手持詩冊放在腿側半坐回望，像剛唱畢晚禱",
    lighting: "彩窗亮光、燭火補光與石灰牆漫反射",
  },
  {
    id: "wave4-western-florence-fresco-lady",
    title: "佛城壁暉・濃彩女史",
    parentCategory: "西方古典 / 歐陸史詩",
    series: "歐陸史詩／佛城壁畫廳",
    themeHint: "歐陸 女史 壁畫 廳堂",
    aliases: ["佛羅倫斯", "壁畫女史", "文藝復興", "歐陸女史"],
    identity: "佛城壁暉濃彩女史",
    palette: "赭紅、孔雀綠與古金色",
    costumeCore: "古典禮裙、錦織披巾與垂墜長袖",
    jewelry: "古金髮飾、耳墜與琥珀戒飾",
    prop: "畫卷與筆記冊",
    place: "佛城壁畫長廳",
    foreground: "畫卷、石臺、花瓶與燭光",
    midground: "真人女史倚靠石臺轉身停步",
    background: "壁畫、拱窗、雕柱與天井光束",
    action: "人物一手托畫卷，一手扶石臺回首，像剛從畫作前退開半步",
    lighting: "亮場天井光、壁畫反射與古金細節高光",
  },
  {
    id: "wave4-western-swan-lake-ball-lady",
    title: "湖宮絃宴・白羽名姝",
    parentCategory: "西方古典 / 歐陸史詩",
    series: "歐陸史詩／湖宮舞宴",
    themeHint: "歐陸 舞宴 名姝 湖宮",
    aliases: ["舞宴名姝", "湖宮舞會", "歐陸宮廷", "白羽禮裙"],
    identity: "湖宮絃宴白羽名姝",
    palette: "象牙白、月銀與水藍色",
    costumeCore: "白羽禮裙、垂墜披肩與細紗手套",
    jewelry: "銀晶耳飾、羽冠與細緻項鍊",
    prop: "羽扇與手套",
    place: "湖宮水晶舞廳",
    foreground: "羽扇、欄杆、水晶燈與薄霧",
    midground: "真人名姝倚靠欄邊側身站停",
    background: "舞廳、湖面倒影、拱窗與群燈",
    action: "人物一手持羽扇低垂，一手扶欄輕靠轉肩，像剛從舞池邊退出",
    lighting: "水晶舞燈主光、湖面反射與月銀邊光",
  },
  {
    id: "wave4-western-baroque-library-duchess",
    title: "巴洛書閣・夜紋女爵",
    parentCategory: "西方古典 / 歐陸史詩",
    series: "歐陸史詩／巴洛克書閣",
    themeHint: "巴洛克 女爵 書閣 夜紋",
    aliases: ["巴洛克女爵", "古典書閣", "女爵", "歐陸懸疑"],
    identity: "巴洛書閣夜紋女爵",
    palette: "深酒紅、黑棕與古金色",
    costumeCore: "長禮裙、絲絨肩披與束帶外層",
    jewelry: "古金耳飾、胸針與手環",
    prop: "書冊與眼鏡",
    place: "巴洛克書閣長桌",
    foreground: "書冊、燭臺、羽毛筆與窗影",
    midground: "真人女爵坐在長桌一側回眸",
    background: "高書架、壁燈、木梯與深色天花",
    action: "人物一手扶書冊，一手搭在椅背半側坐回望，像剛從密談裡抬起頭",
    lighting: "暖燭光與窗邊補光、木質反射與古金高光",
  },
  {
    id: "wave4-western-roman-fountain-princess",
    title: "羅泉金雨・石庭王女",
    parentCategory: "西方古典 / 歐陸史詩",
    series: "歐陸史詩／羅泉石庭",
    themeHint: "歐陸 王女 石庭 噴泉",
    aliases: ["石庭王女", "羅馬噴泉", "歐陸公主", "古典旅拍"],
    identity: "羅泉金雨石庭王女",
    palette: "金杏、象牙白與天藍色",
    costumeCore: "古典垂褶長裙、淡紗披肩與細腰帶",
    jewelry: "金葉頭飾、珍珠耳環與手環",
    prop: "月桂枝與小壺",
    place: "羅泉噴泉石庭",
    foreground: "噴泉水滴、月桂枝、石欄與陽光碎點",
    midground: "真人王女坐靠在石欄邊緣",
    background: "噴泉雕像、拱廊、廣場與晴空",
    action: "人物一手扶石欄，一手持月桂枝垂落，半坐回首像剛從石庭宴會歇下",
    lighting: "高亮日光、水滴高光與石庭暖反射",
  },
  {
    id: "wave4-western-golden-courtyard-empress",
    title: "金庭晨鐘・御階皇后",
    parentCategory: "西方古典 / 歐陸史詩",
    series: "歐陸史詩／金庭晨鐘",
    themeHint: "歐陸 皇后 御階 晨鐘",
    aliases: ["歐陸皇后", "御階皇后", "古典王后", "晨鐘宮廷"],
    identity: "金庭晨鐘御階皇后",
    palette: "古金、深藍與象牙白",
    costumeCore: "帝后禮裙、金紋披風與層疊裙身",
    jewelry: "王冠、寶石耳墜與徽章肩鏈",
    prop: "權杖與手套",
    place: "金庭御階長廳",
    foreground: "權杖、欄杆、金毯與燭臺",
    midground: "真人皇后站在御階前緣回身",
    background: "拱廳、吊燈、長毯與遠處王座",
    action: "人物一手扶權杖，一手收住披風轉身回望，像剛從晨儀走下王座階",
    lighting: "高亮吊燈主照、金毯反射與藍金對比高光",
  },
  {
    id: "wave4-western-sapphire-castle-lady",
    title: "藍堡月宴・寶冠淑姝",
    parentCategory: "西方古典 / 歐陸史詩",
    series: "歐陸史詩／藍堡月宴",
    themeHint: "歐陸 月宴 淑姝 城堡",
    aliases: ["城堡月宴", "藍堡淑姝", "歐陸禮服", "古典夜宴"],
    identity: "藍堡月宴寶冠淑姝",
    palette: "寶石藍、月銀與舊金色",
    costumeCore: "寶石藍禮裙、薄紗披肩與垂墜裙擺",
    jewelry: "寶冠、銀鏈耳飾與寶石胸針",
    prop: "酒杯與披肩",
    place: "藍堡月宴石廊",
    foreground: "酒杯、石欄、月光與薄紗",
    midground: "真人淑姝倚在石廊窗邊回首",
    background: "城堡尖塔、夜空、拱窗與遠處燈火",
    action: "人物一手持杯下垂，一手扶窗框側倚回望，像剛從月宴中抽身",
    lighting: "月光主照、室內暖燈補光與寶石藍高光",
  },
  {
    id: "wave4-silkroad-loulan-moon-queen",
    title: "樓蘭月幕・金砂王姬",
    parentCategory: "東方異域 / 絲路西域",
    series: "絲路西域／樓蘭月幕",
    themeHint: "西域 樓蘭 王姬 月幕",
    aliases: ["樓蘭王姬", "絲路王姬", "西域公主", "金砂王姬"],
    identity: "樓蘭月幕金砂王姬",
    palette: "流砂金、石榴紅與夜藍色",
    costumeCore: "西域長裙、金紗頭披與垂鏈腰飾",
    jewelry: "金幣額鏈、寶石耳飾與臂環",
    prop: "月燈與香瓶",
    place: "樓蘭月幕行宮",
    foreground: "香瓶、紗幕、月燈與沙紋",
    midground: "真人王姬倚坐在月榻前緣",
    background: "拱門、燈火、地毯與夜色沙丘",
    action: "人物一手扶榻沿，一手托月燈回身，像剛從行宮內走向帳外夜色",
    lighting: "月光與燈火交疊、金砂反射與珠鏈高光",
  },
  {
    id: "wave4-silkroad-kucha-bell-dancer",
    title: "龜茲金鈴・回旋舞姬",
    parentCategory: "東方異域 / 絲路西域",
    series: "絲路西域／龜茲金鈴",
    themeHint: "西域 舞姬 龜茲 金鈴",
    aliases: ["龜茲舞姬", "金鈴舞姬", "絲路舞伎", "敦煌舞姬"],
    identity: "龜茲金鈴回旋舞姬",
    palette: "寶石藍、琥珀金與赭紅色",
    costumeCore: "西域舞裙、半透頭紗與金鈴腰鏈",
    jewelry: "額鏈、耳墜與金鈴臂飾",
    prop: "手鼓與長紗",
    place: "龜茲樂殿石臺",
    foreground: "長紗、手鼓、花瓣與沙塵",
    midground: "真人舞姬旋身停在石臺邊緣",
    background: "拱頂、壁畫、火盆與樂殿燈光",
    action: "人物一手收住長紗，一手扶鼓半轉身停住，像剛在節拍裡回旋落點",
    lighting: "亮場火盆主光、金鈴反射與寶石藍高光",
  },
  {
    id: "wave4-silkroad-persian-perfume-lady",
    title: "波斯香穹・琥珀名姝",
    parentCategory: "東方異域 / 絲路西域",
    series: "絲路西域／波斯香穹",
    themeHint: "波斯 名姝 香穹 夜宴",
    aliases: ["波斯名姝", "香穹名姝", "異域貴姬", "琥珀夜宴"],
    identity: "波斯香穹琥珀名姝",
    palette: "琥珀金、翡翠綠與酒紅色",
    costumeCore: "波斯垂墜長裙、珠鏈頭紗與半透披肩",
    jewelry: "寶石額鏈、耳墜與金幣腰飾",
    prop: "香氛瓶與手鏡",
    place: "波斯香穹長廊",
    foreground: "香氛瓶、珠簾、燭影與地毯紋樣",
    midground: "真人名姝倚靠拱柱回望",
    background: "彩磚、拱廊、燈火與深色天幕",
    action: "人物一手托香氛瓶，一手扶住拱柱側倚回首，像剛從香宴中走出",
    lighting: "高亮琥珀燈光、彩磚反射與珠鏈 sparkle highlights",
  },
  {
    id: "wave4-silkroad-dunhuang-candle-priestess",
    title: "敦煌燭潮・飛霞祭姬",
    parentCategory: "東方異域 / 絲路西域",
    series: "絲路西域／敦煌燭潮",
    themeHint: "敦煌 祭姬 飛霞 神殿",
    aliases: ["敦煌祭姬", "飛霞祭姬", "西域神殿", "莫高窟"],
    identity: "敦煌燭潮飛霞祭姬",
    palette: "朱金、砂橙與孔雀藍",
    costumeCore: "敦煌長裙、飛霞披帛與金鏈腰封",
    jewelry: "飛天冠飾、寶石耳墜與鈴飾",
    prop: "火盆與蓮燈",
    place: "敦煌燭潮神殿",
    foreground: "火盆、蓮燈、飛紗與壁畫殘框",
    midground: "真人祭姬半跪在神殿前緣",
    background: "石窟壁畫、佛龕、燭光與高窗天光",
    action: "人物一手托起蓮燈，一手扶住階沿半跪回首，像在祭儀中被鏡頭截停",
    lighting: "亮場天光與火盆暖光交疊、金鏈反射與飛紗高光",
  },
  {
    id: "wave4-silkroad-oasis-trader-heiress",
    title: "綠洲金帳・商旅王女",
    parentCategory: "東方異域 / 絲路西域",
    series: "絲路西域／綠洲金帳",
    themeHint: "西域 綠洲 王女 商旅",
    aliases: ["綠洲王女", "商旅王女", "西域公主", "絲路旅拍"],
    identity: "綠洲金帳商旅王女",
    palette: "祖母綠、流砂金與象牙白",
    costumeCore: "西域長裙、輕紗外層與金線腰封",
    jewelry: "祖母綠額飾、耳墜與腕環",
    prop: "地圖與駝鈴",
    place: "綠洲金帳商隊庭院",
    foreground: "駝鈴、地圖、紗幕與果盤",
    midground: "真人王女坐倚在地毯坐墊前方",
    background: "棕櫚、帳幕、駝隊與綠洲水影",
    action: "人物一手扶地圖，一手搭在坐墊邊緣半坐回望，像正為商隊指路",
    lighting: "高亮日光、綠洲水面反射與金線高光",
  },
  {
    id: "wave4-silkroad-red-cliff-rider",
    title: "赤崖風旌・邊庭女騎",
    parentCategory: "東方異域 / 絲路西域",
    series: "絲路西域／赤崖風旌",
    themeHint: "西域 女騎 邊庭 風旌",
    aliases: ["西域女騎", "邊庭女騎", "絲路女將", "風旌旅拍"],
    identity: "赤崖風旌邊庭女騎",
    palette: "赤棕、砂金與岩灰色",
    costumeCore: "胡風袍裙、短披風與皮革腰帶",
    jewelry: "銅飾耳墜、髮繩與護腕",
    prop: "馬韁與風旗",
    place: "赤崖關道觀景臺",
    foreground: "風旗、馬韁、沙塵與岩石",
    midground: "真人女騎扶鞍停在木欄邊",
    background: "赤崖、關道、駝隊與遠山天光",
    action: "人物一手扶鞍，一手抓住風旗邊緣回身，像剛從關道上勒馬停住",
    lighting: "日落亮光、沙塵 haze 與金屬護腕高光",
  },
  {
    id: "wave4-silkroad-jade-temple-oracle",
    title: "玉殿流火・沙城神諭",
    parentCategory: "東方異域 / 絲路西域",
    series: "絲路西域／玉殿流火",
    themeHint: "西域 神諭 玉殿 沙城",
    aliases: ["沙城神諭", "玉殿神諭", "異域祭司", "西域神殿"],
    identity: "玉殿流火沙城神諭",
    palette: "玉綠、流火橙與金色",
    costumeCore: "神諭長裙、紗質頭披與寶石腰鏈",
    jewelry: "玉石額鏈、耳墜與指環",
    prop: "神諭盤與火燈",
    place: "玉殿流火祭臺",
    foreground: "神諭盤、火燈、紗幕與碎石",
    midground: "真人神諭立於祭臺邊緣回望",
    background: "祭臺、石殿、火盆與沙城夜色",
    action: "人物一手托神諭盤，一手收住頭披邊緣轉身，像剛宣讀完神意",
    lighting: "火燈主光、玉石反射與砂金邊緣光",
  },
  {
    id: "wave4-silkroad-crescent-arch-singer",
    title: "月拱香雨・弦影歌姝",
    parentCategory: "東方異域 / 絲路西域",
    series: "絲路西域／月拱香雨",
    themeHint: "西域 歌姝 月拱 香雨",
    aliases: ["弦影歌姝", "西域歌姝", "月拱夜宴", "異域歌伎"],
    identity: "月拱香雨弦影歌姝",
    palette: "月銀、藍綠與玫瑰紅",
    costumeCore: "西域歌姝長裙、細紗披肩與垂鏈腰飾",
    jewelry: "月銀頭鏈、耳飾與足鏈",
    prop: "短琴與香瓶",
    place: "月拱香雨長廊",
    foreground: "香瓶、短琴、紗幕與燈影",
    midground: "真人歌姝坐倚在月拱欄邊",
    background: "拱廊、月光、彩燈與地毯深景",
    action: "人物一手扶短琴，一手撥開紗幕側倚回眸，像剛唱完一段月下短歌",
    lighting: "月光與香燈交織、月銀反射與藍綠高光",
  },
  {
    id: "wave4-silkroad-golden-mirage-princess",
    title: "金蜃霞庭・流影帝姬",
    parentCategory: "東方異域 / 絲路西域",
    series: "絲路西域／金蜃霞庭",
    themeHint: "西域 帝姬 金蜃 霞庭",
    aliases: ["流影帝姬", "西域帝姬", "金蜃霞庭", "沙海公主"],
    identity: "金蜃霞庭流影帝姬",
    palette: "霞橘、香檳金與孔雀綠",
    costumeCore: "帝姬長裙、蜃影外紗與細金腰鏈",
    jewelry: "寶石頭冠、流蘇耳飾與肩鏈",
    prop: "鏡盒與香帕",
    place: "金蜃霞庭高臺",
    foreground: "鏡盒、紗幕、燈杯與花紋地毯",
    midground: "真人帝姬靠在高臺矮榻邊回望",
    background: "高臺、拱門、落日沙丘與金燈",
    action: "人物一手托鏡盒，一手扶榻邊半坐回首，像在霞光裡等一場夜宴開席",
    lighting: "落日亮場、金燈補光與霞橘絲紗高光",
  },
  {
    id: "wave4-silkroad-night-bazaar-lady",
    title: "沙市星燈・夜集名伶",
    parentCategory: "東方異域 / 絲路西域",
    series: "絲路西域／沙市夜集",
    themeHint: "西域 夜集 名伶 星燈",
    aliases: ["夜集名伶", "沙市旅拍", "西域夜宴", "異域旅人"],
    identity: "沙市星燈夜集名伶",
    palette: "玫紅、靛藍與古金色",
    costumeCore: "西域長裙、薄紗罩肩與金鏈腰飾",
    jewelry: "幣飾頭鏈、耳墜與手鐲",
    prop: "絲巾與香料盒",
    place: "沙市夜集燈街",
    foreground: "香料盒、絲巾、燈籠與市集器皿",
    midground: "真人名伶走在燈街邊回身停步",
    background: "市集、拱門、火把與遠處駝隊剪影",
    action: "人物一手提香料盒，一手按住絲巾回眸，像剛穿過沙市夜集的燈海",
    lighting: "高亮市集火光、器皿反射與玫紅靛藍對比光",
  },
  {
    id: "wave4-garden-orchid-mist-spirit",
    title: "蘭霧花亭・幽香精靈",
    parentCategory: "花園童話 / 自然精靈",
    series: "花園童話／蘭霧花亭",
    themeHint: "花園 精靈 蘭花 晨霧",
    aliases: ["蘭花精靈", "花園精靈", "蘭霧花亭", "自然精靈"],
    identity: "蘭霧花亭幽香精靈",
    palette: "蘭紫、露珠銀與嫩綠色",
    costumeCore: "花靈紗裙、蘭瓣披肩與細藤腰飾",
    jewelry: "蘭花冠、露珠耳飾與細鏈手環",
    prop: "蘭花枝與香露瓶",
    place: "蘭霧花亭晨徑",
    foreground: "蘭花、露珠、香露瓶與藤蔓",
    midground: "真人精靈靠在花亭欄邊回眸",
    background: "花亭、林光、霧氣與深層花徑",
    action: "人物一手托香露瓶，一手扶欄側倚回望，像剛在晨霧裡採集花香",
    lighting: "高亮晨光、露珠 sparkle 與蘭紫反射",
  },
  {
    id: "wave4-garden-camellia-fountain-queen",
    title: "茶花泉庭・晨露女王",
    parentCategory: "花園童話 / 自然精靈",
    series: "花園童話／茶花泉庭",
    themeHint: "花園 女王 茶花 噴泉",
    aliases: ["茶花女王", "噴泉花園", "晨露女王", "花園女王"],
    identity: "茶花泉庭晨露女王",
    palette: "茶花紅、象牙白與香檳金",
    costumeCore: "花園禮裙、花瓣披肩與垂墜紗層",
    jewelry: "茶花冠、珍珠耳墜與金葉項鍊",
    prop: "花籃與水晶杯",
    place: "茶花噴泉庭園",
    foreground: "茶花、泉水、水晶杯與石欄",
    midground: "真人女王倚在石欄邊半坐停步",
    background: "噴泉、花園拱門、花海與晨光",
    action: "人物一手提花籃，一手扶欄半坐回眸，像剛從泉庭晨宴起身",
    lighting: "高亮晨光、泉水反射與香檳金高光",
  },
  {
    id: "wave4-garden-magnolia-cloud-priestess",
    title: "木蘭雲徑・柔光祭司",
    parentCategory: "花園童話 / 自然精靈",
    series: "花園童話／木蘭雲徑",
    themeHint: "花園 祭司 木蘭 雲徑",
    aliases: ["木蘭祭司", "柔光祭司", "花園祭司", "白花精靈"],
    identity: "木蘭雲徑柔光祭司",
    palette: "木蘭白、淺金與霧藍色",
    costumeCore: "祭司長裙、木蘭披紗與細藤腰帶",
    jewelry: "木蘭花冠、銀葉耳飾與腕鏈",
    prop: "木蘭枝與銀燈",
    place: "木蘭雲徑花園",
    foreground: "木蘭、雲霧、銀燈與枝葉",
    midground: "真人祭司沿花徑回身停步",
    background: "花門、樹影、雲霧與遠處溫室",
    action: "人物一手提銀燈，一手拂過木蘭枝回眸，像剛穿過雲霧花徑",
    lighting: "亮場雲光、花瓣反射與銀燈冷暖混光",
  },
  {
    id: "wave4-garden-cherry-moon-keeper",
    title: "櫻月玻庭・夜露守護者",
    parentCategory: "花園童話 / 自然精靈",
    series: "花園童話／櫻月玻庭",
    themeHint: "花園 守護者 櫻花 月夜",
    aliases: ["櫻花守護者", "夜露守護者", "玻璃花庭", "花園童話"],
    identity: "櫻月玻庭夜露守護者",
    palette: "櫻粉、月銀與玻璃藍",
    costumeCore: "花園紗裙、透明披肩與花瓣腰飾",
    jewelry: "櫻枝髮冠、銀耳墜與晶珠手環",
    prop: "玻璃提燈與花剪",
    place: "櫻月玻庭夜徑",
    foreground: "提燈、櫻瓣、玻璃反光與藤蔓",
    midground: "真人守護者坐靠在玻璃欄邊回首",
    background: "花庭、月光、櫻樹與遠處溫室燈影",
    action: "人物一手提燈，一手扶欄坐靠回眸，像正為夜開的花朵守夜",
    lighting: "月光主照、提燈補光與玻璃折射高光",
  },
  {
    id: "wave4-garden-honey-grove-lady",
    title: "蜜林晨歌・琥珀花姝",
    parentCategory: "花園童話 / 自然精靈",
    series: "花園童話／蜜林晨歌",
    themeHint: "花園 花姝 蜜林 晨光",
    aliases: ["蜜林花姝", "琥珀花姝", "蜂蜜花園", "夏日花靈"],
    identity: "蜜林晨歌琥珀花姝",
    palette: "蜂蜜金、奶油白與嫩葉綠",
    costumeCore: "夏日花裙、薄紗披肩與花穗腰帶",
    jewelry: "琥珀耳飾、花冠與細鏈腳飾",
    prop: "蜂巢籃與野花束",
    place: "蜜林花園木橋",
    foreground: "野花、蜂巢籃、木欄與晨光粒子",
    midground: "真人花姝靠在木橋邊緣回眸",
    background: "花田、樹林、蜂箱與遠處小屋",
    action: "人物一手提蜂巢籃，一手扶木欄轉肩回望，像剛走過晨光木橋",
    lighting: "高亮晨光、琥珀反射與花田暖高光",
  },
  {
    id: "wave4-garden-iris-rain-court-lady",
    title: "鳶尾雨庭・霧藍花靈",
    parentCategory: "花園童話 / 自然精靈",
    series: "花園童話／鳶尾雨庭",
    themeHint: "花園 花靈 鳶尾 雨庭",
    aliases: ["鳶尾花靈", "霧藍花靈", "雨庭精靈", "藍花花園"],
    identity: "鳶尾雨庭霧藍花靈",
    palette: "霧藍、紫灰與露珠銀",
    costumeCore: "鳶尾長裙、雨紗披肩與細緻腰鏈",
    jewelry: "鳶尾冠、露珠耳飾與銀鏈手環",
    prop: "小傘與玻璃瓶",
    place: "鳶尾雨庭石徑",
    foreground: "小傘、雨珠、花瓣與石欄",
    midground: "真人花靈沿石徑轉身停步",
    background: "雨庭、玻璃窗、花叢與遠處噴泉",
    action: "人物一手收住小傘，一手拎著玻璃瓶回身停步，像剛在細雨中採集花露",
    lighting: "亮場雨後柔光、露珠高光與霧藍反射",
  },
  {
    id: "wave4-garden-poppy-sunset-muse",
    title: "罌粟晚曦・流焰繆思",
    parentCategory: "花園童話 / 自然精靈",
    series: "花園童話／罌粟晚曦",
    themeHint: "花園 繆思 罌粟 晚曦",
    aliases: ["罌粟繆思", "流焰繆思", "晚曦花園", "夏日晚霞"],
    identity: "罌粟晚曦流焰繆思",
    palette: "罌粟紅、日落橙與奶白色",
    costumeCore: "晚曦長裙、流焰披紗與花瓣腰飾",
    jewelry: "日焰耳飾、花冠與手鍊",
    prop: "花扇與花束",
    place: "罌粟花田晚徑",
    foreground: "花扇、罌粟、金草與夕光",
    midground: "真人繆思坐在花田木椅側邊回首",
    background: "花海、晚霞、木欄與遠丘",
    action: "人物一手握花扇，一手扶椅背半坐回眸，像剛在晚曦裡轉身入鏡",
    lighting: "高亮夕光、花海暖反射與紅橙邊光",
  },
  {
    id: "wave4-garden-mint-glasshouse-sprite",
    title: "薄荷穹室・晶露花精",
    parentCategory: "花園童話 / 自然精靈",
    series: "花園童話／薄荷穹室",
    themeHint: "花園 花精 玻璃穹室 薄荷",
    aliases: ["薄荷花精", "晶露花精", "玻璃花房", "溫室精靈"],
    identity: "薄荷穹室晶露花精",
    palette: "薄荷綠、透明銀與粉白色",
    costumeCore: "玻璃花房紗裙、透明披帛與晶露腰飾",
    jewelry: "晶露髮冠、銀耳飾與水滴手鏈",
    prop: "玻璃壺與薄荷枝",
    place: "薄荷穹室花房",
    foreground: "玻璃壺、薄荷葉、水滴與藤架",
    midground: "真人花精坐倚在花架邊緣回眸",
    background: "穹室、植物牆、陽光與透明窗列",
    action: "人物一手托玻璃壺，一手扶花架坐倚回望，像剛在溫室裡澆灌晨露",
    lighting: "高亮玻璃天光、葉面反射與晶露 sparkle highlights",
  },
  {
    id: "wave4-garden-violet-hill-shepherdess",
    title: "紫丘晨風・花原牧姬",
    parentCategory: "花園童話 / 自然精靈",
    series: "花園童話／紫丘晨風",
    themeHint: "花園 牧姬 紫丘 晨風",
    aliases: ["花原牧姬", "紫丘晨風", "田野花靈", "薰風草原"],
    identity: "紫丘晨風花原牧姬",
    palette: "薰衣草紫、奶油白與草地綠",
    costumeCore: "牧歌長裙、輕柔披肩與花穗腰帶",
    jewelry: "野花頭環、木珠耳飾與細鏈項鍊",
    prop: "草帽與花束",
    place: "紫丘草原花坡",
    foreground: "草帽、野花、草穗與晨霧",
    midground: "真人牧姬坐在花坡石上回首",
    background: "花坡、草原、遠樹與晨光",
    action: "人物一手扶草帽，一手抱花束半坐回望，像剛在花坡上停下腳步",
    lighting: "晨風亮光、草坡反射與薰紫柔高光",
  },
  {
    id: "wave4-garden-silver-thorn-rose-lady",
    title: "銀刺玫庭・夜霜花后",
    parentCategory: "花園童話 / 自然精靈",
    series: "花園童話／銀刺玫庭",
    themeHint: "花園 花后 銀刺 玫瑰 月夜",
    aliases: ["玫瑰花后", "夜霜花后", "月夜花園", "銀刺玫庭"],
    identity: "銀刺玫庭夜霜花后",
    palette: "玫瑰紅、月銀與墨綠色",
    costumeCore: "玫瑰禮裙、銀刺披肩與垂墜紗層",
    jewelry: "銀刺花冠、耳鏈與玫瑰胸針",
    prop: "玫瑰權杖與枝剪",
    place: "銀刺玫庭月夜拱門",
    foreground: "玫瑰、權杖、月霧與石欄",
    midground: "真人花后倚在拱門邊回身停步",
    background: "玫瑰園、月光、花架與遠燈",
    action: "人物一手扶權杖，一手拂過玫瑰枝回眸，像剛巡過月夜花園",
    lighting: "月光主照、玫瑰紅反射與月銀邊緣高光",
  },
];
