export const EIGHTH_WAVE_PROFILE_DEFS = [
  {
    id: "eighth-kyoto-torii-rain-kimono",
    title: "京都鳥居雨巷・朱傘和服旅人",
    parentCategory: "東方和風旅拍",
    series: "東方和風旅拍／京都鳥居／雨巷朱傘",
    themeHint: "京都 鳥居 雨巷 朱傘 和服",
    aliases: ["京都", "鳥居", "和服", "朱傘", "雨巷"],
    identity: "京都雨巷朱傘和服旅人",
    palette: "朱紅、墨黑與雨霧灰",
    costumeCore: "朱紅和服、黑色腰封、透明雨披與木屐",
    jewelry: "紅玉髮簪、細金耳飾與和風繩結",
    prop: "朱色和傘與小型提包",
    place: "京都伏見鳥居雨後石階",
    foreground: "雨滴、朱傘傘骨、石階水光與鳥居柱影",
    midground: "真人旅人扶傘停在石階轉角",
    background: "連續鳥居、濕亮石階、竹林暗影與暖色燈籠",
    action: "人物一手持傘柄低於臉部，另一手扶鳥居木柱微側回望",
    lighting: "雨後柔光、燈籠暖反射、濕地水光與朱紅傘面高光",
  },
  {
    id: "eighth-kanazawa-snow-teahouse-maiko",
    title: "金澤雪茶屋・白梅舞姬",
    parentCategory: "東方和風旅拍",
    series: "東方和風旅拍／金澤雪茶屋／白梅舞姬",
    themeHint: "金澤 雪景 茶屋 白梅 舞姬",
    aliases: ["金澤", "雪景", "茶屋", "白梅", "舞姬"],
    identity: "金澤雪茶屋白梅舞姬",
    palette: "白梅色、淡金與雪灰藍",
    costumeCore: "白梅刺繡和服、淡金腰帶與雪色披肩",
    jewelry: "白梅髮簪、珍珠耳飾與細金腰飾",
    prop: "暖茶盞與紙門邊小燈",
    place: "金澤雪夜茶屋紙門前",
    foreground: "落雪、茶盞熱氣、紙門木格與白梅枝",
    midground: "真人舞姬坐在茶屋廊邊",
    background: "雪覆屋簷、石燈籠、庭院松影與暖窗光",
    action: "人物側坐廊邊，一手端茶盞低於下巴，另一手整理披肩回望鏡頭",
    lighting: "雪地冷反射、紙門暖光、茶氣柔霧與珍珠高光",
  },
  {
    id: "eighth-okinawa-sea-breeze-yukata",
    title: "沖繩海風浴衣・藍浪旅人",
    parentCategory: "東方和風旅拍",
    series: "東方和風旅拍／沖繩海風／藍浪浴衣",
    themeHint: "沖繩 海風 浴衣 藍浪 旅人",
    aliases: ["沖繩", "浴衣", "海風", "藍浪"],
    identity: "沖繩海風藍浪浴衣旅人",
    palette: "海藍、象牙白與珊瑚粉",
    costumeCore: "海藍浴衣、象牙腰帶與薄紗防曬外披",
    jewelry: "珊瑚耳飾、貝殼髮簪與細銀手鏈",
    prop: "貝殼小包與海邊木欄",
    place: "沖繩海岸木棧道黃昏",
    foreground: "海風掀起的薄紗、貝殼小包與木欄影",
    midground: "真人旅人靠近木棧道欄杆轉身",
    background: "藍色海面、珊瑚礁、夕陽雲層與遠方島影",
    action: "人物一手扶木欄回身，一手按住被海風吹起的浴衣袖口",
    lighting: "黃昏海面反光、珊瑚粉雲光與柔和臉部補光",
  },
  {
    id: "eighth-shanghai-jazz-qipao-singer",
    title: "上海爵士夜・墨綠旗袍歌姬",
    parentCategory: "東方旗袍夜宴",
    series: "東方旗袍夜宴／上海爵士夜／墨綠歌姬",
    themeHint: "上海 爵士 旗袍 歌姬 夜宴",
    aliases: ["上海", "爵士", "旗袍", "歌姬", "夜宴"],
    identity: "上海爵士夜墨綠旗袍歌姬",
    palette: "墨綠、香檳金與深酒紅",
    costumeCore: "墨綠絲絨旗袍、香檳金披肩與復古腰線",
    jewelry: "珍珠耳墜、金色髮梳與細手鏈",
    prop: "復古麥克風與小型手包",
    place: "老上海爵士俱樂部舞台前",
    foreground: "麥克風、煙霧、香檳杯與舞台燈邊緣",
    midground: "真人歌姬靠近麥克風台微側回眸",
    background: "爵士樂隊剪影、紅絲絨幕布、吧台燈與金色壁燈",
    action: "人物一手扶復古麥克風架，另一手牽住披肩邊緣，像剛唱完一段回望鏡頭",
    lighting: "舞台香檳金主光、酒紅邊緣光、煙霧散射與珍珠反光",
  },
  {
    id: "eighth-hongkong-neon-qipao-editor",
    title: "香港霓虹雨街・黑金旗袍主編",
    parentCategory: "東方旗袍夜宴",
    series: "東方旗袍夜宴／香港霓虹雨街／黑金主編",
    themeHint: "香港 霓虹 雨街 旗袍 主編",
    aliases: ["香港", "霓虹", "雨街", "旗袍", "主編"],
    identity: "香港霓虹雨街黑金旗袍主編",
    palette: "黑金、霓虹紅與雨夜藍",
    costumeCore: "黑金緞面旗袍、長版風衣與細皮革腰帶",
    jewelry: "金色耳扣、腕錶與黑曜石戒指",
    prop: "皮革文件夾與透明傘",
    place: "香港霓虹雨街騎樓下",
    foreground: "透明傘邊緣、文件夾、雨滴與濕地霓虹倒影",
    midground: "真人主編站在騎樓欄柱旁",
    background: "繁體霓虹招牌、電車燈、雨夜街口與高樓玻璃",
    action: "人物一手扶透明傘柄，另一手抱文件夾靠近騎樓柱回身",
    lighting: "霓虹紅藍反射、雨地高光、騎樓暖燈與柔和臉部補光",
  },
  {
    id: "eighth-taipei-artdeco-qipao-hostess",
    title: "台北藝廊夜宴・白玉旗袍策展人",
    parentCategory: "東方旗袍夜宴",
    series: "東方旗袍夜宴／台北藝廊夜宴／白玉策展人",
    themeHint: "台北 藝廊 夜宴 白玉旗袍 策展人",
    aliases: ["台北", "藝廊", "旗袍", "策展人", "夜宴"],
    identity: "台北藝廊夜宴白玉旗袍策展人",
    palette: "白玉、墨黑與玫瑰金",
    costumeCore: "白玉緞面旗袍、墨黑短披肩與玫瑰金腰扣",
    jewelry: "玫瑰金耳飾、玉石胸針與細手鏈",
    prop: "展覽手冊與香檳杯",
    place: "台北 Art Deco 藝廊夜宴",
    foreground: "香檳杯、展覽手冊、金屬欄杆與雕塑邊緣",
    midground: "真人策展人坐在藝廊長椅前緣",
    background: "Art Deco 牆面、油畫、玻璃燈與夜色窗景",
    action: "人物端坐長椅前緣，一手扶展覽手冊，另一手持香檳杯低於肩線",
    lighting: "藝廊暖白聚光、玻璃燈反射、玫瑰金珠寶高光與清晰臉部補光",
  },
  {
    id: "eighth-mecha-hangar-commander",
    title: "銀灰機庫・女指揮官",
    parentCategory: "賽博機甲 / 科幻戰姬",
    series: "賽博機甲／銀灰機庫／女指揮官",
    themeHint: "機甲 機庫 指揮官 銀灰 科幻",
    aliases: ["機甲", "機庫", "指揮官", "科幻"],
    identity: "銀灰機庫女指揮官",
    palette: "銀灰、冷白與警示橙",
    costumeCore: "銀灰指揮官長外套、黑色戰術內層與金屬腰封",
    jewelry: "通訊耳機、軍階胸針與銀色腕錶",
    prop: "全息平板與機甲維修欄杆",
    place: "巨大機甲維修機庫",
    foreground: "全息平板、欄杆、警示燈與金屬地面反光",
    midground: "真人指揮官靠在維修平台欄杆旁",
    background: "巨大機甲胸甲、機械臂、冷白燈帶與工程平台",
    action: "人物一手扶維修欄杆，另一手操作全息平板，身體微側回頭下達指令",
    lighting: "冷白機庫主光、警示橙邊緣光、金屬反射與清晰臉部補光",
  },
  {
    id: "eighth-cyber-bike-rain-runner",
    title: "霓虹機車雨夜・賽博疾行者",
    parentCategory: "賽博機甲 / 科幻戰姬",
    series: "賽博機甲／霓虹機車雨夜／疾行者",
    themeHint: "賽博 機車 雨夜 霓虹 疾行者",
    aliases: ["賽博", "機車", "雨夜", "疾行者"],
    identity: "霓虹機車雨夜賽博疾行者",
    palette: "電藍、黑色與霓虹粉",
    costumeCore: "黑色短版戰術外套、電藍護甲裙褲與雨夜披風",
    jewelry: "發光耳扣、機械手環與細金屬頸圈",
    prop: "賽博機車與透明頭盔",
    place: "雨夜霓虹高架橋下",
    foreground: "機車車燈、水花、透明頭盔與濕地反射",
    midground: "真人疾行者坐靠在機車側邊",
    background: "高架橋、霓虹招牌、雨霧車燈與城市高樓",
    action: "人物一手扶機車把手，另一手提起透明頭盔，剛從車側坐靠起身看向鏡頭",
    lighting: "霓虹電藍粉反射、車燈逆光、雨霧散射與真實皮革高光",
  },
  {
    id: "eighth-orbital-lab-engineer",
    title: "軌道實驗室・白銀工程師",
    parentCategory: "賽博機甲 / 科幻戰姬",
    series: "賽博機甲／軌道實驗室／白銀工程師",
    themeHint: "軌道 實驗室 工程師 白銀 科幻",
    aliases: ["軌道實驗室", "工程師", "白銀", "科幻"],
    identity: "軌道實驗室白銀工程師",
    palette: "白銀、透明藍與深空黑",
    costumeCore: "白銀實驗室長外套、透明藍防護層與細金屬腰帶",
    jewelry: "微型通訊耳釘、透明護目鏡髮上固定與銀色識別牌",
    prop: "磁浮工具箱與透明控制台",
    place: "太空軌道實驗室觀景艙",
    foreground: "透明控制台、工具箱、玻璃反射與漂浮數據光點",
    midground: "真人工程師靠近控制台轉身",
    background: "地球弧線、深空星光、機械艙壁與藍色儀表光",
    action: "人物一手扶透明控制台，另一手收起護目鏡，像剛完成艙內校準回望鏡頭",
    lighting: "地球反射藍光、實驗室冷白補光、玻璃高光與自然臉部 catchlight",
  },  {
    id: "eighth-maldives-overwater-dress",
    title: "馬爾地夫水屋・白裙海風旅人",
    parentCategory: "海岸度假旅拍",
    series: "海岸度假旅拍／馬爾地夫水屋／白裙海風",
    themeHint: "馬爾地夫 水屋 白裙 海風 旅拍",
    aliases: ["馬爾地夫", "水屋", "白裙", "海風"],
    identity: "馬爾地夫水屋白裙海風旅人",
    palette: "白色、玻璃海藍與陽光金",
    costumeCore: "白色長裙、透明海風披肩與草編腰帶",
    jewelry: "貝殼耳飾、細金手鏈與珍珠髮夾",
    prop: "水屋木欄杆與草編帽",
    place: "馬爾地夫水上屋木棧道",
    foreground: "草編帽、木欄杆、透明披肩與海面反光",
    midground: "真人旅人扶著水屋欄杆回身",
    background: "玻璃海面、水上屋、白沙淺灘與晴空雲層",
    action: "人物一手扶木欄杆，一手按住被海風吹起的草編帽，裙襬沿木棧道拉出流線",
    lighting: "海面高亮反射、白裙柔光、陽光金邊緣光與清晰臉部補光",
  },
  {
    id: "eighth-santorini-blue-dome-swim",
    title: "聖托里尼藍頂・海崖度假旅人",
    parentCategory: "海岸度假旅拍",
    series: "海岸度假旅拍／聖托里尼藍頂／海崖度假",
    themeHint: "聖托里尼 藍頂 海崖 度假 旅拍",
    aliases: ["聖托里尼", "藍頂", "海崖", "度假"],
    identity: "聖托里尼藍頂海崖度假旅人",
    palette: "愛琴海藍、白色與夕陽粉",
    costumeCore: "白色度假長裙、藍色絲巾與輕薄外披",
    jewelry: "藍寶石耳飾、銀色手鏈與小型髮飾",
    prop: "海崖白牆欄杆與藍色絲巾",
    place: "聖托里尼藍頂教堂海崖步道",
    foreground: "白牆欄杆、藍色絲巾、花盆與海風薄紗",
    midground: "真人旅人靠在白牆欄杆旁",
    background: "藍頂教堂、愛琴海、白色村落與夕陽天空",
    action: "人物側靠白牆欄杆，一手扶欄，一手整理藍色絲巾回望鏡頭",
    lighting: "夕陽粉金側光、白牆反射、海面藍光與自然皮膚紋理",
  },
  {
    id: "eighth-hawaii-volcanic-beach-sarong",
    title: "夏威夷黑沙灘・火山紗籠旅人",
    parentCategory: "海岸度假旅拍",
    series: "海岸度假旅拍／夏威夷黑沙灘／火山紗籠",
    themeHint: "夏威夷 黑沙灘 火山 紗籠 旅拍",
    aliases: ["夏威夷", "黑沙灘", "火山", "紗籠"],
    identity: "夏威夷黑沙灘火山紗籠旅人",
    palette: "黑沙、珊瑚紅與海水青",
    costumeCore: "珊瑚紅度假上衣、長紗籠與輕薄披巾",
    jewelry: "貝殼項鍊、金色手環與花朵髮飾",
    prop: "火山岩、海風披巾與草編包",
    place: "夏威夷黑沙灘火山岩岸",
    foreground: "火山岩、草編包、浪花與黑沙紋理",
    midground: "真人旅人坐靠在低矮火山岩旁",
    background: "海浪、火山山影、椰樹剪影與夕陽雲層",
    action: "人物坐靠低矮火山岩，一手扶岩面保持重心，另一手牽住被風吹起的披巾",
    lighting: "夕陽珊瑚紅逆光、浪花高光、黑沙反射與柔和臉部補光",
  },
  {
    id: "eighth-paris-atelier-bridal",
    title: "巴黎高訂工坊・象牙婚紗設計師",
    parentCategory: "高訂婚紗禮服",
    series: "高訂婚紗禮服／巴黎工坊／象牙設計師",
    themeHint: "巴黎 高訂工坊 象牙婚紗 設計師",
    aliases: ["巴黎", "高訂", "婚紗", "設計師"],
    identity: "巴黎高訂工坊象牙婚紗設計師",
    palette: "象牙白、香檳金與裁縫木色",
    costumeCore: "象牙婚紗半成品、香檳金腰封與透明薄紗披肩",
    jewelry: "珍珠耳飾、細金戒指與髮梳",
    prop: "裁縫尺、設計稿與人台",
    place: "巴黎高訂婚紗工坊",
    foreground: "設計稿、裁縫尺、人台薄紗與工作桌邊緣",
    midground: "真人設計師坐在工作桌旁整理婚紗布料",
    background: "高窗、布料架、半成人台婚紗與暖色工坊燈",
    action: "人物臨案坐在工作桌旁，一手扶設計稿，另一手整理象牙薄紗裙片",
    lighting: "高窗柔光、工坊暖燈、珍珠高光與真實布料紋理",
  },
  {
    id: "eighth-vienna-ball-crystal-gown",
    title: "維也納水晶舞會・銀藍禮裙女主",
    parentCategory: "高訂婚紗禮服",
    series: "高訂婚紗禮服／維也納舞會／銀藍禮裙",
    themeHint: "維也納 水晶舞會 銀藍禮裙",
    aliases: ["維也納", "舞會", "水晶", "禮裙"],
    identity: "維也納水晶舞會銀藍禮裙女主",
    palette: "銀藍、象牙白與水晶透明光",
    costumeCore: "銀藍水晶禮裙、象牙薄紗拖尾與立體刺繡腰封",
    jewelry: "水晶耳墜、銀色髮冠與細手鏈",
    prop: "舞會階梯扶手與小型晚宴包",
    place: "維也納水晶吊燈舞會廳",
    foreground: "階梯扶手、晚宴包、水晶吊燈散景與裙襬珠片",
    midground: "真人女主踏下舞會階梯",
    background: "水晶吊燈、金色拱門、樂隊剪影與華麗舞會廳",
    action: "人物一手扶階梯扶手，一手提起禮裙裙襬，像剛踏下舞會階梯回望鏡頭",
    lighting: "水晶吊燈主光、銀藍珠片高光、金色廳堂反射與清晰臉部補光",
  },
  {
    id: "eighth-rose-garden-bridal-cape",
    title: "玫瑰花園婚紗・披肩新娘女主",
    parentCategory: "高訂婚紗禮服",
    series: "高訂婚紗禮服／玫瑰花園／披肩新娘",
    themeHint: "玫瑰花園 婚紗 披肩 新娘",
    aliases: ["玫瑰花園", "婚紗", "披肩", "新娘"],
    identity: "玫瑰花園披肩新娘女主",
    palette: "玫瑰粉、象牙白與嫩葉綠",
    costumeCore: "象牙婚紗、玫瑰粉披肩與立體花瓣裙襬",
    jewelry: "珍珠項鍊、玫瑰髮飾與細金手鏈",
    prop: "玫瑰花束與花園石椅",
    place: "英式玫瑰花園午後",
    foreground: "玫瑰花束、石椅邊緣、花枝與薄紗柔焦",
    midground: "真人女主坐在花園石椅前緣",
    background: "玫瑰拱門、綠籬、噴泉與午後柔光",
    action: "人物坐在石椅前緣，一手扶玫瑰花束，另一手整理披肩，裙襬沿石椅自然鋪開",
    lighting: "午後柔光、玫瑰粉反射、珍珠高光與自然皮膚紋理",
  },];
