// 基于风格范例图片分析创建的角色卡
// 来源：C:\Users\User\Desktop\ai生圖\風格範例

export const STYLE_ANALYSIS_PROFILES = [
  {
    id: "oriental-fairy-flowing-dress",
    title: "东方仙侠・飘逸白衣仙子",
    parentCategory: "仙俠神話 / 古裝陸劇",
    series: "东方仙侠／飘逸系列",
    themeHint: "东方仙侠 白衣仙子 飘逸长裙 古风仙境 云雾缭绕",
    aliases: ["白衣仙子", "飘逸仙姬", "云裳仙子", "东方仙侠"],
    identity: "东方飘逸白衣仙子",
    palette: "纯白、淡青、云雾灰、月光银",
    costumeCore: "纯白飘逸长裙、多层薄纱、轻盈袖摆、高腰束带、云纹刺绣",
    jewelry: "简约银饰、白玉发簪、珍珠耳坠",
    prop: "飘带、薄纱、云雾",
    place: "山巅云海、仙境台阶、雾气缭绕的古建筑",
    foreground: "飘动的白色薄纱、云雾前景",
    midground: "真人仙子站立姿态，裙摆随风飘扬，面向镜头",
    background: "朦胧山峦、云海、古典建筑剪影",
    action: "自然站姿，双手自然垂放或轻提裙摆，头发与裙摆随风飘动",
    sceneAction: "自然站姿，双手自然垂放或轻提裙摆，头发与裙摆随风飘动",
    sceneLighting: "柔和顶光、云雾散射光、边缘轮廓光",
    lighting: "柔和顶光、云雾散射光、边缘轮廓光",
    atmosphere: "空灵飘逸的东方仙侠电影感，强调服装动态与轻盈质感",
  },

  {
    id: "modern-urban-fashion-portrait",
    title: "都市时尚・现代性感名媛",
    parentCategory: "現代都市 / 街拍電影",
    series: "都市电影／时尚街拍",
    themeHint: "现代都市 时尚名媛 黑色礼服 都市背景 高级感",
    aliases: ["都市名媛", "时尚女郎", "黑色礼服", "现代风格"],
    identity: "都市时尚性感名媛",
    palette: "经典黑、珍珠白、都市灰、暖金光",
    costumeCore: "黑色修身礼服、深V领设计、完整内衬、高级剪裁、简约现代线条",
    jewelry: "简约金色项链、精致耳饰",
    prop: "现代建筑背景、都市光影",
    place: "现代都市街景、建筑外墙、玻璃幕墙",
    foreground: "人物主体清晰，礼服质感突出",
    midground: "真人名媛自信站姿，直视镜头，姿态优雅",
    background: "都市建筑、柔焦光斑、现代感背景",
    action: "自信站姿，肩部微扬，眼神直视，手部自然摆放",
    sceneAction: "自信站姿，肩部微扬，眼神直视，手部自然摆放",
    sceneLighting: "自然光、柔和面部补光、边缘轮廓光",
    lighting: "自然光、柔和面部补光、边缘轮廓光",
    atmosphere: "高级都市时尚大片感，强调现代女性自信与优雅",
  },

  {
    id: "fantasy-purple-magic-queen",
    title: "奇幻魔法・紫金魔法女王",
    parentCategory: "奇幻異世界 / 暗黑王族",
    series: "奇幻魔法／女王系列",
    themeHint: "奇幻魔法 紫金配色 华丽头饰 魔法女王 史诗感",
    aliases: ["魔法女王", "紫金女王", "奇幻女王", "华丽头饰"],
    identity: "紫金奇幻魔法女王",
    palette: "深紫、古金、宝石蓝、神秘黑",
    costumeCore: "紫金高订礼服、华丽头饰、金属装饰、宝石镶嵌、多层次结构",
    jewelry: "巨型金色头饰、紫晶宝石、金属颈饰、华丽耳坠",
    prop: "权杖、魔法光效、宝石",
    place: "奇幻神殿、魔法王座、神秘宫殿",
    foreground: "华丽头饰细节、宝石反光",
    midground: "真人女王端庄坐姿或站姿，气场强大，正视镜头",
    background: "魔法光效、神秘背景、宫殿建筑",
    action: "威严坐姿或站姿，头部微扬，展现女王气场",
    sceneAction: "威严坐姿或站姿，头部微扬，展现女王气场",
    sceneLighting: "魔法光效、暖金色主光、紫色环境光、宝石反光",
    lighting: "魔法光效、暖金色主光、紫色环境光、宝石反光",
    atmosphere: "史诗级奇幻魔法电影感，强调华丽与权威",
  },

  {
    id: "gothic-dark-mystique-lady",
    title: "哥特暗黑・神秘暗夜女爵",
    parentCategory: "奇幻異世界 / 暗黑王族",
    series: "哥特暗黑／夜宴系列",
    themeHint: "哥特暗黑 黑色礼服 神秘氛围 暗夜美学 高级感",
    aliases: ["暗夜女爵", "哥特女王", "黑色神秘", "暗黑美学"],
    identity: "哥特暗黑神秘女爵",
    palette: "深黑、暗红、冷银、幽蓝",
    costumeCore: "黑色高订哥特礼服、蕾丝细节、金属装饰、修身剪裁、完整内衬",
    jewelry: "银色项链、暗色宝石、金属饰品",
    prop: "黑色元素、神秘道具",
    place: "哥特建筑、暗黑宫殿、神秘场景",
    foreground: "黑色礼服质感、蕾丝细节",
    midground: "真人女爵优雅姿态，神秘眼神，气质冷艳",
    background: "暗色调背景、神秘光影、建筑轮廓",
    action: "优雅站姿或坐姿，姿态高贵冷艳，眼神深邃",
    sceneAction: "优雅站姿或坐姿，姿态高贵冷艳，眼神深邃",
    sceneLighting: "低调暗光、侧逆光、冷色调环境光",
    lighting: "低调暗光、侧逆光、冷色调环境光",
    atmosphere: "高级哥特暗黑电影美学，神秘而优雅",
  },

  {
    id: "chinese-classical-red-hanfu",
    title: "中国古典・红衣汉服佳人",
    parentCategory: "中國歷代服裝／泛朝代總覽",
    series: "汉服古风／红衣系列",
    themeHint: "中国古典 红色汉服 古风美学 传统服饰 庭院背景",
    aliases: ["红衣汉服", "古风佳人", "中式古装", "汉服仕女"],
    identity: "中国古典红衣汉服佳人",
    palette: "中国红、古金、象牙白、木色",
    costumeCore: "红色传统汉服、多层次结构、刺绣工艺、宽袖设计、传统剪裁",
    jewelry: "传统发饰、玉石配饰、金色头饰",
    prop: "扇子、伞、古典道具",
    place: "中式庭院、古典建筑、园林景观",
    foreground: "汉服细节、刺绣纹理",
    midground: "真人佳人传统姿态，温婉气质，东方美感",
    background: "古典建筑、庭院景观、朦胧背景",
    action: "传统仕女姿态，手持道具，姿态优雅端庄",
    sceneAction: "传统仕女姿态，手持道具，姿态优雅端庄",
    sceneLighting: "自然光、柔和散射光、暖色调",
    lighting: "自然光、柔和散射光、暖色调",
    atmosphere: "中国传统古典电影美学，温婉典雅",
  },

  {
    id: "fantasy-golden-warrior-queen",
    title: "奇幻战姬・金甲女战神",
    parentCategory: "武俠江湖 / 戰場女將",
    series: "战姬系列／金甲女王",
    themeHint: "奇幻战姬 金色铠甲 女战神 史诗感 华丽战甲",
    aliases: ["金甲女王", "女战神", "战姬", "奇幻战士"],
    identity: "奇幻金甲女战神",
    palette: "古金、青铜、战甲银、深红",
    costumeCore: "金色战甲、华丽铠甲设计、金属质感、战斗礼服结合、完整护甲",
    jewelry: "金色头盔、战甲配饰、金属装饰",
    prop: "武器、盾牌、权杖",
    place: "战场、史诗场景、奇幻王座",
    foreground: "战甲细节、金属反光",
    midground: "真人女战神威武姿态，气场强大，战士风范",
    background: "史诗战场、云雾、宏大场景",
    action: "战士站姿，手持武器，姿态威严有力",
    sceneAction: "战士站姿，手持武器，姿态威严有力",
    sceneLighting: "史诗级戏剧光、金属反光、强烈对比",
    lighting: "史诗级戏剧光、金属反光、强烈对比",
    atmosphere: "史诗级奇幻战争电影感，威严而华丽",
  },

  {
    id: "elegant-eastern-blossom-lady",
    title: "东方雅致・花间仕女",
    parentCategory: "中國歷代服裝／泛朝代總覽",
    series: "东方雅致／花间系列",
    themeHint: "东方雅致 淡雅服饰 花间美人 古风写意 清新脱俗",
    aliases: ["花间仕女", "东方雅致", "清新古风", "淡雅美人"],
    identity: "东方雅致花间仕女",
    palette: "淡粉、湖蓝、象牙白、春绿",
    costumeCore: "淡雅古装、清新色调、简约设计、飘逸质感、传统剪裁",
    jewelry: "简约发饰、珠钗、淡色配饰",
    prop: "花枝、团扇、书卷",
    place: "花园、庭院、自然景观",
    foreground: "花卉前景、柔焦花瓣",
    midground: "真人仕女温婉姿态，气质清雅，与花相伴",
    background: "花园景观、朦胧背景、自然元素",
    action: "温婉站姿或坐姿，手持花枝或团扇，姿态柔美",
    sceneAction: "温婉站姿或坐姿，手持花枝或团扇，姿态柔美",
    sceneLighting: "自然散射光、柔和面光、清新色调",
    lighting: "自然散射光、柔和面光、清新色调",
    atmosphere: "东方写意电影美学，清新淡雅脱俗",
  },
];
