function createBedchamberConsortExpansionProfile([slug, title, seriesName, palette, costumeCore, jewelry, prop, place, foreground, midground, background, action, lighting]) {
  return {
    id: `bedchamber-consort-expanded-${slug}`,
    title,
    parentCategory: "寢宮寵妃系列",
    series: `寢宮寵妃系列／${seriesName}`,
    themeHint: `寢宮寵妃 皇宮寢宮 宮燈 紅木床榻 高訂緞面禮服 ${title} ${seriesName}`,
    aliases: ["寢宮寵妃", "皇宮寢宮", "宮燈", "紅木床榻", "高訂緞面禮服", title],
    identity: title.replace("・", ""),
    palette,
    costumeCore,
    jewelry,
    prop,
    place,
    foreground,
    midground,
    background,
    action,
    lighting,
    atmosphere: "成熟高訂古風寢宮寵妃電影封面，收錄斜躺、倚臥、長腿線條與低領禮服比例，但保持服裝完整、真人可穿戴與非低俗寫真",
  };
}

function createBedchamberSuccubusExpansionProfile([slug, title, seriesName, palette, costumeCore, jewelry, prop, place, foreground, midground, background, action, lighting]) {
  return {
    id: `bedchamber-succubus-expanded-${slug}`,
    title,
    parentCategory: "魅魔",
    series: `寢宮魅魔系列／${seriesName}`,
    themeHint: `魅魔 寢宮 夜宴 高訂暗黑禮服 宮燈 床榻 珠寶 ${title} ${seriesName}`,
    aliases: ["魅魔", "寢宮魅魔", "夜宴魅姬", "高訂暗黑禮服", "宮燈床榻", title],
    identity: title.replace("・", ""),
    palette,
    costumeCore,
    jewelry,
    prop,
    place,
    foreground,
    midground,
    background,
    action,
    lighting,
    atmosphere: "參考寢宮寵妃構圖的高訂暗黑魅魔電影封面，重點是絲緞、薄紗、珠寶、翼形披紗與成熟女王氣場，不做情趣內衣、裸露或遊戲低俗化",
    cupSize: "K",
  };
}

const BEDCHAMBER_CONSORT_EXPANSION_PROFILES = [
  ["golden-lotus-reclining", "金蓮燈榻・斜臥寵妃", "金蓮斜臥", "蓮金、香檳緞、琥珀燈火與紅木棕", "蓮金 satin 低領宮廷長裙、完整安全內襯、鑽石腰封、側開衩裙擺與寬幅金紗披袍", "金蓮花冠、琥珀流蘇步搖、鑽石項鍊與細金臂釧", "蓮紋金盒與玉盞", "金蓮宮燈皇宮寢榻", "金緞裙擺、蓮紋金盒、玉盞與床榻錦墊", "真人寵妃斜臥於床榻，臉部正視鏡頭，長腿線條由裙擺自然延伸", "金色宮燈、紅木屏風、絲綢帷帳與珠寶托盤", "人物一手撐床榻，一手低扶玉盞，姿態舒展但穩定", "warm lotus lantern key、gold satin shine、soft Vogue facial fill"],
  ["ruby-candle-couch", "紅寶燭榻・側坐寵妃", "紅寶側坐", "紅寶石、古金、深紅木與燭火橙", "紅寶 satin 宮廷禮服、低領水晶胸衣外層、完整內襯、修身腰封與高開衩長裙", "紅寶鳳冠、金絲流蘇耳墜、紅寶項鍊與鑽石腰鏈", "紅寶酒杯與金色燭台", "紅寶燭光寢宮軟榻", "酒杯、燭台、紅緞裙擺與錦墊", "真人寵妃側坐軟榻，雙腿斜向前景，臉部微側正面", "燭火、紅木雕花牆、金色帷幕與床柱", "人物一手扶軟榻，一手低持酒杯，手不遮臉", "ruby candle glow、warm skin-safe fill、gold jewelry sparkle"],
  ["ivory-pearl-canopy", "象牙珠帳・倚枕寵妃", "珠帳倚枕", "象牙白、珍珠金、月銀與柔燭色", "象牙 satin 低領宮廷禮服、珍珠鑲邊、完整內襯、柔紗披袖與修長裙擺", "珍珠金冠、月銀流蘇、白鑽耳墜與玉鐲", "珍珠團扇與白玉香盒", "象牙珠帳皇宮寢榻", "團扇、白玉香盒、珍珠簾與象牙裙擺", "真人寵妃倚靠軟枕，肩頸線條清楚，臉部正向鏡頭", "白紗帷帳、金色宮燈、紅木妝台與月窗", "人物一手扶軟枕，一手低持團扇，姿態柔和", "pearl-white silk bounce、warm lantern edge、soft beauty light"],
  ["sapphire-lantern-long-leg", "藍寶宮燈・長腿寵妃", "藍寶長腿", "藍寶石、香檳金、深木棕與琥珀光", "藍寶 satin 高訂宮廷禮服、低領金蕾絲結構、完整安全內襯、長裙開衩與藍金薄紗披帛", "藍寶金冠、青金石耳墜、鑽石頸鍊與金色腰飾", "藍寶酒杯與宮扇", "藍寶宮燈寢宮床榻", "宮扇、藍寶酒杯、裙擺反光與床榻邊緣", "真人寵妃坐於床榻側緣，長腿線條在裙擺間自然可見", "藍金帷幕、金色燈架、紅木屏風與珠簾", "人物一手低持宮扇，一手扶床榻，臉部正視鏡頭", "sapphire silk bounce、amber lantern key、diamond sparkle"],
  ["jade-incense-recline", "玉煙翠榻・低靠寵妃", "玉煙低靠", "翡翠、玉白、暖金與紅木棕", "翡翠 satin 宮廷長裙、玉白內襯、低領金邊胸衣外層、側開衩裙擺與輕薄披袖", "翡翠步搖、玉石耳墜、金絲髮簪與細鑽項鍊", "白玉香爐與翡翠香盒", "玉煙寢宮紅木軟榻", "香煙、白玉香爐、翡翠香盒與綠緞裙擺", "真人寵妃低靠軟榻，臉部微側正面清楚", "玉屏風、宮燈、紅木床柱與絲綢帷帳", "人物一手撐軟枕，一手整理披袖，姿態穩定", "jade silk fill、warm incense glow、soft facial key"],
  ["amethyst-mirror-lounge", "紫晶鏡奩・半倚寵妃", "紫晶妝榻", "紫晶、暗玫瑰、香檳金與燭火金", "紫晶 satin 低領宮廷禮服、完整內襯、香檳金水晶腰封與半透明紫金披袍", "紫晶花冠、紫寶流蘇耳飾、鑽石項鍊與水晶手鏈", "銅鏡、紫晶酒杯與胭脂盒", "紫晶妝台皇宮寢室", "銅鏡、胭脂盒、紫晶酒杯與紫金裙擺", "真人寵妃半倚妝台，禮服輪廓與臉部都清楚", "紅木妝台、紫金帷幕、宮燈與床榻深景", "人物一手扶妝台，一手低持酒杯，正視鏡頭", "amethyst glow、vanity lantern warmth、crystal highlights"],
  ["black-gold-phoenix-bed", "黑金鳳榻・夜宮寵妃", "黑金鳳榻", "墨黑、古金、琥珀、暗紅與燭火橙", "黑金 satin 宮廷禮服、低領金線胸衣、完整內襯、修身長裙開衩與黑金披紗", "黑金鳳冠、黑曜石耳墜、古金項鍊與金絲腰鏈", "黑玉香盒與金色燭台", "黑金鳳紋皇宮寢榻", "燭台、黑玉香盒、黑金裙擺與鳳紋靠枕", "真人寵妃倚靠鳳榻，長腿線條由裙擺引導但不局部特寫", "深色帷幕、金色宮燈、紅木床柱與燭火", "人物一手撐靠枕，一手低扶裙側，臉部轉向鏡頭", "candle key、black satin rim light、warm amber fill"],
  ["rose-gold-silk-pillow", "玫瑰金枕・凝眸寵妃", "玫瑰金凝眸", "玫瑰金、蜜桃粉、珍珠白與暖金", "玫瑰金 satin 低領宮廷長裙、完整安全內襯、粉晶腰飾、柔紗披袖與修長裙擺", "玫瑰金花冠、粉晶耳墜、珍珠項鍊與細金手鐲", "粉晶香瓶與玫瑰金團扇", "玫瑰金寢宮軟枕床榻", "團扇、香瓶、軟枕與玫瑰金裙擺", "真人寵妃倚枕凝眸，肩頸線條優雅，臉部明亮", "粉金帷幕、紅木床榻、宮燈與珠寶台", "人物一手扶軟枕，一手低持團扇，姿態舒展", "rose-gold silk highlight、warm palace fill、soft editorial light"],
  ["snow-gold-side-lie", "雪金紗榻・側臥寵妃", "雪金側臥", "雪白、淡金、月銀、紅木棕與暖燭", "雪金 satin 宮廷長裙、淡金蕾絲低領結構、完整內襯、銀白披紗與側開衩裙擺", "淡金月冠、珍珠流蘇、白鑽耳墜與玉鐲", "月白團扇與白玉香盒", "雪金紗帳月窗寢榻", "月白團扇、白玉香盒、雪金裙擺與紗帳垂墜", "真人寵妃側臥床榻，臉部朝向鏡頭，身形舒展", "月窗、白紗帷幕、紅木家具與柔焦宮燈", "人物一手低持團扇，一手撐床榻，腿部比例自然", "cool moon fill、warm lantern key、snow-gold satin sheen"],
  ["copper-brocade-low-couch", "銅金錦榻・低坐寵妃", "銅金低坐", "銅金、栗棕、香檳金與暖燭色", "銅金 satin 宮廷禮服、低領珠繡外層、完整內襯、錦緞腰封與厚重披袍", "銅金花冠、黃水晶耳飾、金色項鍊與臂釧", "銅鏡、金盒與小酒盞", "銅金錦繡皇宮寢榻", "銅鏡、小酒盞、金盒與錦墊紋理", "真人寵妃低坐床榻邊，雙腿斜收，臉部正面", "紅木家具、金色帷幕、宮燈與深景珠寶架", "人物一手扶榻邊，一手低持酒盞，姿勢端正", "copper lantern glow、brocade texture highlights、soft facial fill"],
  ["champagne-bead-curtain", "香檳珠簾・撩簾寵妃", "香檳撩簾", "香檳金、珍珠白、紅木棕與琥珀光", "香檳 satin 低領宮廷長裙、完整安全內襯、珍珠水晶腰封、長裙開衩與柔金披袖", "珍珠金冠、長流蘇步搖、鑽石耳墜與珍珠項鍊", "珠簾、金色香盒與手持小扇", "香檳珠簾寢宮入口", "珠簾、小扇、香盒與金緞裙擺", "真人寵妃坐於床榻側並撩開珠簾，臉部正視鏡頭", "宮燈、紅木屏風、絲帳與床榻深景", "人物一手撩珠簾，一手低持小扇，腿部線條自然延伸", "champagne lantern key、pearl sparkle、warm editorial fill"],
  ["peony-gold-bedside", "牡丹金榻・花冠寵妃", "牡丹金榻", "牡丹粉、香檳金、暖紅木與燭火金", "牡丹金 satin 宮廷禮服、低領花瓣珠繡結構、完整內襯、花紋克制的長裙與披袍", "牡丹金冠、粉晶耳墜、細鑽項鍊與花形腰飾", "牡丹花枝與金色香瓶", "牡丹金燈皇宮寢榻", "牡丹花枝、香瓶、裙擺與錦墊", "真人寵妃倚坐床榻，身形修長，臉部看向鏡頭", "牡丹屏風、宮燈、紅木床榻與珠寶擺件", "人物一手低持牡丹，一手扶軟枕，姿態華麗", "peony-gold bounce、warm lamp key、soft skin texture light"],
  ["lapis-gold-moon-bed", "青金月榻・側倚寵妃", "青金月榻", "青金石藍、古金、月銀與紅木棕", "青金 satin 宮廷長裙、低領金線胸衣外層、完整內襯、修長開衩裙擺與月銀披紗", "青金石金冠、藍寶耳墜、月銀項鍊與金絲腰飾", "青金酒杯與月形香爐", "青金月窗寢宮床榻", "酒杯、月形香爐、青金裙擺與床榻邊緣", "真人寵妃側倚床榻，臉部微側正面，長腿線條由裙擺帶出", "月窗、藍金帷幕、宮燈與紅木屏風", "人物一手撐床榻，一手低持酒杯，手不遮臉", "moon cool fill、gold lantern key、lapis satin sheen"],
  ["honey-gold-incense-bed", "蜜金香榻・暖燈寵妃", "蜜金香榻", "蜜金、暖棕、香檳白與燭火橙", "蜜金 satin 低領宮廷禮服、完整內襯、鑽石細腰封、柔軟長披袍與側開衩裙擺", "蜜金花冠、黃水晶耳墜、鑽石鎖骨鏈與金鐲", "鎏金香爐與蜜色酒盞", "蜜金香霧皇宮寢榻", "香爐、酒盞、暖色煙氣與蜜金裙擺", "真人寵妃倚靠床榻軟枕，臉部正視鏡頭", "金色宮燈、紅木家具、絲綢帷帳與香霧", "人物一手扶軟枕，一手低持酒盞，腿部線條自然呈現", "honey lantern key、incense haze、satin sparkle highlights"],
  ["silver-gold-royal-couch", "銀金御榻・清冷寵妃", "銀金御榻", "銀金、月白、冷灰、紅木棕與暖燭", "銀金 satin 宮廷長裙、低領銀線胸衣、完整安全內襯、冷光水晶腰封與透明披袖", "銀金冠、白鑽耳墜、月銀項鍊與水晶手鏈", "銀色香盒與白玉杯", "銀金冷月皇宮寢榻", "白玉杯、銀色香盒、冷光裙擺與床榻", "真人寵妃端坐後微微斜靠，清冷凝視鏡頭", "月窗、白紗帳、金色宮燈與紅木深景", "人物一手扶床榻，一手低持白玉杯，姿態克制", "cool moon key、warm lantern balance、silver satin highlights"],
  ["wine-red-brocade-bed", "酒紅錦榻・濃艷寵妃", "酒紅錦榻", "酒紅、暗金、紅木棕與燭火橙", "酒紅 satin 宮廷低領禮服、完整內襯、暗金刺繡腰封、側開衩長裙與酒紅披袍", "酒紅寶石冠、紅寶耳墜、暗金項鍊與金絲腰鏈", "紅玉酒杯與金色燭台", "酒紅錦繡寢宮床榻", "酒杯、燭台、酒紅裙擺與錦墊", "真人寵妃斜靠床榻，身形豐盈修長，臉部明亮", "深紅帷幕、紅木屏風、宮燈與珠寶盒", "人物一手低持酒杯，一手扶披袍，正面或微側正面", "wine-red candle glow、gold embroidery sparkle、soft face fill"],
  ["tea-gold-wood-screen", "茶金木屏・靜坐寵妃", "茶金木屏", "茶金、檀木棕、香檳金與暖燭色", "茶金 satin 宮廷禮服、低領珠繡外層、完整內襯、簡潔奢華長裙與薄紗披袖", "茶晶金冠、琥珀耳墜、細金項鍊與玉戒", "茶盞、香盒與木屏", "茶金木屏皇宮寢殿", "茶盞、香盒、木屏邊緣與茶金裙擺", "真人寵妃靜坐床榻側方，腿部線條在裙擺下自然延伸", "檀木屏風、宮燈、紅木家具與絲帳", "人物一手扶木屏，一手低持茶盞，姿態端莊", "warm wood bounce、tea-gold satin highlights、soft editorial key"],
  ["opal-gold-jewel-bed", "歐泊金榻・珠光寵妃", "歐泊珠光", "歐泊白、淡金、珍珠粉與暖木棕", "歐泊金 satin 宮廷長裙、低領水晶胸衣、完整內襯、珠光腰封與輕薄披袍", "歐泊金冠、珍珠耳墜、白鑽項鍊與水晶腰飾", "歐泊珠寶盒與金色手鏡", "歐泊珠光皇宮寢榻", "珠寶盒、手鏡、歐泊裙擺與錦墊", "真人寵妃半躺床榻，臉部正視鏡頭，光澤華麗", "珠簾、宮燈、紅木床柱與絲綢帷幕", "人物一手扶床榻，一手低持手鏡，姿態舒展", "opal shimmer light、warm lantern glow、diamond sparkle"],
  ["bronze-gold-lantern-bed", "鎏銅宮燈・倚臂寵妃", "鎏銅倚臂", "鎏銅金、暖棕、琥珀與暗紅", "鎏銅 satin 宮廷低領長裙、完整安全內襯、金屬蕾絲邊、鑽石腰飾與寬袖披袍", "鎏銅花冠、琥珀耳墜、金色項鍊與臂釧", "鎏金宮燈與小香瓶", "鎏銅宮燈寢宮榻旁", "小香瓶、宮燈反光、鎏銅裙擺與床榻", "真人寵妃倚靠扶手，長腿斜向前景，臉部看鏡頭", "紅木家具、金色床帳、燭台與珠寶擺設", "人物一手倚扶手，一手低扶裙側，姿勢高級穩定", "bronze lantern key、amber silk bounce、metal lace sparkle"],
  ["pale-blue-silk-bed", "霧藍紗榻・清雅寵妃", "霧藍紗榻", "霧藍、淡金、月白與紅木棕", "霧藍 satin 宮廷長裙、低領淡金珠飾結構、完整內襯、透明霧藍披帛與側開衩裙擺", "霧藍寶冠、月白耳墜、細鑽項鍊與玉鐲", "霧藍團扇與白瓷茶盞", "霧藍紗帳皇宮寢榻", "團扇、茶盞、霧藍裙擺與紗帳邊緣", "真人寵妃側坐床榻，臉部正向鏡頭，姿態清雅", "霧藍帷幕、金色宮燈、紅木窗格與床榻", "人物一手低持團扇，一手扶床榻，長腿線條自然", "misty blue silk fill、warm lantern key、soft facial catchlight"],
  ["lotus-pink-satin-bed", "蓮粉緞榻・柔媚寵妃", "蓮粉緞榻", "蓮粉、香檳金、珍珠白與暖木棕", "蓮粉 satin 宮廷低領禮服、完整安全內襯、珍珠腰封、柔紗披袖與修長開衩裙擺", "蓮花金冠、粉晶耳墜、珍珠項鍊與細金手鏈", "蓮花香盒與粉晶團扇", "蓮粉緞面皇宮寢榻", "香盒、團扇、蓮粉裙擺與軟枕", "真人寵妃斜倚床榻，臉部正視鏡頭，肩頸線條柔和", "蓮紋屏風、金色宮燈、紅木床柱與絲帳", "人物一手扶軟枕，一手低持團扇，姿態成熟柔美", "lotus-pink bounce、champagne lantern glow、pearl highlights"],
].map(createBedchamberConsortExpansionProfile);

const BEDCHAMBER_SUCCUBUS_EXPANSION_PROFILES = [
  ["obsidian-gold-recline", "黑曜金榻・魅魔女王", "黑曜金榻", "黑曜石、暗金、酒紅與燭火紫", "黑曜 satin 高訂寢宮禮服、深領但有安全內襯的水晶胸衣、側開衩長裙、黑金薄紗披袍與翼形肩紗", "黑曜王冠、暗金流蘇耳飾、紫晶項鍊與金屬腰鏈", "黑玫酒杯與紫晶香爐", "黑曜寢宮王榻", "黑玫酒杯、紫晶香爐、黑金裙擺與軟枕", "真人魅魔女王斜躺王榻，臉部正視鏡頭，長腿線條由禮服自然延伸", "暗金宮燈、黑紅帷帳、哥德床柱與燭火", "人物一手撐王榻，一手低持酒杯，翼形披紗不遮臉", "obsidian candle key、purple rim light、gold satin sparkle"],
  ["ruby-moon-bed", "紅月絲榻・魅魔寵姬", "紅月絲榻", "血月紅、黑金、煙紫與燭火橙", "紅月 satin 高訂長裙、完整內襯、低領紅寶胸衣外層、黑紗披袖與修身腰封", "紅寶魔冠、黑金耳墜、紅晶項鍊與細鏈腰飾", "紅晶酒杯與黑玫瑰", "紅月夜宴寢榻", "黑玫瑰、酒杯、紅月裙擺與床榻錦墊", "真人魅魔寵姬側坐寢榻，臉部微側正面，姿態華麗", "紅月窗、黑金帷幕、燭台與深色紅木家具", "人物一手低持酒杯，一手扶床榻，腿部線條作為禮服剪裁點綴", "red moon backlight、warm candle fill、ruby sparkle"],
  ["amethyst-wing-lounge", "紫晶翼帳・魅魔女爵", "紫晶翼帳", "紫晶、黑緞、冷銀與暗金", "紫晶黑 satin 寢宮禮服、完整內襯、低領水晶胸衣、翼形透明披紗與高訂拖尾長裙", "紫晶冠、冷銀流蘇耳墜、黑鑽項鍊與水晶臂鏈", "紫晶星盤與黑色香盒", "紫晶翼帳哥德寢宮", "星盤、香盒、紫晶裙擺與翼形披紗", "真人魅魔女爵倚靠軟枕，臉部正視鏡頭，翼紗向後展開", "紫黑帷帳、金色宮燈、尖拱窗與燭火", "人物一手扶星盤，一手整理披紗，手不遮臉", "amethyst glow、silver rim light、warm gold practicals"],
  ["midnight-blue-satin", "午夜藍榻・魅魔名姝", "午夜藍榻", "午夜藍、黑金、月銀與紫霧", "午夜藍 satin 高訂低領長裙、完整安全內襯、黑金珠飾腰封、側開衩裙擺與月銀披紗", "藍寶魔冠、月銀耳墜、黑鑽頸鍊與金屬手鏈", "藍寶酒杯與月銀手鏡", "午夜藍哥德寢榻", "酒杯、手鏡、藍緞裙擺與床榻邊緣", "真人魅魔名姝坐於床榻側，長腿線條自然延伸，臉部明亮", "月窗、藍黑帷幕、宮燈與燭火", "人物一手低持手鏡，一手扶床榻，微側正面看鏡頭", "midnight blue bounce、moon rim、warm candle facial fill"],
  ["rose-smoke-couch", "煙玫瑰榻・魅魔夢姬", "煙玫瑰榻", "煙玫瑰、黑紫、香檳金與柔燭色", "煙玫瑰 satin 寢宮禮服、完整內襯、低領蕾絲外層、薄紗披袖與修身長裙", "玫瑰金魔冠、粉晶流蘇耳墜、細鑽項鍊與黑金腰鏈", "煙玫瑰香瓶與粉晶酒杯", "煙玫瑰夜宴寢宮", "香瓶、酒杯、煙玫瑰裙擺與軟枕", "真人魅魔夢姬半倚軟榻，臉部正向鏡頭", "玫瑰色帷幕、黑金床柱、宮燈與柔霧", "人物一手扶軟枕，一手低持酒杯，姿態柔媚但端正", "rose smoke haze、champagne lantern key、soft glam fill"],
  ["emerald-venom-bed", "翡翠毒藤・魅魔女王", "翡翠毒藤", "翡翠綠、黑金、毒藤紫與暖金", "翡翠黑 satin 禮服、完整安全內襯、低領金藤胸衣外層、側開衩長裙與藤蔓刺繡披袖", "翡翠魔冠、綠寶耳墜、黑金項鍊與藤紋腰鏈", "翡翠酒盞與黑藤香爐", "翡翠毒藤寢宮王榻", "酒盞、香爐、藤紋披袖與綠緞裙擺", "真人魅魔女王側倚王榻，臉部明亮，身形修長", "黑金帷幕、綠色燭火、紅木床榻與珠寶擺設", "人物一手扶床柱，一手低持酒盞，雙眼看向鏡頭", "emerald candle glow、gold edge light、green satin highlights"],
  ["silver-moon-succubus", "銀月紗榻・魅魔聖姬", "銀月紗榻", "銀月、黑白、淡金與紫灰", "銀月 satin 高訂長裙、完整內襯、低領銀線胸衣、透明月紗披肩與修身開衩裙擺", "銀月魔冠、白鑽耳墜、月銀項鍊與水晶臂鏈", "銀色聖杯與月形香盒", "銀月紗帳魅魔寢榻", "聖杯、月形香盒、銀月裙擺與紗帳", "真人魅魔聖姬側臥紗榻，臉部正視鏡頭", "月窗、銀白帷幕、黑金燭台與柔焦床柱", "人物一手撐床榻，一手低持聖杯，姿態清冷", "cool moon key、warm candle balance、silver satin sheen"],
  ["wine-velvet-lounge", "酒紅絲絨・魅魔女爵", "酒紅絲絨", "酒紅、黑金、暗玫瑰與燭火", "酒紅 satin 絲絨感寢宮禮服、完整內襯、低領黑蕾絲外層、長裙開衩與黑紅披袍", "紅寶魔冠、黑金耳墜、酒紅寶石項鍊與細鏈腰飾", "紅酒杯與黑玫瑰手包", "酒紅夜宴魅魔寢宮", "紅酒杯、黑玫瑰、酒紅裙擺與軟枕", "真人魅魔女爵低靠軟榻，長腿線條由裙擺帶出", "酒紅帷幕、黑金宮燈、紅木家具與燭火", "人物一手低持紅酒杯，一手扶披袍，臉部正向鏡頭", "wine velvet glow、candle key、ruby catchlight"],
  ["pearl-black-crown", "黑珍珠榻・魅魔王妃", "黑珍珠榻", "黑珍珠、香檳金、煙灰與燭火紫", "黑珍珠 satin 宮廷魅魔禮服、完整安全內襯、低領珍珠胸衣外層、黑金薄紗袖與長裙拖尾", "黑珍珠王冠、珍珠流蘇耳墜、黑鑽項鍊與金色臂釧", "黑珍珠盒與金色香瓶", "黑珍珠宮燈王妃寢榻", "珍珠盒、香瓶、黑珍珠裙擺與床榻錦墊", "真人魅魔王妃端坐後斜靠，臉部清楚看向鏡頭", "黑金帷幕、宮燈、紅木床柱與珠簾", "人物一手扶珍珠盒，一手整理薄紗袖，姿態高貴", "black pearl sheen、gold lantern key、soft purple rim"],
  ["copper-horn-couch", "銅金角冠・魅魔御姬", "銅金角冠", "銅金、黑棕、琥珀與暗紅", "銅金 satin 高訂寢宮長裙、完整內襯、低領金屬蕾絲外層、側開衩裙擺與黑棕披袍", "銅金小角冠、琥珀耳墜、金屬項圈式項鍊與臂鏈", "銅燈與琥珀酒杯", "銅金魅魔寢宮軟榻", "銅燈、酒杯、銅金裙擺與軟枕", "真人魅魔御姬倚臂軟榻，臉部微側正面", "暖暗宮燈、紅木牆、黑金帷幕與燭火", "人物一手倚扶手，一手低持酒杯，長腿自然延伸", "copper practical glow、amber satin highlights、soft face fill"],
  ["frost-blue-gothic-bed", "冰藍霜榻・魅魔冰姬", "冰藍霜榻", "冰藍、銀白、黑金與冷紫", "冰藍 satin 高訂長裙、完整安全內襯、低領水晶胸衣、銀白披紗與修長側開衩裙擺", "冰晶魔冠、銀白耳墜、藍鑽項鍊與水晶手鏈", "冰晶酒杯與銀色香盒", "冰藍霜光哥德寢榻", "冰晶酒杯、香盒、冰藍裙擺與白霧", "真人魅魔冰姬側臥床榻，臉部正視鏡頭", "冷月窗、黑金床柱、銀白帷幕與藍色燭火", "人物一手撐床榻，一手低持冰晶杯，姿態冷艷", "icy moon key、blue candle rim、silver satin sparkle"],
  ["gold-butterfly-succubus", "金蝶夜榻・魅魔花姬", "金蝶夜榻", "金蝶色、黑紫、蜜金與燭火橙", "金蝶 satin 寢宮禮服、完整內襯、低領蝶翼胸衣外層、黑紫薄紗披袖與高訂長裙", "金蝶魔冠、蝶形流蘇耳飾、蜜金項鍊與水晶腰鏈", "金蝶面具與小酒杯", "金蝶夜宴魅魔寢榻", "面具、酒杯、蝶翼披袖與金蝶裙擺", "真人魅魔花姬半倚軟榻，臉部正面明亮", "黑紫帷幕、金色宮燈、蝶形珠簾與紅木家具", "人物一手低持面具，一手扶軟枕，披袖不遮臉", "gold butterfly sparkle、purple haze rim、warm lantern key"],
  ["crimson-spider-silk", "緋蛛絲榻・魅魔織姬", "緋蛛絲榻", "緋紅、黑金、煙紫與燭火", "緋紅 satin 高訂長裙、完整內襯、低領黑蕾絲胸衣外層、蛛絲紋披紗與側開衩裙擺", "緋紅魔冠、黑金蛛絲耳墜、紅晶項鍊與細鏈腰飾", "紅晶香爐與黑絲手扇", "緋紅蛛絲魅魔寢宮", "香爐、手扇、蛛絲披紗與紅裙擺", "真人魅魔織姬坐於床榻側方，長腿線條自然呈現", "蛛絲紋帷幕、黑金宮燈、紅木床榻與燭火", "人物一手低持手扇，一手扶床榻，眼神看鏡頭", "crimson candle key、black lace texture、ruby sparkle"],
  ["violet-orchid-bed", "紫蘭香榻・魅魔香姬", "紫蘭香榻", "紫蘭、黑金、香檳紫與暖燭", "紫蘭 satin 寢宮禮服、完整安全內襯、低領水晶外層、柔紗披袖與修長長裙", "紫蘭魔冠、紫晶耳墜、細鑽項鍊與黑金手鏈", "紫蘭香瓶與水晶酒杯", "紫蘭香霧魅魔寢榻", "香瓶、酒杯、紫蘭裙擺與香霧", "真人魅魔香姬倚靠軟枕，臉部正視鏡頭", "紫蘭帷幕、金色宮燈、紅木床柱與霧氣", "人物一手扶香瓶，一手整理披袖，姿態成熟", "violet haze、warm lantern key、crystal highlights"],
  ["dark-jade-moon-bed", "暗玉月榻・魅魔妖后", "暗玉月榻", "暗玉綠、黑金、月銀與冷紫", "暗玉 satin 高訂魅魔禮服、完整內襯、低領金邊胸衣、側開衩長裙與黑綠披紗", "暗玉魔冠、綠寶耳墜、月銀項鍊與金絲腰鏈", "暗玉酒杯與月形香爐", "暗玉月窗魅魔寢榻", "酒杯、香爐、暗玉裙擺與月窗反光", "真人魅魔妖后側倚床榻，臉部明亮且凝視鏡頭", "月窗、黑金帷幕、綠色燭火與紅木家具", "人物一手扶床柱，一手低持酒杯，姿態威儀", "dark jade bounce、moon rim light、green candle glow"],
  ["champagne-black-silk", "香檳黑紗・魅魔名伶", "香檳黑紗", "香檳金、黑紗、珍珠白與暖燭", "香檳 satin 禮服、完整安全內襯、低領黑蕾絲外層、黑紗披袖與高訂開衩長裙", "香檳金魔冠、珍珠流蘇耳墜、黑鑽項鍊與細金手鏈", "黑紗團扇與香檳杯", "香檳黑紗夜宴寢宮", "團扇、香檳杯、黑紗披袖與香檳裙擺", "真人魅魔名伶斜坐床榻，臉部正視鏡頭", "黑金帷幕、宮燈、紅木妝台與床榻深景", "人物一手低持團扇，一手扶床榻，長腿線條自然", "champagne practicals、black lace rim、soft editorial fill"],
  ["blood-amber-throne-bed", "血珀王榻・魅魔女帝", "血珀王榻", "血珀、黑金、暗紅與紫霧", "血珀 satin 高訂寢宮長裙、完整內襯、低領紅晶胸衣、黑金披袍與修長開衩裙擺", "血珀王冠、紅晶耳墜、黑金項鍊與寶石腰鏈", "血珀權杖與紅酒杯", "血珀王榻魅魔寢宮", "權杖、酒杯、血珀裙擺與王榻錦墊", "真人魅魔女帝倚坐王榻，臉部正面清楚，姿態有王權感", "黑紅帷幕、金色燭台、哥德床柱與紫霧", "人物一手扶權杖，一手低持酒杯，身體斜靠但端正", "blood amber key、purple rim haze、gold edge light"],
  ["moon-silver-chain", "月銀鏈紗・魅魔月姬", "月銀鏈紗", "月銀、黑紫、冷白與淡金", "月銀 satin 高訂低領禮服、完整內襯、細鏈肩飾、黑紫透明披紗與側開衩長裙", "月銀魔冠、鏈條耳飾、白鑽項鍊與水晶腰鏈", "月銀手鏡與水晶杯", "月銀鏈紗魅魔寢榻", "手鏡、水晶杯、鏈紗肩飾與月銀裙擺", "真人魅魔月姬側臥床榻，臉部正視鏡頭", "月窗、黑紫帷幕、銀色燈架與柔焦燭火", "人物一手低持手鏡，一手撐床榻，姿態舒展", "silver moon fill、soft candle key、chain sparkle"],
  ["onyx-red-lantern", "縞瑪瑙燈・魅魔掌燈姬", "縞瑪瑙掌燈", "縞瑪瑙黑、暗紅、古金與燭火橙", "縞瑪瑙黑 satin 禮服、完整安全內襯、暗紅低領胸衣外層、古金腰封與黑紅披袍", "黑曜魔冠、暗紅耳墜、古金項鍊與黑晶手鏈", "紅色宮燈與黑玉香盒", "縞瑪瑙夜燈魅魔寢宮", "紅燈、香盒、黑紅裙擺與床榻邊緣", "真人魅魔掌燈姬坐在床榻邊，臉部被紅燈柔光照亮", "黑金帷幕、紅木家具、燭台與深色珠簾", "人物一手提紅色宮燈，一手扶床榻，手不遮臉", "red lantern key、onyx satin rim、warm gold bounce"],
  ["opal-night-succubus", "夜歐泊榻・魅魔幻姬", "夜歐泊幻姬", "夜歐泊、黑藍、淡金與紫霧", "夜歐泊 satin 高訂禮服、完整內襯、低領珠光胸衣、黑藍薄紗披袖與長裙開衩", "歐泊魔冠、珠光耳墜、白鑽項鍊與水晶腰飾", "歐泊珠寶盒與藍紫酒杯", "夜歐泊幻光魅魔寢榻", "珠寶盒、酒杯、歐泊裙擺與幻光霧氣", "真人魅魔幻姬半躺床榻，臉部正視鏡頭，光澤夢幻", "藍紫帷幕、金色宮燈、紅木床柱與珠簾", "人物一手扶珠寶盒，一手撐床榻，姿態華麗", "opal shimmer、blue-purple rim、warm lantern fill"],
  ["smoky-gold-veil", "煙金薄紗・魅魔簾后", "煙金薄紗", "煙金、黑灰、香檳色與燭火", "煙金 satin 寢宮禮服、完整內襯、低領金線胸衣、黑灰透明披紗與側開衩長裙", "煙金魔冠、灰晶耳墜、金色項鍊與細鏈臂飾", "煙金香爐與薄紗簾", "煙金簾幕魅魔寢宮", "香爐、薄紗簾、煙金裙擺與軟枕", "真人魅魔簾后坐於帷幕前，長腿線條由裙擺自然露出，臉部清楚", "煙灰帷幕、宮燈、紅木床榻與燭光", "人物一手撩薄紗簾，一手扶軟枕，正視鏡頭", "smoky gold haze、warm lantern key、soft glam fill"],
].map(createBedchamberSuccubusExpansionProfile);

export const STYLE_REFERENCE_PROFILES = [
  {
    id: "style-ref-flower-window-qipao",
    title: "花窗牡丹・奶油白旗袍名媛",
    parentCategory: "現代都市 / 街拍電影",
    series: "風格範例轉卡／花窗旗袍",
    themeHint: "花窗 牡丹 奶油白旗袍 珍珠髮飾 室內柔光",
    aliases: ["風格範例", "花窗旗袍", "牡丹刺繡", "奶油白", "珍珠髮飾"],
    identity: "花窗牡丹奶油白旗袍名媛",
    palette: "奶油白、粉牡丹、珍珠金與柔木棕",
    costumeCore: "奶油白緞面旗袍、粉色牡丹刺繡、半透明披紗與合身但端正的室內名媛禮服輪廓",
    jewelry: "珍珠流蘇髮飾、細珍珠項鍊、玉鐲與小型金色耳飾",
    prop: "粉牡丹花枝與珍珠手包",
    place: "中式花窗室內花房",
    foreground: "粉牡丹、薄紗窗簾與柔焦花影",
    midground: "真人名媛站在木格花窗旁中景，肩頸與旗袍刺繡清楚",
    background: "木格窗、室內花器、玉石擺件與窗外綠意",
    action: "人物一手低持花枝，一手自然扶住珍珠項鍊或手包，眼神安靜看向鏡頭",
    lighting: "soft window key light、warm flower-room bounce、pearl and silk highlights",
  },
  {
    id: "style-ref-stardust-silver-evening-muse",
    title: "星塵銀紗・水晶夜宴名媛",
    parentCategory: "現代都市 / 街拍電影",
    series: "風格範例轉卡／水晶夜宴",
    themeHint: "銀鑽薄紗 晚禮服 長髮逆光 灰金 sparkle",
    aliases: ["銀鑽", "星塵", "水晶晚禮服", "逆光長髮"],
    identity: "星塵銀紗水晶夜宴名媛",
    palette: "銀白、水晶灰、香檳金與柔膚暖光",
    costumeCore: "銀白水晶刺繡晚禮服、細密珠飾、透明外紗罩裙與安全內襯結構，呈現高訂晚宴質感而非低俗禮服",
    jewelry: "水晶長耳墜、細鑽項鍊、銀色戒指與髮絲珠光飾件",
    prop: "水晶手包與香檳色薄紗披肩",
    place: "灰金夜宴露台座椅旁",
    foreground: "薄紗裙擺、水晶手包與柔焦光點",
    midground: "真人名媛端坐或站在露台座椅旁，禮服輪廓完整不以胸腰腿為主視覺",
    background: "灰金牆面、木質扶手、遠景燈球與細緻空氣粒子",
    action: "人物一手扶椅背，一手低持手包，長髮受側風帶起但不遮臉",
    lighting: "bright champagne rim light、soft facial fill、crystal sparkle highlights",
    atmosphere: "安全高訂夜宴電影海報主視覺，避免 pin-up 與身體特寫",
  },
  {
    id: "style-ref-champagne-wine-bar-gown-diva",
    title: "香檳酒紅・吧台晚禮服名伶",
    parentCategory: "現代都市 / 街拍電影",
    series: "風格範例轉卡／吧台晚禮服",
    themeHint: "吧台 名伶 香檳金酒紅漸層 晚禮服 栗棕編髮 粉色蝴蝶結",
    aliases: ["吧台晚禮服", "香檳酒紅", "栗棕編髮", "粉色蝴蝶結", "高開衩禮服", "都會名伶"],
    identity: "香檳酒紅吧台晚禮服名伶",
    palette: "香檳金、玫瑰酒紅、暖琥珀、黑曜吧台與柔粉髮飾",
    costumeCore: "香檳金到酒紅漸層亮片高訂晚禮服、交疊深 V 掛脖胸線、完整安全內襯、收腰垂墜結構、高開衩長裙與金色細帶高跟鞋，呈現都會奢華而非低俗禮服",
    jewelry: "細鑽鎖骨鍊、玫瑰金手鍊、長耳墜、粉色蝴蝶結髮飾與栗棕色長髮編髮元素",
    prop: "紅酒杯、吧台玻璃器皿與小型珠寶手包",
    place: "暖色高級酒吧吧台",
    foreground: "紅酒杯、花束柔焦、亮片裙擺、吧台反光與暖色散景光斑",
    midground: "真人都會名伶倚靠吧台中景，禮服 V 線與高開衩裙擺完整入鏡，臉部正面清楚",
    background: "酒瓶陳列、皮革高腳椅、窗外夜景、植物暗影與金色氛圍燈",
    action: "人物一手低持紅酒杯於胸口下方，另一手自然扶住吧台邊緣，身體微側但臉部正面看向鏡頭，手與酒杯不遮五官",
    lighting: "warm amber bar practicals、soft Vogue facial fill、champagne sequin sparkle、shallow depth of field bokeh、subtle volumetric glow",
    atmosphere: "幻想系都會名伶電影海報主視覺，栗棕編髮與粉色蝴蝶結帶溫柔夢幻氣質，但不引用既有遊戲角色名稱",
  },
  {
    id: "style-ref-rain-lantern-red-umbrella-maiko",
    title: "雨巷紅傘・夜燈和風姬",
    parentCategory: "東方和風旅拍",
    series: "風格範例轉卡／雨夜紅傘",
    themeHint: "雨夜 紅傘 和風 花魁 黑紅和服 燈籠街道",
    aliases: ["雨夜紅傘", "和風", "花魁", "黑紅和服", "燈籠雨巷"],
    identity: "雨巷紅傘夜燈和風姬",
    palette: "深靛黑、朱紅、燈籠暖橙、雨水冷灰與金線點綴",
    costumeCore: "黑紅層疊和風禮服、花紋外掛、寬腰封、長袖披擺與完整安全內襯，呈現雨夜花街電影感",
    jewelry: "紅花髮簪、黑金流蘇髮飾、小型耳墜與細金指飾",
    prop: "大型朱紅紙傘、腰間香囊與雨巷燈籠",
    place: "雨夜燈籠古街",
    foreground: "雨滴、水面倒影、紅傘邊緣與濕石板反光",
    midground: "真人和風姬站在雨巷中央，紅傘形成圓形構圖，臉部清楚不被傘遮住",
    background: "紅色燈籠、木造街屋、夜霧、遠景招牌與細雨光絲",
    action: "人物雙手自然扶住傘柄下方，傘面抬高露出五官，身體微側但視線看向鏡頭",
    lighting: "red lantern practicals、cool rain rim light、soft facial fill、wet street reflections",
    atmosphere: "東方和風雨夜電影海報，神秘、華麗、克制，不做低角度挑逗構圖",
  },
  {
    id: "style-ref-burgundy-rose-chaise-diva",
    title: "酒紅玫瑰・花房長裙名伶",
    parentCategory: "高訂婚紗禮服",
    series: "風格範例轉卡／酒紅玫瑰禮服",
    themeHint: "酒紅晚禮服 玫瑰花房 貴妃椅 高開衩 暖暗花影",
    aliases: ["酒紅禮服", "玫瑰花房", "貴妃椅", "高訂長裙", "花影名伶"],
    identity: "酒紅玫瑰花房長裙名伶",
    palette: "深酒紅、玫瑰粉、暗木棕、柔金與暖膚光",
    costumeCore: "酒紅緞面高訂晚禮服、立體胸衣外層、完整安全內襯、側開衩長裙與垂墜裙擺",
    jewelry: "紅寶耳墜、玫瑰金髮夾、細鑽項鍊與金色手鍊",
    prop: "深紅玫瑰花枝、絲緞手包與花房靠墊",
    place: "暗調玫瑰花房貴妃椅",
    foreground: "玫瑰花瓣、垂落裙擺、絲緞手包與椅面暗紋",
    midground: "真人名伶倚坐貴妃椅，腿部由裙擺自然延伸，臉部微側正面清楚",
    background: "巨型玫瑰花牆、暗色壁紙、柔焦花影與暖色壁燈",
    action: "人物一手扶住貴妃椅邊緣，一手輕靠花枝旁但不遮臉，坐姿有明確支撐點",
    lighting: "warm floral key light、soft rose bounce、satin highlight、shallow depth of field",
    atmosphere: "高訂花房晚禮服封面感，華麗成熟但避免 pin-up 與身體局部特寫",
  },
  {
    id: "style-ref-blush-crystal-magazine-princess",
    title: "粉晶封面・夢紗禮服公主",
    parentCategory: "高訂婚紗禮服",
    series: "風格範例轉卡／粉晶封面禮服",
    themeHint: "粉晶禮服 時尚封面 水晶背景 夢幻薄紗 長裙",
    aliases: ["粉晶禮服", "時尚封面", "水晶薄紗", "夢紗公主", "高訂長裙"],
    identity: "粉晶封面夢紗禮服公主",
    palette: "霧粉、粉紫、水晶銀、珍珠白與香檳金",
    costumeCore: "粉紫水晶刺繡高訂禮服、層疊薄紗裙、完整安全內襯、羽片感肩飾與拖尾裙擺",
    jewelry: "水晶髮飾、粉鑽耳墜、細鑽手鍊與珍珠戒指",
    prop: "水晶手包與透明薄紗披肩",
    place: "粉晶水晶時尚攝影棚",
    foreground: "薄紗拖尾、水晶手包、柔焦光點與封面式留白",
    midground: "真人禮服公主站在水晶佈景中央，完整禮服輪廓與臉部都清楚",
    background: "粉紫水晶吊飾、亮片幕牆、柔焦燈球與高級攝影棚反光",
    action: "人物一手輕扶薄紗裙擺，一手自然垂落，封面站姿挺拔但不呆板",
    lighting: "bright fashion cover key、pink crystal sparkle、soft facial fill、champagne rim light",
    atmosphere: "國際時尚雜誌封面質感，不生成可讀品牌文字或雜誌標誌",
  },
  {
    id: "style-ref-black-gold-crystal-cover-diva",
    title: "黑金封面・夜晶禮服女王",
    parentCategory: "高訂婚紗禮服",
    series: "風格範例轉卡／黑金封面禮服",
    themeHint: "黑金禮服 水晶夜景 時尚封面 高開衩 金色散景",
    aliases: ["黑金禮服", "水晶夜景", "時尚封面", "夜晶女王", "金色散景"],
    identity: "黑金封面夜晶禮服女王",
    palette: "墨黑、古金、香檳金、水晶透明與深夜灰",
    costumeCore: "黑金亮片高訂長禮服、完整安全內襯、深色薄紗披層、金線刺繡與側開衩拖尾",
    jewelry: "黑鑽耳墜、金色髮飾、水晶手鍊與細金腰飾",
    prop: "黑色珠寶手包與水晶台座",
    place: "黑金水晶夜景攝影棚",
    foreground: "黑金裙擺、水晶台座、珠寶手包與金色散景光斑",
    midground: "真人女王站在封面式燈光中央，禮服剪裁完整入鏡，臉部正面清楚",
    background: "金色吊燈、深色玻璃、亮片幕牆與夜景反光",
    action: "人物一手扶住水晶台座邊緣，一手自然整理披紗，身體微側但眼神看向鏡頭",
    lighting: "black-gold editorial key、champagne rim light、crystal sparkle highlights、soft face fill",
    atmosphere: "黑金高訂封面大片，不生成可讀品牌文字或雜誌標誌",
  },
  {
    id: "style-ref-egypt-gold-bob-queen",
    title: "尼羅金冠・短髮埃及女王",
    parentCategory: "埃及豔后／尼羅河女兒／埃及神話女神",
    series: "風格範例轉卡／埃及金冠",
    themeHint: "埃及女王 金冠 短髮 鎖骨項圈 神殿石柱",
    aliases: ["埃及女王", "尼羅金冠", "短髮", "黃金項圈", "神殿石柱"],
    identity: "尼羅金冠短髮埃及女王",
    palette: "沙金、象牙白、孔雀綠、青金石藍與日光暖灰",
    costumeCore: "象牙白埃及垂墜長裙、金屬胸飾外層、完整安全內襯、金色腰封與細褶披紗",
    jewelry: "寬幅黃金項圈、青金石額飾、蛇形臂釧、金色耳環與多層手鐲",
    prop: "紙莎草卷、金色權杖作為身側陳設與石座扶手",
    place: "尼羅神殿石柱迴廊",
    foreground: "紙莎草卷、金色臂釧、石階紋理與沙塵光",
    midground: "真人埃及女王半身到中景站在石柱旁，短髮與金冠輪廓清楚",
    background: "神殿石柱、雕刻牆面、尼羅日光與金色浮塵",
    action: "人物一手扶住石柱或項圈邊緣，權杖靠在身側不必手持，臉部正面凝視鏡頭",
    lighting: "golden temple sunlight、soft stone bounce、lapis jewelry sparkle、warm haze",
    atmosphere: "埃及神話女王肖像，莊嚴、精緻、時尚，不做低俗艷后刻板姿態",
  },
  {
    id: "style-ref-silver-cathedral-archangel",
    title: "銀翼聖殿・白金大天使",
    parentCategory: "暗黑墮天使",
    series: "風格範例轉卡／銀翼聖殿",
    themeHint: "白金天使 銀翼 聖殿 高挑禮服 光柱 權杖",
    aliases: ["銀翼", "白金天使", "聖殿", "光柱", "神聖禮服"],
    identity: "銀翼聖殿白金大天使",
    palette: "銀白、白金、冷月藍、珍珠灰與神殿金",
    costumeCore: "白金聖殿長禮服、金屬胸甲外層、完整安全內襯、銀白披紗、翼形肩飾與長靴",
    jewelry: "光環冠飾、白鑽耳墜、銀色臂環與神聖符文腰鏈",
    prop: "銀白權杖、羽翼、聖殿浮雕與光柱",
    place: "白金哥德聖殿大廳",
    foreground: "羽毛、權杖底座、銀白裙擺與大理石反光",
    midground: "真人大天使站在聖殿光柱中，全身比例修長，羽翼向後展開不遮臉",
    background: "高拱窗、聖殿柱廊、冷白光束與金色浮塵",
    action: "人物一手扶權杖作垂直支撐，一手自然展開披紗，站姿有重心且五官清楚",
    lighting: "cathedral volumetric light、silver rim light、soft divine facial fill、white-gold sparkle",
    atmosphere: "神聖天使史詩封面，莊嚴冷艷，不做低俗奇幻盔甲",
  },
  {
    id: "style-ref-neon-fighting-street-heroine",
    title: "霓虹拳影・街頭格鬥戰姬",
    parentCategory: "動漫次文化街拍",
    series: "風格範例轉卡／街頭格鬥",
    themeHint: "街頭格鬥 霓虹塗鴉 運動短裝 拳套 動態姿勢",
    aliases: ["街頭格鬥", "霓虹塗鴉", "拳套", "運動戰姬", "動態海報"],
    identity: "霓虹拳影街頭格鬥戰姬",
    palette: "黑白運動色、熱粉、電紫、霓虹藍與濕街反光",
    costumeCore: "白色運動背心、黑色機能短裙或短褲、安全運動內搭、護腕、格鬥手套與短靴",
    jewelry: "小型耳扣、運動髮帶、金屬頸鏈與機能腕帶",
    prop: "格鬥拳套、霓虹塗鴉牆與能量粉塵",
    place: "霓虹塗鴉地下街格鬥場",
    foreground: "粉紫能量粉塵、濕地反光、拳套邊緣與動態光跡",
    midground: "真人格鬥戰姬採低重心預備姿，肩、腰、膝方向合理，臉部清楚看鏡頭",
    background: "塗鴉牆、霓虹燈牌、城市夜景、煙霧與觀眾剪影",
    action: "人物一手護在身前一手後拉蓄勢，拳套不遮臉，雙腳分開建立真實格鬥重心",
    lighting: "neon magenta-blue rim、hard sports key、wet pavement reflections、cinematic motion particles",
    atmosphere: "遊戲感街頭格鬥海報，但不引用既有角色名稱與商標",
  },
  {
    id: "style-ref-island-rail-summer-traveler",
    title: "海島軌道・陽光運動旅人",
    parentCategory: "海岸度假旅拍",
    series: "風格範例轉卡／海島軌道",
    themeHint: "海島旅拍 山海軌道 運動泳裝 繩結披肩 陽光",
    aliases: ["海島旅拍", "山海軌道", "運動泳裝", "陽光旅人", "度假"],
    identity: "海島軌道陽光運動旅人",
    palette: "晴空藍、海水青、日光白、熱帶綠與暖沙色",
    costumeCore: "黑白運動度假套裝、安全泳裝式上衣、機能短裙或短褲、輕薄防曬外衫與運動涼鞋",
    jewelry: "貝殼耳飾、細繩手環、運動墨鏡與簡約項鍊",
    prop: "彩色繩結披肩、旅行水壺與小型運動包",
    place: "海島山坡觀景軌道旁",
    foreground: "軌道木枕、熱帶草葉、運動包與日光陰影",
    midground: "真人旅人站在觀景平台或軌道旁，身體完整入鏡，臉部朝向鏡頭",
    background: "海灣城市、山坡綠意、藍天白雲與遠方海面",
    action: "人物一手拉開彩色披肩迎風，一手扶住身側欄杆或背包肩帶，站姿穩定",
    lighting: "bright tropical sunlight、clean sky fill、sea reflection bounce、crisp travel-photo clarity",
    atmosphere: "海島運動旅拍大片，健康陽光，不做低俗泳裝寫真",
  },
  {
    id: "style-ref-sky-swing-white-tulle-muse",
    title: "晴空鞦韆・白紗雲海少女",
    parentCategory: "田園花園旅拍",
    series: "風格範例轉卡／晴空鞦韆",
    themeHint: "晴空 鞦韆 白紗禮裙 雲海 透明窗景",
    aliases: ["晴空鞦韆", "白紗禮裙", "雲海", "天空旅拍", "夢幻窗景"],
    identity: "晴空鞦韆白紗雲海少女",
    palette: "晴空藍、雲白、珍珠白、淡金與清透水色",
    costumeCore: "白色薄紗禮裙、完整安全內襯、羽毛感裙擺、細肩外紗與輕盈拖尾",
    jewelry: "珍珠髮夾、細鑽耳墜、白色手鍊與小花髮飾",
    prop: "白色鞦韆繩、透明窗框與雲朵紗簾",
    place: "高空玻璃窗景鞦韆",
    foreground: "白紗裙擺、鞦韆座、透明窗反光與雲影",
    midground: "真人少女坐在鞦韆上，雙手自然扶繩，裙擺垂落形成雲朵感",
    background: "藍天白雲、遠方湖海、透明玻璃牆與柔光室內",
    action: "人物雙手輕扶鞦韆繩，坐姿端正且臉部正面清楚，雙腳自然下垂或輕點地",
    lighting: "clear sky window key、soft cloud bounce、white tulle highlights、airy high-key exposure",
    atmosphere: "清透明亮的天空童話旅拍，不做低角度腿部特寫",
  },
  {
    id: "style-ref-loulan-sunset-desert-princess",
    title: "樓蘭夕照・沙漠披紗公主",
    parentCategory: "東方異域 / 絲路西域",
    series: "風格範例轉卡／樓蘭夕照",
    themeHint: "沙漠 夕陽 樓蘭 披紗 長髮 遺跡",
    aliases: ["樓蘭", "沙漠夕陽", "絲路公主", "披紗", "古城遺跡"],
    identity: "樓蘭夕照沙漠披紗公主",
    palette: "沙金、赭橙、銅棕、暮紫與柔黑髮色",
    costumeCore: "絲路披紗長裙、赭橙刺繡外袍、完整安全內襯、腰鏈與輕薄頭紗",
    jewelry: "銅金額飾、綠松石耳墜、細鏈面紗飾、手環與腰間玉飾",
    prop: "絲路披紗、皮革水袋與古城石柱",
    place: "樓蘭沙漠遺跡夕陽坡地",
    foreground: "沙粒、披紗邊緣、皮革水袋與石牆裂紋",
    midground: "真人公主站在沙丘與遺跡之間，回眸看向鏡頭，臉部半側光清楚",
    background: "沙漠山脊、殘破城牆、落日天空與暖色風沙",
    action: "人物一手扶住被風吹起的披紗，一手自然貼近石柱或腰側，沒有多餘手持道具",
    lighting: "low sunset backlight、warm sand bounce、cinematic dust haze、soft eye catchlight",
    atmosphere: "絲路西域電影旅拍，孤獨、神秘、壯闊，不做無支撐呆站",
  },
  {
    id: "style-ref-qing-autumn-maple-consort",
    title: "清苑金秋・楓影旗裝貴妃",
    parentCategory: "清宮旗裝／雪苑貴妃／晚清宮廷寫實",
    series: "風格範例轉卡／清苑金秋",
    themeHint: "清宮 旗裝 楓葉 金秋 宮牆 扶柱",
    aliases: ["清宮旗裝", "楓葉", "金秋", "宮牆", "旗裝貴妃"],
    identity: "清苑金秋楓影旗裝貴妃",
    palette: "宮廷黃、墨黑、楓葉橙、暖金與朱紅宮牆",
    costumeCore: "黃色刺繡清宮旗裝、黑色滾邊、完整端莊內襯、立領盤扣與長直袍身",
    jewelry: "清宮旗頭、金色耳墜、碧玉手鐲、點翠髮飾與小型胸針",
    prop: "楓葉、宮門朱柱與小型絲帕",
    place: "秋日清宮紅柱迴廊",
    foreground: "落楓、石階、絲帕與旗裝下擺",
    midground: "真人貴妃站在紅柱旁，旗裝輪廓完整，臉部微側正面看鏡頭",
    background: "朱紅宮牆、金色楓樹、宮門陰影與秋日斜光",
    action: "人物一手扶住紅柱，一手自然整理袖口或絲帕，沒有酒杯與多餘硬道具",
    lighting: "golden autumn side light、warm palace wall bounce、soft face fill、falling leaves sparkle",
    atmosphere: "晚清宮廷寫實時尚大片，端莊、高貴、秋色明亮",
  },
  {
    id: "style-ref-dunhuang-turquoise-flying-dancer",
    title: "敦煌孔雀・金冠飛天舞姬",
    parentCategory: "敦煌飛天",
    series: "風格範例轉卡／孔雀飛天",
    themeHint: "敦煌 飛天 孔雀藍 金冠 披帛 壁畫 舞姿",
    aliases: ["敦煌", "孔雀藍", "飛天舞姬", "金冠", "披帛"],
    identity: "敦煌孔雀金冠飛天舞姬",
    palette: "孔雀藍、沙金、青綠、琥珀橙與壁畫深褐",
    costumeCore: "敦煌飛天舞衣、孔雀藍與金橙披帛、完整安全內襯、金線胸衣外層與層疊長裙",
    jewelry: "華麗金冠、綠松石耳飾、額飾、臂釧、腰鏈與流蘇步搖",
    prop: "長披帛、金鈴與敦煌壁畫圓光",
    place: "敦煌壁畫佛龕舞台",
    foreground: "孔雀藍披帛、金鈴、舞裙流線與壁畫金粉",
    midground: "真人飛天舞姬旋身起舞，雙臂帶動披帛形成環形構圖，臉部清楚",
    background: "敦煌壁畫、佛龕圓光、深色洞窟紋樣與金色浮塵",
    action: "人物以旋身舞姿拉開長披帛，手部遠離五官，腳步有真實落點與重心",
    lighting: "warm grotto spotlight、gold dust haze、turquoise fabric highlights、soft facial fill",
    atmosphere: "敦煌飛天舞蹈大片，華麗動態但保持舞衣完整與姿態合理",
  },
  {
    id: "style-ref-moon-palace-silver-fairy",
    title: "銀月星河・月宮白紗仙姬",
    parentCategory: "仙俠神話 / 古裝陸劇",
    series: "風格範例轉卡／銀月仙姬",
    themeHint: "滿月 星河 白紗 仙姬 月宮 透明披帛",
    aliases: ["銀月", "月宮仙姬", "白紗", "星河", "仙俠"],
    identity: "銀月星河月宮白紗仙姬",
    palette: "月白、銀藍、星光銀、淡紫與透明水晶光",
    costumeCore: "月白仙俠長裙、銀線刺繡、完整安全內襯、透明披帛與飄逸長袖",
    jewelry: "月形額飾、銀白髮簪、水晶耳墜、細銀手鏈與星石腰飾",
    prop: "星光靈珠、透明披帛與月宮石階",
    place: "滿月星河月宮露台",
    foreground: "星光靈珠、透明披帛、月白裙擺與銀色霧氣",
    midground: "真人仙姬站在月宮露台，滿月形成背後圓形構圖，臉部正面明亮",
    background: "巨大滿月、星河、雲霧、月宮欄杆與遠景銀樹",
    action: "人物雙手在身前托起星光但不遮胸口與五官，披帛向兩側飄開",
    lighting: "large moon backlight、silver-blue rim、soft fantasy facial fill、sparkle particles",
    atmosphere: "仙俠月宮封面，清冷夢幻，不做低俗仙女寫真",
  },
  {
    id: "style-ref-snow-fox-crystal-oracle",
    title: "雪狐晶林・冰紫靈狐聖女",
    parentCategory: "九尾妖狐",
    series: "風格範例轉卡／雪狐晶林",
    themeHint: "雪狐 冰晶 紫白花裙 靈狐 聖女 雪地",
    aliases: ["雪狐", "冰晶", "靈狐聖女", "紫白花裙", "雪地仙境"],
    identity: "雪狐晶林冰紫靈狐聖女",
    palette: "冰白、淡紫、雪藍、水晶銀與柔粉光",
    costumeCore: "淡紫白花瓣仙裙、完整安全內襯、雪紗披肩、銀線刺繡與柔軟拖尾",
    jewelry: "冰晶髮冠、白鑽耳墜、紫晶項鍊、銀色手鍊與雪花髮飾",
    prop: "巨型白狐、冰晶花枝與雪地燈火",
    place: "冰晶雪林靈狐秘境",
    foreground: "冰晶花、雪霧、裙擺、白狐尾影與冷色花瓣",
    midground: "真人靈狐聖女坐在雪地石座或低台上，白狐在身側守護，臉部看向鏡頭",
    background: "紫藍冰晶樹、雪夜燈火、巨型白狐身影與星光霧氣",
    action: "人物一手輕扶石座或裙擺，一手自然靠近白狐毛邊，沒有多餘杯具或硬道具",
    lighting: "icy violet key、white fox bounce、crystal sparkle highlights、soft snow diffusion",
    atmosphere: "雪狐仙境電影封面，柔美、靈氣、守護感強，避免寵物遮臉",
  },
  {
    id: "style-ref-blue-hanfu-courtyard-student",
    title: "書院藍裙・庭院古風少女",
    parentCategory: "中國歷代服裝／泛朝代總覽",
    series: "風格範例轉卡／書院庭院",
    themeHint: "古風庭院 藍裙 書院 木廊 陽光 坐姿",
    aliases: ["古風庭院", "藍裙", "書院", "木廊", "清雅少女"],
    identity: "書院藍裙庭院古風少女",
    palette: "深靛藍、天青、木棕、象牙白與庭院日光",
    costumeCore: "深藍短襖或對襟上衣、淺藍長裙、完整端莊內襯、繡花腰帶與柔軟披肩",
    jewelry: "素雅髮簪、小珍珠耳飾、藍色髮帶與細玉手鐲",
    prop: "書卷、木廊扶手與小型布包",
    place: "古風書院木廊庭院",
    foreground: "木地板、書卷、裙擺、庭院光斑與欄杆陰影",
    midground: "真人少女坐在木廊邊，身體微側，臉部正向鏡頭，姿態安靜自然",
    background: "木門窗、院落日光、石階、竹影與古宅牆面",
    action: "人物一手扶住木廊邊緣，一手自然放在書卷旁，不必手持茶盞",
    lighting: "clear courtyard sunlight、warm wood bounce、soft face fill、natural hanfu texture",
    atmosphere: "清雅古風書院生活感，乾淨、自然、有支撐點，不做過度舞台化姿勢",
  },
  {
    id: "style-ref-lilac-lake-terrace-consort",
    title: "櫻橋紫紗・湖畔倚欄寵姬",
    parentCategory: "中國歷代服裝／泛朝代總覽",
    series: "風格範例轉卡／櫻橋紫紗",
    themeHint: "湖畔 古風 紫紗 低欄 櫻花 水面 高開衩",
    aliases: ["櫻橋", "紫紗", "湖畔", "倚欄", "古風寵姬"],
    identity: "櫻橋紫紗湖畔倚欄寵姬",
    palette: "淡紫、櫻粉、湖水青、暖木棕與柔金",
    costumeCore: "淡紫薄紗古風禮裙、完整安全內襯、金線胸衣外層、長披帛與側開衩裙擺",
    jewelry: "粉晶髮簪、細金項鍊、紫晶耳墜、臂釧與腰鏈",
    prop: "櫻花枝、湖畔木欄與薄紗披帛",
    place: "櫻花湖畔木橋露台",
    foreground: "櫻花瓣、湖面反光、紫紗裙擺與木欄邊緣",
    midground: "真人寵姬倚靠湖畔欄杆，身體微側，臉部低頭微回眸但五官清楚",
    background: "櫻花樹、水面、木橋、亭台屋簷與柔焦春光",
    action: "人物一手扶木欄建立支撐點，一手自然整理披帛或裙擺，不需要酒杯或額外道具",
    lighting: "soft spring sunlight、lake reflection fill、pink blossom rim、sheer fabric highlights",
    atmosphere: "古風湖畔春日大片，保留紫紗與長腿線條但避免低俗視角",
  },
  {
    id: "style-ref-dream-garden-iridescent-feather-couture",
    title: "夢境花園・虹羽高訂花藝超模",
    parentCategory: "高訂婚紗禮服",
    series: "風格範例轉卡／夢境花園",
    themeHint: "夢境花園 虹彩羽毛 高訂禮服 巨型花藝 Vogue Italia Fine Art Fashion",
    aliases: ["夢境花園", "虹彩羽毛", "高訂禮服", "巨型花藝", "Fine Art Fashion"],
    identity: "夢境花園虹羽高訂花藝超模",
    palette: "薰衣草紫、玫瑰粉、丁香紫、冰藍、珍珠母貝虹彩與柔白光",
    costumeCore: "超高級奇幻羽毛高訂禮服、露肩無袖雕塑輪廓、完整安全內襯、水晶羽片胸衣外層、半透明虹彩羽毛層疊、天鵝羽翼與孔雀尾羽般展開的空氣感裙擺",
    jewelry: "羽毛水晶頭飾、透明水晶耳墜、細鑽手鍊、珍珠母貝戒指與柔亮髮飾",
    prop: "巨型花藝裝置、半透明花瓣、垂掛花束與水晶花枝",
    place: "薰衣草紫夢境花園精品攝影棚",
    foreground: "前景植物框景、虹彩羽毛邊緣、水晶花枝與柔焦花瓣",
    midground: "真人高訂超模位於畫面左側，微側身半隱於巨型花藝後方，禮服雕塑輪廓完整清楚",
    background: "薰衣草紫、玫瑰粉、丁香紫與冰藍花藝包覆整個空間，右側保留大片留白與柔和景深",
    action: "人物一手自然扶腰，一手輕觸花藝邊緣，眼神自信看向鏡頭，花藝不遮擋五官",
    lighting: "soft diffused fine-art fashion light、pearl iridescent feather highlights、premium editorial depth of field、clean beauty fill",
    atmosphere: "超寫實精品高訂時尚攝影與 Fine Art Fashion 花藝大片，華麗、夢幻、精緻，但保持真人可穿戴禮服結構",
  },
  {
    id: "style-ref-mist-amber-leopard-bedchamber-consort",
    title: "霧琥珀豹紋・宮榻寵妃",
    parentCategory: "寢宮寵妃系列",
    series: "寢宮寵妃系列／霧琥珀豹紋",
    themeHint: "霧琥珀 豹紋宮廷刺繡 古風寵妃 宮廷床榻 貓系側躺",
    aliases: ["霧琥珀", "豹系寵妃", "豹紋宮廷刺繡", "貓系側躺", "宮廷床榻"],
    identity: "霧琥珀豹紋宮榻寵妃",
    palette: "霧琥珀、黑棕、冷白、古金、柔雪紗與暖燭光",
    costumeCore: "古風宮廷寵妃造型、輕透雪紡與薄紗多層疊穿、完整安全內襯、金線刺繡抽象豹紋、豹形符號以宮廷刺繡與飾品點綴，避免現代印花與俗氣大面積圖案",
    jewelry: "金色古風繁複頭飾、豹眼寶石意象、豹紋徽記、流蘇金鏈、琥珀耳墜與細金臂飾",
    prop: "豹眼寶石香盒、金線床帳、薄紗床幔與暖金燭台作背景光源",
    place: "霧琥珀古風宮廷床榻",
    foreground: "薄紗床幔、豹眼寶石香盒、雪紡裙擺、金線刺繡床帳與暖燭光暈",
    midground: "真人寵妃在床榻上採貓系側躺姿態，上半身微轉，頭部微抬，臉部正面清楚看向鏡頭",
    background: "金線刺繡床帳、薄紗垂落、暖金燭光、柔陰影、紅木寢榻與私密高級宮廷氛圍",
    action: "人物雙手輕撐床緣支撐身體，身體形成柔軟 S 曲線，慵懶但克制，手指比例自然且不遮臉",
    lighting: "mist amber candle key、cool white skin fill、soft bedchamber shadows、gold embroidery sparkle、realistic chiffon translucency",
    atmosphere: "高級時尚寫真式古風寵妃，霧琥珀凝視與豹紋宮廷刺繡是記憶點，克制性感但不挑逗",
  },
  {
    id: "style-ref-republic-teahouse-peony-qipao",
    title: "民國茶館・米金牡丹旗袍美人",
    parentCategory: "東方旗袍夜宴",
    series: "風格範例轉卡／民國茶館旗袍",
    themeHint: "民國復古 旗袍美人 懷舊茶館 米金牡丹刺繡 夕陽窗光",
    aliases: ["民國茶館", "米金旗袍", "牡丹刺繡", "懷舊茶館", "復古旗袍"],
    identity: "民國茶館米金牡丹旗袍美人",
    palette: "米金、牡丹紅、暖夕陽、檀木棕、古銅與柔和膚光",
    costumeCore: "米金色緞面中國風修身旗袍、紅色滾邊、牡丹花刺繡、完整安全內襯、貼身但端莊的剪裁與優雅側開衩",
    jewelry: "復古盤髮、自然碎髮、空氣感瀏海、中式髮簪、流蘇耳環、珠花髮飾與細金手鍊",
    prop: "古銅茶壺、茶杯、雕花木椅、繡花桌布與圓形牡丹屏風",
    place: "中國懷舊復古茶館窗邊",
    foreground: "木製茶桌、古銅茶壺、茶杯、繡花桌布與旗袍緞面反光",
    midground: "真人旗袍美人坐在茶館窗邊，姿態溫柔微側，臉部明亮，旗袍刺繡清楚",
    background: "木窗花、紅色燈籠、書法掛軸、圓形牡丹屏風、江南古鎮式灰瓦屋簷與柔和散景",
    action: "人物一手自然扶住木桌邊緣，一手靠近茶杯但不遮五官，甜美微笑看向鏡頭",
    lighting: "warm sunset window backlight、soft golden rim light、teahouse wood bounce、qipao embroidery highlights、shallow depth of field",
    atmosphere: "中國復古民國風旗袍電影寫真，溫柔、精緻、高級，茶具合理入鏡但不喧賓奪主",
  },
  {
    id: "style-ref-republic-koi-corridor-qipao",
    title: "錦鯉水廊・米金牡丹旗袍旅人",
    parentCategory: "東方旗袍夜宴",
    series: "風格範例轉卡／錦鯉水廊旗袍",
    themeHint: "民國旗袍 木造走廊 池水 巨大錦鯉 紅燈籠 夕陽暖光",
    aliases: ["錦鯉水廊", "米金旗袍", "紅白錦鯉", "中式木廊", "復古庭院"],
    identity: "錦鯉水廊米金牡丹旗袍旅人",
    palette: "米金、牡丹紅、錦鯉白紅、池水青、檀木棕與夕陽金",
    costumeCore: "米金色牡丹刺繡中國風旗袍、紅色滾邊、完整安全內襯、緞面貼身剪裁、優雅側開衩與復古高跟鞋",
    jewelry: "復古盤髮、中式髮簪、珠花髮飾、流蘇耳環、細金手鍊與小型珍珠戒指",
    prop: "木造走廊欄杆、古銅茶壺、紅燈籠倒影與池水中的巨大紅白錦鯉",
    place: "復古中式木造走廊與錦鯉池",
    foreground: "木欄杆、池水波光、紅燈籠倒影、錦鯉魚背與旗袍裙擺",
    midground: "真人旗袍旅人站在木造走廊上，身體微側，低頭凝視池水，臉部仍保留明亮側面輪廓",
    background: "雕花木欄、茶壺、古典屏風、灰瓦屋簷、紅燈籠與中式庭院建築",
    action: "人物一手扶住木欄杆形成支撐點，一手自然整理旗袍裙側，視線落向水中錦鯉，姿態優雅穩定",
    lighting: "warm sunset corridor light、water ripple reflections、red lantern bounce、qipao satin highlights、cinematic shallow depth of field",
    atmosphere: "復古中國風水廊海報，浪漫、夢幻、電影感強，錦鯉與水面反光服務人物情緒與構圖",
  },
  {
    id: "style-ref-morning-private-suite-heiress",
    title: "晨光私宅・淡紫都會名媛",
    parentCategory: "現代都市 / 街拍電影",
    series: "風格範例轉卡／私宅名媛",
    themeHint: "淡紫上衣 白裙 私宅 大面窗光 極簡室內",
    aliases: ["淡紫", "私宅", "白裙", "大面窗光", "都會名媛"],
    identity: "晨光私宅淡紫都會名媛",
    palette: "淡紫、象牙白、米金與淺木色",
    costumeCore: "淡紫交疊針織上衣、象牙白高腰短裙或及膝裙、米白短外套與細帶高跟鞋，保持現代時尚雜誌感",
    jewelry: "小珍珠耳釘、細金手鍊、白色小手包與簡約髮夾",
    prop: "白色小手包與花瓶旁的邀請卡",
    place: "晨光灑入的現代私宅客廳",
    foreground: "邀請卡、白色手包、大理石地面反光與沙發扶手",
    midground: "真人名媛站在窗邊或沙發旁，姿態端正自然",
    background: "白牆線板、米白沙發、花瓶、落地窗與斜切日光",
    action: "人物一手低提手包，一手自然整理袖口，雙腳重心穩定",
    lighting: "clear morning window light、cream wall bounce、soft marble reflections",
  },
  {
    id: "style-ref-liquid-chrome-cyber-curator",
    title: "液態銀環・未來展廳指揮官",
    parentCategory: "賽博機甲 / 科幻戰姬",
    series: "風格範例轉卡／液態銀科幻戰姬",
    themeHint: "銀色金屬 透明管線 科幻展廳 冷藍高光",
    aliases: ["液態銀", "透明管線", "未來展廳", "chrome fashion"],
    identity: "液態銀環未來展廳指揮官",
    palette: "鏡面銀、冰藍、透明玻璃與冷白色",
    costumeCore: "鏡面銀短外套、銀色機能長裙或長褲、透明防護披層與高領軟甲內搭，保留 chrome 反光但避免低角度性感構圖",
    jewelry: "透明耳機模組、銀色耳扣、光學頸環與手腕控制器",
    prop: "透明控制環與液態金屬資料板",
    place: "冷白玻璃未來展廳",
    foreground: "透明控制環、玻璃反射與銀色地面光帶",
    midground: "真人指揮官站在展廳中心，身體完整入鏡",
    background: "冰藍玻璃柱、反射牆、漂浮透明管線與冷色城市剪影",
    action: "人物一手操作透明控制環，一手低持資料板，正面或微側正面看向鏡頭",
    lighting: "clinical white key、icy blue rim light、chrome specular highlights",
    atmosphere: "未來時裝電影主視覺，避免腿部、胸腰或低角度成為主視覺",
  },
  {
    id: "style-ref-sunset-bay-white-shirt-traveler",
    title: "落日海灣・白衫旅人",
    parentCategory: "世界景點旅拍",
    series: "風格範例轉卡／落日海灣",
    themeHint: "海邊夕陽 白色休閒造型 橙金海面 自然笑容",
    aliases: ["海邊", "夕陽", "白衫", "度假旅拍", "水面反光"],
    identity: "落日海灣白衫旅人",
    palette: "夕陽橙、海水金、白色與柔沙色",
    costumeCore: "白色棉質背心或短袖襯衫、白色高腰短褲或輕便長裙、薄防曬外衫與度假涼鞋",
    jewelry: "貝殼耳飾、細金手鍊、草編髮繩與小項鍊",
    prop: "草編帽與小型防水相機",
    place: "落日海灣淺灘",
    foreground: "浪花、水珠、草編帽與濕沙反光",
    midground: "真人旅人站在淺灘邊，笑容自然，肩頸與白色造型清楚",
    background: "橙金夕陽、海面光路、遠方島影與柔焦浪線",
    action: "人物一手低持相機，一手自然扶住被海風吹動的外衫",
    lighting: "golden sunset backlight、warm facial fill、ocean sparkle reflections",
  },
  {
    id: "style-ref-peach-pavilion-tang-court-lady",
    title: "桃花宮苑・粉金盛唐宮姬",
    parentCategory: "中國歷代服裝",
    series: "風格範例轉卡／盛唐花苑",
    themeHint: "粉金唐風 高髻花冠 珍珠流蘇 宮苑花亭",
    aliases: ["盛唐", "桃花", "宮苑", "粉金", "珍珠流蘇"],
    identity: "桃花宮苑粉金盛唐宮姬",
    palette: "桃粉、米金、珍珠白與柔水綠",
    costumeCore: "粉金齊胸襦裙、透明繡花外衫、寬袖披帛與真絲多層垂墜",
    jewelry: "高髻花冠、珍珠流蘇步搖、金色額飾、玉佩與細金腰飾",
    prop: "桃花枝與小型香囊",
    place: "盛唐宮苑桃花花亭",
    foreground: "桃花枝、薄紗袖口、宮苑石欄與花影柔光",
    midground: "真人宮姬坐於花亭石欄旁或站在花影中景",
    background: "園林池水、太湖石、桃花樹與柔焦亭台",
    action: "人物一手低持桃花枝，一手自然扶袖，臉部正面清楚",
    lighting: "warm garden key light、water reflection fill、pearl and embroidery highlights",
  },
  {
    id: "style-ref-blooming-garden-bridal-queen",
    title: "繁花秘園・皇冠花嫁",
    parentCategory: "高訂婚紗禮服",
    series: "風格範例轉卡／花園花嫁",
    themeHint: "花園婚紗 皇冠 頭紗 花束 粉紫花廊 夕陽逆光",
    aliases: ["花嫁", "皇冠", "頭紗", "花束", "粉紫花廊"],
    identity: "繁花秘園皇冠花嫁",
    palette: "薔薇粉、薰衣草紫、嫩葉綠、象牙白與夕陽金",
    costumeCore: "粉紫花朵刺繡婚紗、象牙白安全內襯、透明花瓣披紗、長拖尾與柔軟花園裙擺",
    jewelry: "細鑽皇冠、珍珠耳墜、花瓣手鏈與白金項鍊",
    prop: "粉紫玫瑰花束與絲帶",
    place: "夕陽繁花秘園石階花廊",
    foreground: "花束、飄落花瓣、石階與透明拖尾",
    midground: "真人花嫁站在花廊中央，全身輪廓完整",
    background: "粉紫花牆、樹影、遠景石階與夕陽光球",
    action: "人物雙手抱花束低於胸口，頭紗和披紗受微風帶起但不遮臉",
    lighting: "golden garden backlight、soft bridal facial fill、sparkle veil highlights",
    atmosphere: "花園童話婚紗電影主視覺，禁止畫面文字與過度透明焦點",
  },
  {
    id: "style-ref-dunhuang-golden-crown-feitian",
    title: "敦煌金冠・碧紗飛天舞姬",
    parentCategory: "敦煌飛天",
    series: "風格範例轉卡／敦煌飛天",
    themeHint: "敦煌 飛天 金冠 綠松石 橙青披帛 壁畫佛龕",
    aliases: ["敦煌", "飛天", "壁畫", "綠松石", "金冠"],
    identity: "敦煌金冠碧紗飛天舞姬",
    palette: "沙金、孔雀青、蜜桃橙與壁畫赭色",
    costumeCore: "敦煌飛天舞衣、碧色與橙色長披帛、金線胸衣外層與透明但有安全內襯的舞用長裙",
    jewelry: "金冠、綠松石耳飾、額飾、臂釧、金鏈腰飾與流蘇步搖",
    prop: "長披帛與小型金鈴",
    place: "敦煌壁畫佛龕舞台",
    foreground: "橙青披帛、金鈴、塵光與壁畫色塊",
    midground: "真人飛天舞姬在佛龕前舞動，臉部正面或微側正面清楚",
    background: "敦煌壁畫佛像、古老洞窟紋樣、金色浮塵與暖暗牆面",
    action: "人物雙臂舞動長披帛，手部遠離臉部，舞姿有真實重心",
    lighting: "warm cave skylight、gold dust glow、turquoise jewelry catchlight",
  },
  {
    id: "style-ref-red-moon-nine-tail-fox-queen",
    title: "紅月狐火・九尾花海妖后",
    parentCategory: "九尾妖狐",
    series: "風格範例轉卡／紅月九尾",
    themeHint: "紅月 九尾狐后 白狐巨獸 彼岸花 暗黑東方神話",
    aliases: ["九尾狐", "紅月", "白狐", "彼岸花", "狐火"],
    identity: "紅月狐火九尾花海妖后",
    palette: "血紅、月黑、雪白狐毛與暗紫夜色",
    costumeCore: "深紅花瓣刺繡長裙、黑紅披紗、完整安全內襯與巨大拖尾，形成暗黑東方神話女王輪廓",
    jewelry: "紅晶花冠、細金額飾、黑紅耳墜與狐火紋腰飾",
    prop: "紅晶花枝與狐火符紋",
    place: "紅月廢城彼岸花海",
    foreground: "彼岸花、紅色花瓣、狐火線條與裙擺拖尾",
    midground: "真人妖后站在白狐守護獸旁，姿態端正有壓迫感",
    background: "紅月、廢城剪影、巨大白狐幻影與暗紫夜雲",
    action: "人物一手低持紅晶花枝，一手自然垂落，白狐在身側守護",
    lighting: "red moon backlight、cool facial fill、white fur rim light and crimson haze",
    atmosphere: "暗黑東方神話電影主視覺，不做遊戲 boss 化或低俗女王造型",
  },
  {
    id: "style-ref-amber-rock-occult-countess",
    title: "岩金密紋・琥珀長袍女爵",
    parentCategory: "西方古典 / 歐陸史詩",
    series: "風格範例轉卡／黑金岩紋",
    themeHint: "黑金 岩紋 琥珀光 長袍 室內沙發 歐式密教",
    aliases: ["黑金", "岩紋", "琥珀", "密教", "歐式室內"],
    identity: "岩金密紋琥珀長袍女爵",
    palette: "岩石黑、琥珀金、茶棕與暗銅色",
    costumeCore: "黑金幾何刺繡長袍、琥珀色真絲內搭、高領披肩與完整長裙結構，取代原參考的內衣商品感",
    jewelry: "幾何金屬項鍊、琥珀耳墜、黑金腰鏈與古銅戒指",
    prop: "岩紋手札與琥珀酒杯",
    place: "暖暗歐式書房皮革沙發旁",
    foreground: "手札、酒杯、皮革扶手與黑金披紗",
    midground: "真人女爵站在沙發前或端坐椅側，長袍完整覆蓋身體輪廓",
    background: "木質書房、窗簾逆光、暗金壁燈與古典地毯",
    action: "人物一手低持手札，一手扶住長袍披肩，微側正面看鏡頭",
    lighting: "warm amber window beam、leather bounce、subtle gold embroidery highlights",
    atmosphere: "安全黑金高訂密教電影主視覺，不保留內衣、商品文字或性感商品頁構圖",
  },
  {
    id: "style-ref-waterfall-green-gauze-nymph",
    title: "幽潭瀑影・青衣水仙",
    parentCategory: "花園童話 / 自然精靈",
    series: "風格範例轉卡／幽潭水仙",
    themeHint: "瀑布 水潭 青紗 森林 冷色水光",
    aliases: ["瀑布", "青紗", "水仙", "幽潭", "森林"],
    identity: "幽潭瀑影青衣水仙",
    palette: "冷青綠、霧白、水石灰與深林黑",
    costumeCore: "青綠古風長裙、半透明外紗、濕潤質感披帛與完整內層襯裙，保持神話水仙氣質",
    jewelry: "青玉髮簪、水滴耳飾、細銀臂環與小玉佩",
    prop: "青玉水盞與水草花枝",
    place: "森林瀑布幽潭石岸",
    foreground: "潭水漣漪、濕石、水草與青紗袖口",
    midground: "真人水仙坐在石岸或半跪於水邊，身體支撐點合理",
    background: "瀑布、深林岩壁、冷色水霧與水面高光",
    action: "人物一手扶石岸，一手低持水盞，臉部抬起看向鏡頭",
    lighting: "cool waterfall skylight、water reflection fill、misty rim light",
    atmosphere: "幽潭神話電影主視覺，避免濕身性感化",
  },
  {
    id: "style-ref-pink-pet-clinic-nurse",
    title: "甜粉診療所・貓耳看護",
    parentCategory: "現代都市 / 街拍電影",
    series: "風格範例轉卡／甜粉看護",
    themeHint: "粉白制服 貓耳 看護 蝴蝶結 寵物診療所",
    aliases: ["粉白", "貓耳", "看護", "蝴蝶結", "寵物診療"],
    identity: "甜粉診療所貓耳看護",
    palette: "嫩粉、純白、櫻花粉與柔灰色",
    costumeCore: "粉白短袖看護制服、圓領安全內搭、愛心腰帶、蝴蝶結圍裙與膝上制服裙，呈現可愛制服而非情趣化 cosplay",
    jewelry: "粉色髮夾、愛心項圈式頸飾、名牌、白色短手套與小耳釘",
    prop: "愛心聽診器與病歷夾",
    place: "明亮寵物診療所接待區",
    foreground: "病歷夾、聽診器、粉白櫃台與小型醫療器具",
    midground: "真人看護站在接待櫃台旁，制服輪廓端正",
    background: "白色診間門、粉色標示牌、玻璃藥櫃與柔和燈箱",
    action: "人物一手低持病歷夾，一手自然扶櫃台，貓耳髮飾不遮臉",
    lighting: "bright studio clinic light、soft pink bounce、clean fabric highlights",
    atmosphere: "可愛寵物診療電影角色卡，不做商品頁文字排版或低俗制服化",
  },
  {
    id: "style-ref-blue-sleeve-spring-forest-lady",
    title: "春林藍袖・古風花影仕女",
    parentCategory: "中國歷代服裝",
    series: "風格範例轉卡／藍袖花林",
    themeHint: "寶藍漢服 金繡 林間 花瓣 暖色樹影",
    aliases: ["寶藍漢服", "春林", "花瓣", "金繡", "古風仕女"],
    identity: "春林藍袖古風花影仕女",
    palette: "寶藍、象牙白、金繡色與森林綠",
    costumeCore: "寶藍交領古風長衫、白色內裙、金色花紋刺繡與寬幅透明長袖",
    jewelry: "珍珠金簪、白玉耳飾、細金髮扣與小玉佩",
    prop: "白花枝與藍色披帛",
    place: "春日林間花瓣小徑",
    foreground: "花瓣、藍袖披帛、樹根與柔焦葉影",
    midground: "真人仕女站在老樹旁，抬手整理長袖但不遮臉",
    background: "老樹、暖色穿林光、落花與淡霧小徑",
    action: "人物一手低持花枝，一手牽起長袖，目光微仰或看向鏡頭",
    lighting: "warm forest shaft light、green leaf bounce、blue silk highlights",
  },
  {
    id: "style-ref-blue-core-cyber-guardian",
    title: "藍核義體・戰術守衛",
    parentCategory: "賽博機甲 / 科幻戰姬",
    series: "風格範例轉卡／藍核義體戰姬",
    themeHint: "賽博 義體 藍色能量核心 短髮 戰損塗裝",
    aliases: ["賽博", "義體", "藍核", "戰術守衛", "短髮"],
    identity: "藍核義體戰術守衛",
    palette: "冷白、電光藍、金屬黑與微量警示紅",
    costumeCore: "白色戰術外套、黑色機械義體肩臂、藍色能量核心、完整防護胸甲與機能長褲，改寫為非暴露戰術造型",
    jewelry: "藍光耳機、三角晶體耳飾、金屬頸環與資料腕扣",
    prop: "短刀鞘與維修資料晶片",
    place: "雨後賽博城市維修通道",
    foreground: "資料晶片、藍光電纜、雨滴與金屬欄杆",
    midground: "真人守衛站在維修通道中景，義體肩臂與藍核清楚",
    background: "冷色柱光、濕地反射、維修機械臂與城市光點",
    action: "人物一手低持晶片，一手自然扶住外套領口，短刀只作為腰側道具",
    lighting: "blue energy key light、pink rim light、rainy metal reflections",
    atmosphere: "戰損賽博電影主視覺，使用塗裝與刮痕取代血腥，避免暴露或繃帶性感化",
  },
  {
    id: "style-ref-forest-ritual-blue-hanbok-dancer",
    title: "林間祭舞・藍白韓服舞者",
    parentCategory: "東方和風旅拍",
    series: "風格範例轉卡／藍白韓服",
    themeHint: "藍白韓服 林間祭儀 長袖飄帶 暖色樹影",
    aliases: ["韓服", "藍白", "林間祭舞", "長袖", "暖色樹影"],
    identity: "林間祭舞藍白韓服舞者",
    palette: "深海藍、象牙白、霧金與森林綠",
    costumeCore: "深藍短襦、白色高腰長裙、銀白刺繡、柔紗長袖飄帶與傳統韓服腰線",
    jewelry: "珍珠髮簪、銀色耳墜、細金髮扣與繡花髮帶",
    prop: "白色長袖飄帶與小陶瓶",
    place: "晨霧林間祭儀石案前",
    foreground: "飄帶、花瓣、陶瓶與石案邊緣",
    midground: "真人舞者在林間張開長袖，臉部正面可辨識",
    background: "老樹、彩色祭帶、柔霧、晨光與林間小徑",
    action: "人物雙臂展開長袖飄帶，手臂遠離臉部，舞姿保持真實重心",
    lighting: "warm forest morning light、soft haze、blue fabric sheen",
  },
  {
    id: "style-ref-sapphire-clockwork-queen-knight",
    title: "星藍齒輪・王庭女騎士",
    parentCategory: "賽博機甲 / 科幻戰姬",
    series: "風格範例轉卡／齒輪王庭機械王國",
    themeHint: "藍金機械王國 鐘塔 齒輪權杖 銀藍重甲 蒸汽",
    aliases: ["齒輪", "鐘塔", "女騎士", "藍金盔甲", "蒸汽王庭"],
    identity: "星藍齒輪王庭女騎士",
    palette: "寶石藍、鈦銀、古金與雲白色",
    costumeCore: "寶石藍與鈦銀全身裙甲、機械肩甲、長裙甲片、護臂、護腿與可穿戴胸甲結構",
    jewelry: "藍寶石頸飾、齒輪髮扣、金屬耳飾與騎士徽章",
    prop: "藍寶石齒輪權杖與機械盾扣",
    place: "蒸汽鐘塔王庭廣場",
    foreground: "權杖、金屬地面、齒輪紋與蒸汽薄霧",
    midground: "真人女騎士站在王庭廣場中央，全身盔甲完整入鏡",
    background: "巨大鐘塔、藍金穹頂、蒸汽管線、飛行機械與晴空雲層",
    action: "人物一手持權杖垂直落地，一手自然扶住護臂，正面凝視鏡頭",
    lighting: "bright royal daylight、blue gemstone glow、polished armor highlights",
  },
  {
    id: "style-ref-pink-cat-ear-clinic-assistant",
    title: "粉白貓耳・診療助理",
    parentCategory: "現代都市 / 街拍電影",
    series: "風格範例轉卡／粉白診療助理",
    themeHint: "粉白貓耳 看護制服 棚拍 蝴蝶結 心形飾件",
    aliases: ["粉白貓耳", "診療助理", "蝴蝶結", "心形飾件", "棚拍"],
    identity: "粉白貓耳診療助理",
    palette: "純白、櫻花粉、黑色髮飾與柔膚粉",
    costumeCore: "粉白短袖制服、白色安全內搭、蓬袖、蝴蝶結腰封與端正制服裙",
    jewelry: "貓耳髮箍、粉色蝴蝶結髮夾、心形頸飾、名牌與小耳釘",
    prop: "粉色筆型手電與小型病歷牌",
    place: "乾淨白棚寵物診療形象照場景",
    foreground: "病歷牌、粉色筆燈與白色櫃台",
    midground: "真人助理站在白棚或診療櫃台旁，臉部明亮清楚",
    background: "純白背景、柔和粉色燈帶、簡潔診療道具與乾淨地面",
    action: "人物一手低持病歷牌，一手自然放在櫃台邊，姿態端正",
    lighting: "clean white studio key、soft pink fill、gentle fabric highlights",
    atmosphere: "可愛制服電影角色卡，不做低俗制服、胸部特寫或商品頁文字",
  },
  {
    id: "style-ref-bangkok-golden-temple-traveler",
    title: "曼谷金殿・紅白旅人",
    parentCategory: "世界地標旅拍",
    series: "風格範例轉卡／曼谷金殿",
    themeHint: "泰國王宮 金色寺院 彩瓷欄杆 紅白現代套裝 日光",
    aliases: ["曼谷", "金殿", "泰國王宮", "紅白", "彩瓷"],
    identity: "曼谷金殿紅白旅人",
    palette: "朱紅、純白、寺院金與琺瑯藍綠",
    costumeCore: "紅白現代度假套裝、白色高腰裙或長褲、輕薄披肩與金色細節，符合寺院旅拍端正穿著",
    jewelry: "金色耳圈、細金手鍊、紅色絲巾扣與小型旅行胸針",
    prop: "旅行票卡與紅色絲巾",
    place: "曼谷金色寺院彩瓷欄杆旁",
    foreground: "旅行票卡、彩瓷欄杆、石階與紅色絲巾",
    midground: "真人旅人站在寺院欄杆側前方，服裝端正明亮",
    background: "金色佛塔、泰式屋簷、鑲嵌牆面與晴朗日光",
    action: "人物一手低持票卡，一手扶住絲巾或欄杆，微側正面看鏡頭",
    lighting: "bright Bangkok daylight、gold temple reflection、clean facial fill",
    atmosphere: "世界地標旅拍主視覺，不保留浮水印或畫面文字",
  },
  {
    id: "style-ref-wisteria-spring-courtyard-lady",
    title: "紫藤春庭・淡紫花姬",
    parentCategory: "中國歷代服裝",
    series: "風格範例轉卡／紫藤春庭",
    themeHint: "淡紫古風 花枝 白花背景 柔和日光",
    aliases: ["紫藤", "淡紫", "花姬", "春庭", "古風"],
    identity: "紫藤春庭淡紫花姬",
    palette: "淡紫、月白、花蕊黃與柔葉綠",
    costumeCore: "淡紫古風襦裙、白色內衫、繡花半透明外袍與柔軟長袖",
    jewelry: "紫花髮簪、珍珠流蘇、細銀耳飾與淺紫腰佩",
    prop: "紫藤花枝與小摺扇",
    place: "春日白花庭院",
    foreground: "紫藤花枝、白色花叢、袖口與柔焦花瓣",
    midground: "真人花姬站在花叢側前方，手持花枝",
    background: "白色花樹、庭院綠影、柔和日光與遠景小徑",
    action: "人物一手持紫藤花枝，一手自然扶袖，安靜看向鏡頭",
    lighting: "soft spring daylight、white flower bounce、lavender fabric highlights",
  },
  {
    id: "style-ref-flower-room-fairy-gardener",
    title: "花房瓶花・精靈園藝師",
    parentCategory: "花園童話 / 自然精靈",
    series: "風格範例轉卡／花房精靈",
    themeHint: "花房 瓶花 白色蕾絲 彩翼精靈 窗邊暖光",
    aliases: ["花房", "精靈", "瓶花", "白色蕾絲", "窗邊"],
    identity: "花房瓶花精靈園藝師",
    palette: "奶油白、玫瑰粉、雛菊黃、葉綠與暖木色",
    costumeCore: "奶油白蕾絲長裙、薄紗袖、柔軟園藝圍裙與花瓣刺繡披肩",
    jewelry: "小花髮簪、珍珠耳飾、細金戒指與花葉手鏈",
    prop: "白色花瓶、園藝剪與粉色小花束",
    place: "午後花房木桌旁",
    foreground: "白色花瓶、園藝剪、雛菊、玫瑰與木桌紋理",
    midground: "真人園藝師坐或站在花桌旁，臉部明亮清楚",
    background: "花房窗戶、木架、盆栽、暖光與淡淡彩翼精靈光點",
    action: "人物一手整理瓶花，一手低持園藝剪，遠景小精靈只作為柔焦光點環繞",
    lighting: "warm greenhouse window light、flower color bounce、soft fairy sparkle",
    atmosphere: "真人花房童話電影主視覺，避免卡通化與插畫感",
  },
  {
    id: "style-ref-white-peony-qipao-club-lady",
    title: "牡丹白緞・會館旗袍名媛",
    parentCategory: "現代都市 / 街拍電影",
    series: "風格範例轉卡／白緞旗袍會館",
    themeHint: "白色牡丹刺繡旗袍 大理石階 暖壁燈 會館室內",
    aliases: ["白旗袍", "牡丹刺繡", "會館", "大理石階", "暖壁燈"],
    identity: "牡丹白緞會館旗袍名媛",
    palette: "珍珠白、牡丹粉、孔雀藍、暖金與大理石灰",
    costumeCore: "白色緞面旗袍、牡丹與小鳥刺繡、短袖立領、及膝或長版安全剪裁與細緻盤扣",
    jewelry: "珍珠耳飾、白色細帶鞋、玉戒與小型金色髮夾",
    prop: "牡丹刺繡手包與會館請柬",
    place: "暖金會館大理石階旁",
    foreground: "請柬、手包、大理石階面與壁燈反光",
    midground: "真人名媛站在階梯側前方或端坐階邊，構圖不以腿部為主視覺",
    background: "白金牆面線板、暖壁燈、深色木門與米色沙發",
    action: "人物一手低持請柬，一手自然扶住手包，姿態端莊",
    lighting: "warm club wall light、marble bounce、white satin highlights",
  },
  {
    id: "style-ref-crimson-peony-evening-countess",
    title: "酒紅牡丹・晚宴花園女爵",
    parentCategory: "高訂婚紗禮服",
    series: "風格範例轉卡／酒紅牡丹",
    themeHint: "酒紅禮服 大型牡丹 石座 暗暖棚景 花瓣",
    aliases: ["酒紅", "牡丹", "晚宴禮服", "花園棚景", "女爵"],
    identity: "酒紅牡丹晚宴花園女爵",
    palette: "酒紅、深牡丹紅、煙玫瑰、石灰灰與柔金",
    costumeCore: "酒紅絲緞晚禮服、花瓣式披肩、完整安全內襯、長裙擺與克制高訂晚宴輪廓",
    jewelry: "紅寶耳墜、細金手鐲、玫瑰金髮夾與小型寶石項鍊",
    prop: "深紅牡丹花枝與絲緞手包",
    place: "暗暖牡丹花園石座旁",
    foreground: "大型牡丹、花瓣、石座邊緣與酒紅裙擺",
    midground: "真人女爵站在石座旁或端正倚坐，禮服輪廓完整",
    background: "暗色花牆、粉紅牡丹、暖色聚光與柔焦枝葉",
    action: "人物一手低持牡丹花枝，一手扶住石座或手包，眼神平靜看向鏡頭",
    lighting: "warm floral studio key、crimson petal bounce、soft gold rim light",
    atmosphere: "酒紅花園晚宴電影主視覺，避免性感坐姿或身體特寫",
  },
  {
    id: "style-ref-indoor-window-knit-lifestyle",
    title: "窗邊針織・午后生活寫真",
    parentCategory: "室內生活寫真",
    series: "風格範例轉卡／室內生活補強",
    themeHint: "窗邊 沙發 針織衫 午后柔光 生活寫真",
    aliases: ["窗邊", "針織", "沙發", "午后", "生活寫真"],
    identity: "窗邊針織午后生活女子",
    palette: "雲白、燕麥灰、鼠尾草綠、暖木色與柔金",
    costumeCore: "柔軟針織開衫、白色棉質上衣、寬版長裙或長褲與居家寫真安全層次",
    jewelry: "細金耳扣、簡約戒指、棉麻髮帶與小珍珠項鍊",
    prop: "陶瓷馬克杯與攤開的生活雜誌",
    place: "午後窗邊布沙發旁",
    foreground: "馬克杯、雜誌、木質茶几與柔軟毯面",
    midground: "真人女子坐在窗邊沙發或側身站立，臉部被自然光清楚照亮",
    background: "白紗窗簾、室內綠植、木書架與溫暖牆面",
    action: "人物雙手自然捧杯或整理雜誌，姿態鬆弛但端正",
    lighting: "soft afternoon window light、warm wood bounce、gentle indoor fill",
    atmosphere: "室內生活寫真電影感，避免凌亂臥室與身體特寫",
  },
  {
    id: "style-ref-indoor-bookstore-cardigan-reader",
    title: "書牆暖燈・開襟衫閱讀者",
    parentCategory: "室內生活寫真",
    series: "風格範例轉卡／室內生活補強",
    themeHint: "書牆 暖燈 開襟衫 閱讀 木地板",
    aliases: ["書牆", "閱讀", "開襟衫", "暖燈", "木地板"],
    identity: "書牆暖燈開襟衫閱讀者",
    palette: "深綠、奶茶棕、紙頁米白、胡桃木與暖銅",
    costumeCore: "深綠開襟衫、米白襯衫、長版格紋裙或直筒長褲與舒適室內層次",
    jewelry: "小型圓框眼鏡、細金手錶、珍珠耳釘與皮革書籤",
    prop: "精裝書、書籤與小型桌燈",
    place: "暖燈書牆閱讀角",
    foreground: "翻開的書頁、桌燈、木桌紋理與書籤",
    midground: "真人閱讀者站在書牆前或坐在扶手椅上，視線從書頁抬向鏡頭",
    background: "滿牆書架、壁燈、木地板與安靜室內深景",
    action: "人物一手托書，一手輕扶書頁，動作自然不遮臉",
    lighting: "warm reading lamp key、book page bounce、soft indoor rim light",
    atmosphere: "安靜書房生活寫真主視覺，避免商業棚拍過度誇張",
  },
  {
    id: "style-ref-indoor-kitchen-apron-tea-hostess",
    title: "暖廚茶光・圍裙生活女主",
    parentCategory: "室內生活寫真",
    series: "風格範例轉卡／室內生活補強",
    themeHint: "暖廚 木桌 圍裙 茶壺 窗光 生活寫真",
    aliases: ["暖廚", "圍裙", "茶壺", "木桌", "窗光"],
    identity: "暖廚茶光圍裙生活女主",
    palette: "奶油白、鼠尾草綠、蜂蜜黃、暖木與陶土紅",
    costumeCore: "棉麻長袖洋裝、柔軟圍裙、低飽和色繫帶與自然生活感層次",
    jewelry: "簡約耳釘、棉麻髮帶、細戒與小型吊墜",
    prop: "陶瓷茶壺、玻璃杯與一束小野花",
    place: "暖色木作家庭廚房",
    foreground: "茶壺、杯盤、木桌、花束與窗光反射",
    midground: "真人女主站在料理台旁，手部整理茶杯或小花束",
    background: "開放式木櫃、白色磁磚、綠植與柔和窗簾",
    action: "人物一手扶茶壺，一手整理杯盤，面部保持自然微笑",
    lighting: "morning kitchen window light、warm ceramic bounce、soft home fill",
    atmosphere: "乾淨溫暖的室內生活寫真，避免凌亂廚房與過度擺拍",
  },
  {
    id: "style-ref-bridal-crystal-staircase-gown",
    title: "水晶階廳・緞面花嫁",
    parentCategory: "高訂婚紗禮服",
    series: "風格範例轉卡／高訂婚紗補強",
    themeHint: "水晶階梯 緞面婚紗 長頭紗 香檳金 大廳",
    aliases: ["水晶階梯", "緞面婚紗", "長頭紗", "香檳金", "大廳"],
    identity: "水晶階廳緞面花嫁",
    palette: "象牙白、香檳金、水晶銀、霧玫瑰與大理石灰",
    costumeCore: "象牙白緞面高訂婚紗、立體胸衣外層、完整安全內襯、長拖尾與輕盈頭紗",
    jewelry: "水晶耳墜、細鑽項鍊、珍珠髮針與白金戒指",
    prop: "白玫瑰小捧花與緞面手套",
    place: "水晶吊燈大理石階廳",
    foreground: "白玫瑰、緞面拖尾、大理石階面與水晶反光",
    midground: "真人花嫁站在階梯轉角，完整婚紗輪廓清楚可見",
    background: "水晶吊燈、香檳金牆面、拱形門與柔焦大廳深景",
    action: "人物一手低持捧花，一手自然整理頭紗，姿態端莊",
    lighting: "crystal chandelier glow、champagne marble bounce、soft bridal key light",
    atmosphere: "高訂婚紗品牌大片感，避免誇張性感剪裁",
  },
  {
    id: "style-ref-bridal-rose-chapel-veil-muse",
    title: "玫瑰禮堂・長紗花嫁",
    parentCategory: "高訂婚紗禮服",
    series: "風格範例轉卡／高訂婚紗補強",
    themeHint: "玫瑰禮堂 長頭紗 蕾絲婚紗 花窗 柔光",
    aliases: ["玫瑰禮堂", "長頭紗", "蕾絲婚紗", "花窗", "柔光"],
    identity: "玫瑰禮堂長紗花嫁",
    palette: "珍珠白、淡玫瑰、柔金、月光灰與花葉綠",
    costumeCore: "珍珠白蕾絲婚紗、長袖薄紗、完整安全內襯、柔軟拖尾與透明長頭紗",
    jewelry: "珍珠耳環、花形髮梳、細鑽手鏈與玫瑰金戒指",
    prop: "淡粉玫瑰捧花與白色誓約書",
    place: "玫瑰花窗小禮堂",
    foreground: "玫瑰捧花、白色誓約書、木椅邊緣與頭紗紋理",
    midground: "真人花嫁站在禮堂中央通道，臉部與婚紗細節清楚",
    background: "彩色花窗、白玫瑰拱門、木椅排與柔焦光束",
    action: "人物雙手低捧玫瑰，頭紗自然垂落不遮臉",
    lighting: "rose stained-glass light、soft chapel glow、pearl veil highlights",
    atmosphere: "浪漫禮堂婚紗寫真，避免過度奇幻化與插畫感",
  },
  {
    id: "style-ref-coastal-white-linen-resort-traveler",
    title: "白亞麻海岸・度假旅人",
    parentCategory: "海岸度假旅拍",
    series: "風格範例轉卡／海岸度假補強",
    themeHint: "白亞麻 海岸別墅 藍海 草帽 度假旅拍",
    aliases: ["白亞麻", "海岸別墅", "藍海", "草帽", "度假"],
    identity: "白亞麻海岸度假旅人",
    palette: "亞麻白、海水藍、珊瑚粉、藤編棕與陽光金",
    costumeCore: "白色亞麻長裙、輕薄外罩衫、寬檐草帽與海岸度假安全層次",
    jewelry: "貝殼耳飾、細金腳鏈、藤編手環與小珍珠項鍊",
    prop: "藤編托特包、草帽與旅行墨鏡",
    place: "海岸白牆度假別墅露台",
    foreground: "藤編包、白牆陰影、藍色地磚與海風揚起的裙角",
    midground: "真人旅人站在露台邊，臉部受陽光與反光板柔和照亮",
    background: "藍海、白色欄杆、棕櫚葉與遠方遊艇光點",
    action: "人物一手扶草帽，一手提托特包，目光自然看向鏡頭",
    lighting: "bright coastal sunlight、white wall bounce、soft sea rim light",
    atmosphere: "乾淨高級的海岸度假旅拍，避免泳裝主導與濕身效果",
  },
  {
    id: "style-ref-coastal-coral-sunset-beach-lady",
    title: "珊瑚夕灘・海風度假女主",
    parentCategory: "海岸度假旅拍",
    series: "風格範例轉卡／海岸度假補強",
    themeHint: "夕陽沙灘 珊瑚色長裙 海風 棕櫚 度假旅拍",
    aliases: ["夕陽沙灘", "珊瑚長裙", "海風", "棕櫚", "度假旅拍"],
    identity: "珊瑚夕灘海風度假女主",
    palette: "珊瑚橘、落日金、海藍、沙白與棕櫚綠",
    costumeCore: "珊瑚色度假長裙、輕薄披肩、完整安全內襯與自然垂墜裙擺",
    jewelry: "金色圈耳環、貝殼手鏈、細項鍊與藤編髮夾",
    prop: "小型草編手包與白色涼鞋",
    place: "夕陽海灘棕櫚步道旁",
    foreground: "沙灘足跡、草編手包、裙擺邊緣與海浪泡沫",
    midground: "真人女主站在棕櫚步道側，海風自然帶動披肩",
    background: "橘金夕陽、柔焦海平線、棕櫚剪影與遠方度假燈光",
    action: "人物一手整理披肩，一手自然提包，臉部保持明亮可辨識",
    lighting: "golden sunset key、soft ocean bounce、warm coral rim light",
    atmosphere: "海岸夕陽度假電影寫真，避免泳裝主導與過度性感姿態",
  },
  {
    id: "style-ref-golden-satin-bedchamber-favored-consort",
    title: "金緞寢宮・宮燈寵妃",
    parentCategory: "寢宮寵妃系列",
    series: "風格範例轉卡／金緞寢宮寵妃",
    themeHint: "古風宮廷 寵妃 金緞禮服 皇宮寢宮 宮燈 紅木床榻 珠寶 金冠流蘇",
    aliases: ["金緞寢宮", "宮燈寵妃", "皇宮寢宮", "金色緞面", "紅木床榻", "Vogue古風"],
    identity: "金緞寢宮宮燈寵妃",
    palette: "香檳金、暖銅金、紅木棕、琥珀燈火與深宮暗影",
    costumeCore: "香檳金高級緞面宮廷禮服、完整安全內襯、簡潔大面積 satin 光澤、少量金色蕾絲、鑽石水晶腰飾與寬袖外袍，形成高級寵妃禮服輪廓而非低俗寫真",
    jewelry: "高髻金冠、金絲髮簪、寶石流蘇步搖、垂墜耳飾、細鑽項鍊與金色手鐲",
    prop: "金色香盒、珠寶托盤與紅木案几",
    place: "奢華皇宮寢宮紅木床榻側",
    foreground: "金緞裙擺、珠寶托盤、香盒、紅木案几與宮燈暖光反射",
    midground: "真人寵妃端坐床榻側或站在紅木案几旁，肩頸線條優雅但服裝完整端正",
    background: "金色宮燈、絲綢帷帳、紅木家具、華麗床榻、珠寶擺設與皇家裝飾形成深景",
    action: "人物一手輕扶紅木案几，一手整理寬袖或低持香盒，視線微側正面看向鏡頭，腿部與胸腰不作為主視覺",
    lighting: "warm palace lantern key、amber silk bounce、diamond crystal sparkle、soft Vogue editorial fill light",
    atmosphere: "超寫實古風宮廷人像與國際時尚雜誌封面質感，保留高貴寵妃氣場，避免低俗坐姿、過度開衩、裸露或 pin-up 構圖",
  },
  {
    id: "bedchamber-consort-amber-reclining-gaze",
    title: "琥珀金榻・正視斜臥寵妃",
    parentCategory: "寢宮寵妃系列",
    series: "寢宮寵妃系列／金緞斜臥",
    themeHint: "寵妃 寢宮 斜躺 正視鏡頭 琥珀金緞 大長腿 宮燈",
    aliases: ["寢宮寵妃", "斜躺正視", "琥珀金緞", "宮燈", "長腿線條"],
    identity: "琥珀金榻正視斜臥寵妃",
    palette: "琥珀金、香檳緞、紅木棕、燭火橙與深宮黑",
    costumeCore: "琥珀金 satin 宮廷禮服、低領但有安全內襯的珠飾胸衣結構、長裙開衩露出修長腿部線條、寬袖披袍與鑽石水晶腰飾",
    jewelry: "高髻金冠、長流蘇步搖、琥珀寶石耳墜、細鑽項鍊與金色臂釧",
    prop: "紅木小几、金色香盒與珠寶托盤",
    place: "皇宮寢宮金色床榻與紅木小几旁",
    foreground: "金緞裙擺、長袖披紗、香盒、珠寶托盤與床榻錦墊",
    midground: "真人寵妃斜躺倚靠床榻，臉部正視鏡頭，腿部線條由裙擺自然延伸但服裝完整",
    background: "金色宮燈、絲綢帷帳、紅木雕花屏風、燭台與深色寢宮陳設",
    action: "人物一手撐在床榻側方，一手輕扶裙擺或小几，身體斜躺但臉部清楚看向鏡頭",
    lighting: "warm lantern key light、gold satin specular highlights、soft facial fill、amber candle bokeh",
    atmosphere: "成熟高訂寢宮寵妃大片，保留長腿與豐盈身形的禮服比例參考，但避免裸露、情趣化或低俗 pin-up",
  },
  {
    id: "bedchamber-consort-crimson-gold-couch",
    title: "朱金鳳帳・扶案側坐寵妃",
    parentCategory: "寢宮寵妃系列",
    series: "寢宮寵妃系列／鳳帳側坐",
    themeHint: "朱金寢宮 鳳帳 側坐 扶案 低領禮服 紅木珠寶",
    aliases: ["朱金寵妃", "鳳帳", "扶案側坐", "紅木珠寶", "低領禮服"],
    identity: "朱金鳳帳扶案側坐寵妃",
    palette: "朱砂紅、古金、香檳膚金、紅木棕與燭火橙",
    costumeCore: "朱金緞面宮廷禮服、低領珠繡胸衣外層、完整內襯、修身高腰長裙與寬大金紗披袖，展現成熟曲線但不做身體特寫",
    jewelry: "鳳形金冠、紅寶流蘇耳墜、金絲腰鏈、鑽石項鍊與細金手鐲",
    prop: "紅寶香瓶、宮扇與紅木珠寶盒",
    place: "朱金鳳帳皇宮寢殿",
    foreground: "宮扇、珠寶盒、紅木案角與金紗披袖",
    midground: "真人寵妃側坐床榻邊，一手扶紅木案几，肩頸與禮服輪廓清楚",
    background: "鳳紋帷帳、金色宮燈、雕花紅木牆面與暖色床榻",
    action: "人物微側身扶案回望鏡頭，裙擺沿床榻垂落，雙腿線條由開衩禮服自然呈現",
    lighting: "red-gold palace practicals、warm silk bounce、ruby jewelry catchlight",
    atmosphere: "Vogue 古風寢宮大片，高貴、成熟、艷麗但保持真人可穿戴高訂禮服",
  },
  {
    id: "bedchamber-consort-moonwhite-silk-canopy",
    title: "月白紗帳・倚榻凝眸寵妃",
    parentCategory: "寢宮寵妃系列",
    series: "寢宮寵妃系列／月白倚榻",
    themeHint: "月白 緞面 寢宮 紗帳 倚榻 凝眸 珍珠",
    aliases: ["月白寵妃", "紗帳", "倚榻", "珍珠", "凝眸"],
    identity: "月白紗帳倚榻凝眸寵妃",
    palette: "月白、淡金、珍珠銀、霧灰與暖燭色",
    costumeCore: "月白 satin 宮廷禮服、珍珠鑲邊低領上身、完整安全內襯、細緻腰封與柔軟長披帛",
    jewelry: "珍珠金冠、月白流蘇髮簪、珍珠耳墜、細鑽鎖骨鏈與白玉手鐲",
    prop: "白玉香爐、珍珠團扇與月白絲帕",
    place: "月白紗帳皇宮寢榻",
    foreground: "珍珠團扇、月白絲帕、香爐煙氣與緞面裙擺",
    midground: "真人寵妃倚靠床榻軟枕，正面或微側正面凝視鏡頭，姿態柔和",
    background: "半透明紗帳、金色宮燈、白玉擺件與柔焦紅木窗格",
    action: "人物一手低持珍珠團扇，一手自然扶住軟枕，長裙開衩只作為腿部線條點綴",
    lighting: "soft moon-white silk bounce、warm candle edge light、pearl highlights",
    atmosphere: "月白高級寢宮人像，柔美但克制，避免過度暴露與低俗臥姿",
  },
  {
    id: "bedchamber-consort-peacock-blue-jewel-lantern",
    title: "孔雀藍燈・珠簾長腿寵妃",
    parentCategory: "寢宮寵妃系列",
    series: "寢宮寵妃系列／孔雀藍珠簾",
    themeHint: "孔雀藍 緞面 珠簾 宮燈 長腿 低領 寵妃",
    aliases: ["孔雀藍", "珠簾", "長腿寵妃", "低領緞面", "宮燈"],
    identity: "孔雀藍燈珠簾長腿寵妃",
    palette: "孔雀藍、青金石、暖金、深木棕與琥珀燈色",
    costumeCore: "孔雀藍緞面宮廷禮服、金色蕾絲低領結構、完整內襯、長裙高開衩與透明披帛，強化超模長腿線條但不做低角度特寫",
    jewelry: "青金石金冠、藍寶流蘇耳飾、金色腰鏈、寶石頸鍊與細金戒指",
    prop: "青金石酒杯、金色宮扇與珠簾",
    place: "孔雀藍珠簾宮燈寢宮",
    foreground: "珠簾、宮扇、藍寶酒杯與緞面裙擺反光",
    midground: "真人寵妃坐在床榻側緣，雙腿斜向畫面下方延伸，臉部正面看鏡頭",
    background: "孔雀藍絲帳、金色宮燈、紅木屏風與寶石擺設",
    action: "人物一手撩開珠簾，一手低持宮扇，腿部線條在裙擺間自然可見",
    lighting: "warm lantern key、blue satin bounce、jewel-tone sparkle highlights",
    atmosphere: "寶石色寢宮時尚大片，性感比例收錄為禮服剪裁參考，不轉成暴露寫真",
  },
  {
    id: "bedchamber-consort-rose-gold-makeup-table",
    title: "玫瑰金妝台・半倚寵妃",
    parentCategory: "寢宮寵妃系列",
    series: "寢宮寵妃系列／妝台半倚",
    themeHint: "玫瑰金 妝台 半倚 寵妃 鏡奩 珠寶 低領緞面",
    aliases: ["玫瑰金", "妝台", "半倚", "鏡奩", "珠寶寵妃"],
    identity: "玫瑰金妝台半倚寵妃",
    palette: "玫瑰金、蜜桃粉、暖金、紅木棕與柔燭色",
    costumeCore: "玫瑰金 satin 宮廷禮服、低領水晶胸衣外層、完整安全內襯、柔軟高腰長裙與半透明披袖",
    jewelry: "玫瑰金花冠、粉晶耳墜、細鑽鎖骨鏈、金絲髮簪與寶石手鏈",
    prop: "銅鏡、胭脂盒與粉晶珠寶盤",
    place: "皇宮寢宮紅木妝台旁",
    foreground: "銅鏡、胭脂盒、粉晶珠寶盤與玫瑰金裙擺",
    midground: "真人寵妃半倚妝台，肩頸線條與禮服胸衣結構清楚，視線看向鏡頭",
    background: "紅木妝台、金色宮燈、絲綢帷幕、床榻與柔焦珠簾",
    action: "人物一手扶妝台，一手低持胭脂盒，身體半倚但臉部完整明亮",
    lighting: "warm vanity lantern glow、rose-gold satin highlights、soft beauty editorial fill",
    atmosphere: "高級妝台寵妃封面感，保留豐盈身形與低領禮服比例，但避免裸露與情趣化",
  },
  {
    id: "bedchamber-consort-black-gold-night-palace",
    title: "墨金夜宮・低靠寵妃",
    parentCategory: "寢宮寵妃系列",
    series: "寢宮寵妃系列／墨金低靠",
    themeHint: "墨金 夜宮 寢宮 低靠 長腿 金冠 燭火",
    aliases: ["墨金", "夜宮", "低靠", "長腿", "燭火寵妃"],
    identity: "墨金夜宮低靠寵妃",
    palette: "墨黑、古金、琥珀、暗紅木與燭火橙",
    costumeCore: "墨金 satin 宮廷長裙、金線刺繡低領上身、完整內襯、修身腰封、側開衩長裙與黑金薄紗外袍",
    jewelry: "黑金鳳冠、金曜石耳墜、古金臂釧、黑鑽項鍊與細金腰鏈",
    prop: "金色燭台、黑玉香盒與紅木靠枕",
    place: "夜色皇宮寢殿燭台床榻旁",
    foreground: "燭台火光、黑玉香盒、紅木靠枕與墨金裙擺",
    midground: "真人寵妃低靠床榻軟枕，雙腿由裙擺自然斜向前景，臉部轉向鏡頭",
    background: "深色帷帳、金色宮燈、雕花紅木牆與遠景燭火",
    action: "人物一手撐住軟枕，一手自然扶住裙側，低靠姿勢穩定且不遮臉",
    lighting: "candle key light、black satin edge highlights、warm amber facial fill",
    atmosphere: "暗金寢宮高訂大片，成熟冷艷但保持宮廷禮服完整性",
  },
  {
    id: "bedchamber-consort-emerald-jade-screen",
    title: "翡翠玉屏・回眸寵妃",
    parentCategory: "寢宮寵妃系列",
    series: "寢宮寵妃系列／翡翠玉屏",
    themeHint: "翡翠 緞面 玉屏 回眸 寢宮 長腿 低領",
    aliases: ["翡翠寵妃", "玉屏", "回眸", "翡翠緞面", "長腿"],
    identity: "翡翠玉屏回眸寵妃",
    palette: "翡翠綠、暖金、玉白、深紅木與宮燈橙",
    costumeCore: "翡翠綠 satin 宮廷禮服、金色蕾絲低領外層、完整安全內襯、修長裙擺與高級開衩剪裁",
    jewelry: "翡翠金冠、玉石流蘇步搖、翡翠耳墜、玉佩腰飾與細金項鍊",
    prop: "白玉酒盞、翡翠香盒與繡花靠枕",
    place: "翡翠玉屏皇宮寢宮",
    foreground: "白玉酒盞、翡翠香盒、靠枕與綠緞裙擺",
    midground: "真人寵妃坐於床榻側方微側回眸，臉部明亮，腿部線條由開衩裙自然露出",
    background: "玉屏風、金色宮燈、紅木床榻、絲綢帷帳與珠寶擺設",
    action: "人物一手扶玉屏邊緣，一手低持酒盞，回眸角度仍保留雙眼與五官清楚",
    lighting: "jade-green silk bounce、warm palace lantern key、gold jewelry sparkle",
    atmosphere: "翡翠宮廷寵妃時尚大片，保持優雅高貴，不做低俗挑逗姿勢",
  },
  {
    id: "bedchamber-consort-amethyst-purple-curtain",
    title: "紫晶帷幕・倚枕寵妃",
    parentCategory: "寢宮寵妃系列",
    series: "寢宮寵妃系列／紫晶倚枕",
    themeHint: "紫晶 宮廷 帷幕 倚枕 寵妃 低領 大長腿",
    aliases: ["紫晶寵妃", "帷幕", "倚枕", "低領", "大長腿"],
    identity: "紫晶帷幕倚枕寵妃",
    palette: "紫晶、香檳金、暗玫瑰、紅木棕與燭火金",
    costumeCore: "紫晶 satin 宮廷禮服、香檳金水晶低領胸衣、完整內襯、細腰封與飄逸紫金披袖",
    jewelry: "紫晶金冠、紫寶石流蘇耳墜、細鑽項鍊、金絲腰飾與水晶手鏈",
    prop: "紫晶酒杯、金色香爐與暗玫瑰靠枕",
    place: "紫晶帷幕皇宮寢榻",
    foreground: "紫晶酒杯、香爐煙氣、暗玫瑰靠枕與紫金裙擺",
    midground: "真人寵妃倚靠軟枕，身體斜向畫面，臉部正視鏡頭",
    background: "紫金帷幕、金色燈架、紅木床柱與柔焦珠簾",
    action: "人物一手扶軟枕，一手低持紫晶酒杯，長腿線條在裙擺與床榻間自然延伸",
    lighting: "amethyst silk glow、warm gold lantern fill、crystal sparkle highlights",
    atmosphere: "紫晶寢宮成熟時尚大片，強調禮服剪裁與姿態曲線，不生成裸露或情趣化內容",
  },
  {
    id: "bedchamber-consort-snow-gold-moon-window",
    title: "雪金月窗・側臥寵妃",
    parentCategory: "寢宮寵妃系列",
    series: "寢宮寵妃系列／雪金月窗",
    themeHint: "雪金 月窗 側臥 寵妃 緞面 長腿 宮廷",
    aliases: ["雪金", "月窗", "側臥", "寵妃", "緞面長腿"],
    identity: "雪金月窗側臥寵妃",
    palette: "雪白、淡金、月銀、紅木棕與暖燭色",
    costumeCore: "雪金緞面宮廷長裙、淡金蕾絲低領結構、完整安全內襯、銀白披紗與修長側開衩裙擺",
    jewelry: "淡金月冠、珍珠流蘇、月銀耳墜、白鑽項鍊與玉鐲",
    prop: "月白團扇、白玉香盒與金線軟枕",
    place: "月窗映光皇宮寢榻",
    foreground: "月白團扇、白玉香盒、金線軟枕與雪金緞面裙擺",
    midground: "真人寵妃側臥倚靠床榻，臉部朝向鏡頭，姿勢舒展而端正",
    background: "月窗、金色宮燈、白紗帷幕、紅木家具與柔焦珠寶擺件",
    action: "人物一手低持團扇，一手撐住床榻，側臥姿態保留長腿比例但不以身體局部特寫",
    lighting: "moon window cool fill、warm lantern key、snow-gold satin highlights",
    atmosphere: "雪金月夜寢宮封面感，保留斜臥姿勢與長腿線條，避免裸露、低俗視角與 AI 寫真感",
  },
  ...BEDCHAMBER_CONSORT_EXPANSION_PROFILES,
  ...BEDCHAMBER_SUCCUBUS_EXPANSION_PROFILES,
  // ─── 圖片分析建檔 batch-2 2026-06-07（下排 6 張）──────────────
  {
    id: "style-ref-dark-moon-palace-succubus-queen",
    title: "暗月殿柱・魅魔黑紫女王",
    parentCategory: "魅魔",
    series: "風格範例轉卡／暗月殿柱魅魔",
    themeHint: "暗月 大理石宮殿 深紫黑 掛脖禮服 高開衩 魅魔女王 奇幻",
    aliases: ["暗月宮殿", "黑紫魅魔", "掛脖深V", "大理石柱", "月夜女王"],
    identity: "暗月殿柱魅魔黑紫女王",
    palette: "墨黑、深紫、金色、月銀與暗大理石灰",
    costumeCore: "黑紫深V掛脖晚禮服，完整安全內襯，金色胸口裝飾，高開衩長裙，修身貼合，宮廷奇幻風格",
    jewelry: "金色頸鍊、細金耳飾與手部金屬飾件",
    prop: "大理石宮殿柱作支撐點，月光圓窗作背景光源",
    place: "奢華大理石宮殿大廳，圓拱窗透出滿月",
    foreground: "大理石地板倒影與金色光斑虛化",
    midground: "真人魅魔女王全身站立，臉部至腳踝，正面構圖，高開衩裙擺自然垂落",
    background: "大理石立柱、圓拱窗滿月、深紫霧氣與金色燭光點綴",
    action: "人物站立於大理石廳，一手自然垂落或微扶裙側，臉部正視鏡頭，氣場強勢冷豔",
    lighting: "moon backlight through arch、gold candle edge rim、soft purple facial fill",
    atmosphere: "暗月宮殿魅魔女王奇幻電影海報，強調服裝剪裁與氣場，不做低俗或情趣化呈現",
    cupSize: "K",
  },
  {
    id: "style-ref-pink-hanfu-floral-crown-gentle",
    title: "桃粉花冠・漢服溫婉仕女",
    parentCategory: "中國歷代服裝／泛朝代總覽",
    series: "風格範例轉卡／桃粉漢服花冠",
    themeHint: "桃粉漢服 花冠 紅流蘇 溫婉 微笑 傳統中式 真實感",
    aliases: ["桃粉漢服", "花冠仕女", "紅流蘇", "溫婉微笑", "古裝仕女"],
    identity: "桃粉花冠漢服溫婉仕女",
    palette: "桃粉、胭脂紅、金色、珍珠白與暖米色",
    costumeCore: "桃粉色漢服，刺繡花紋上衣，寬袖飄帶，合身腰線，完整傳統服裝剪裁",
    jewelry: "粉花金冠、紅色流蘇髮飾、紅寶珠鍊項鍊與耳墜",
    prop: "傳統室內傢俬作背景陳設，非手持",
    place: "傳統中式室內，米色大理石或暖色背景",
    foreground: "柔焦前景淺虛化",
    midground: "真人仕女上半身正面，臉部至腰線清楚，表情溫婉帶微笑",
    background: "暖色調室內、米色或淺棕大理石柱、柔和環境光",
    action: "人物站立或輕坐，雙手自然疊於前方或輕扶衣袖，微笑直視鏡頭，姿態端莊溫柔",
    lighting: "warm soft studio key、gentle fill、peach skin highlight",
    atmosphere: "傳統漢服仕女溫婉寫真封面，以花冠與服裝細節為視覺重點，不做低俗或誇張構圖",
  },
  {
    id: "style-ref-rainbow-energy-magic-sorceress",
    title: "彩焰能量・仙俠魔法術士",
    parentCategory: "仙俠神話 / 古裝陸劇",
    series: "風格範例轉卡／彩焰能量術士",
    themeHint: "彩色能量光焰 魔法術士 仙俠 暗色背景 旋渦光效 奇幻",
    aliases: ["彩焰能量", "魔法術士", "仙俠光效", "旋渦光芒", "奇幻魔法"],
    identity: "彩焰能量仙俠魔法術士",
    palette: "彩虹色能量光（藍、綠、紅、金、紫）、深暗背景、金色光點",
    costumeCore: "深色仙俠服裝或半透明能量衣，服裝與光效融合，整體以能量光芒為視覺主體",
    jewelry: "髮飾與能量光效融合，細節被光芒環繞",
    prop: "彩色能量旋渦與光焰（場景效果，非手持道具）",
    place: "魔法空間，暗色深景，能量光焰環繞",
    foreground: "彩色能量光點與旋渦前景虛化",
    midground: "人物上半身或四分之三身，被彩色能量光焰環繞，臉部清楚可辨",
    background: "深暗抽象空間、彩色光芒放射、金色光點散佈",
    action: "人物姿態施法或召喚，雙手或單手引導能量，神情專注或自信，能量光焰不遮擋五官",
    lighting: "rainbow energy emission light、dark surround、golden particle glow",
    atmosphere: "仙俠奇幻魔法術士電影海報，彩色能量旋渦為核心視覺，強調動態感與神秘氣息",
  },
  {
    id: "style-ref-white-hanfu-fan-sunset-pavilion",
    title: "白裙宮扇・夕照古亭仕女",
    parentCategory: "中國歷代服裝／泛朝代總覽",
    series: "風格範例轉卡／夕照古亭白裙",
    themeHint: "白色漢服 宮扇 古亭 夕陽 桃花 仙俠古裝 古典",
    aliases: ["白色漢服", "宮扇仕女", "古亭夕照", "桃花古裝", "夕陽古亭"],
    identity: "白裙宮扇夕照古亭仕女",
    palette: "純白、奶白、金橙夕陽、淡粉桃花與青灰古亭",
    costumeCore: "白色或奶白漢服長裙，輕薄飄帶，精緻刺繡點綴，端莊傳統剪裁",
    jewelry: "細髮飾、珍珠或白玉耳飾、細鑽項鍊",
    prop: "白色或淡金圓形宮扇（仙俠古裝場景合理持物）",
    place: "古代亭閣旁，夕陽橙光，遠景古塔",
    foreground: "桃花花瓣飄落或花叢淺焦虛化",
    midground: "真人仕女上半身至腰線，正面或微側，宮扇半遮半展，臉部清楚",
    background: "古亭、古塔剪影、橙金夕陽天空、遠景城廓",
    action: "人物持宮扇微扇或半展置於胸前側方，眼神望向遠方或鏡頭，姿態悠然",
    lighting: "warm sunset backlight、soft golden fill、white hanfu rim glow",
    atmosphere: "仙俠古裝夕照電影封面，以夕陽逆光與白裙飄動為視覺核心，持宮扇為古裝場景合理持物",
  },
  {
    id: "style-ref-white-butterfly-fairy-celestial",
    title: "白蝶仙羽・縹緲天仙花女",
    parentCategory: "花園童話 / 自然精靈",
    series: "風格範例轉卡／白蝶天仙",
    themeHint: "白色薄紗 蝴蝶羽翼 天仙 縹緲 花卉 精靈 夢幻奇幻",
    aliases: ["白蝶仙羽", "天仙花女", "縹緲精靈", "白色薄紗翼", "夢幻仙子"],
    identity: "白蝶仙羽縹緲天仙花女",
    palette: "純白、月白、淡粉、薄荷銀與柔金光",
    costumeCore: "白色透明薄紗仙裝，蝴蝶形羽翼披肩，多層輕薄裙擺，精緻刺繡與花瓣裝飾",
    jewelry: "白色花形髮飾、細鑽項鍊、銀色耳飾",
    prop: "白色花卉環繞或蝴蝶裝飾（場景效果，非手持）",
    place: "縹緲仙境，白光霧氣環繞，花瓣飄散",
    foreground: "白色花瓣或光點淺焦前景",
    midground: "人物上半身或半身，蝴蝶翼向後展開，臉部正面清楚",
    background: "白霧仙境、花卉光暈、柔白光芒散射",
    action: "人物站立或微浮，雙手自然垂落或輕托裙擺，翼形紗羽向後展開，神情縹緲聖潔",
    lighting: "soft diffuse white light、petal bokeh glow、cool silver rim",
    atmosphere: "白蝶天仙縹緲仙境電影封面，蝴蝶羽翼與白色薄紗為核心視覺，不做裸露或情趣化",
  },
  {
    id: "style-ref-white-robe-longblack-hair-xianxia",
    title: "白袍長髮・仙俠素雅仕女",
    parentCategory: "仙俠神話 / 古裝陸劇",
    series: "風格範例轉卡／白袍仙俠長髮",
    themeHint: "白袍 超長黑直髮 仙俠 素雅 清冷 古裝 淡雅",
    aliases: ["白袍仙俠", "超長黑髮", "素雅仙女", "清冷古裝", "仙俠長髮"],
    identity: "白袍長髮仙俠素雅仕女",
    palette: "純白、月白、墨黑長髮、淡金點綴與清冷白光",
    costumeCore: "白色仙俠長袍，飄逸袖擺，素雅刺繡，清冷高雅剪裁，超長直黑髮垂落至腰下",
    jewelry: "淡金髮冠或細髮飾、白玉或細鑽耳飾、細鍊項鍊",
    prop: "白梅花枝或淡色扇（可選，非必持）",
    place: "仙俠庭院、白霧仙境或淡色花院",
    foreground: "白梅或淡花瓣淺焦前景",
    midground: "人物上半身或半身，超長黑髮自然垂落，臉部清晰正面或微側",
    background: "白霧仙境、淡色花院、月白遠景與清冷環境",
    action: "人物站立，雙手自然垂落或輕扶長袍，超長黑髮隨姿態自然垂落，神情清冷素雅",
    lighting: "cool white diffuse key、soft moonlight fill、black hair shine highlight",
    atmosphere: "仙俠素雅白袍清冷電影封面，以超長黑直髮與白袍對比為視覺核心，氣質清冷出塵",
  },
  // ─── 圖片分析建檔 batch-1 2026-06-07（上排 6 張）──────────────
  {
    id: "style-ref-banquet-colorprint-slip-dress",
    title: "水彩印染・宴會晚禮服名媛",
    parentCategory: "現代都市夜景",
    series: "風格範例轉卡／宴會晚禮服",
    themeHint: "水彩印染 細肩帶 迷你裙 宴會廳 水晶吊燈 真人寫真",
    aliases: ["宴會晚禮服", "水彩印染", "細肩帶", "迷你裙", "宴會廳"],
    identity: "水彩印染宴會晚禮服名媛",
    palette: "紅橙黑水彩暈染、金色光澤、奶白膚色",
    costumeCore: "水彩印染絲緞細肩帶迷你洋裝，紅橙黑抽象花紋，斜裁深V領口，膝上裙長，光澤流動感面料",
    jewelry: "細圈金色項鍊、簡約金耳環",
    prop: "水晶酒杯置桌面陳設，非手持",
    place: "豪華宴會廳圓桌旁",
    foreground: "桌邊餐具與水晶杯淺焦虛化",
    midground: "真人名媛坐於椅沿，臉部至膝蓋完整入鏡，正面構圖",
    background: "水晶吊燈、白色圓桌、後方虛化賓客身影",
    action: "人物坐於椅沿，雙腿自然側疊，雙手交疊置膝，眼神直視鏡頭，表情自信優雅",
    lighting: "宴會廳暖金水晶吊燈主光、桌面反射補光、臉部清晰",
    atmosphere: "高端宴會廳真人寫真電影感封面，裙長端正，不以腿部或胸口為主視覺",
  },
  {
    id: "style-ref-redwine-stargown-bar-fantasy",
    title: "星光流轉・吧台紅髮夢幻名伶",
    parentCategory: "現代都市夜景",
    series: "風格範例轉卡／吧台星光",
    themeHint: "超長紅髮 星芒白銀長裙 吧台 持酒杯 裸背 夢幻奇幻",
    aliases: ["超長紅髮", "星芒長裙", "吧台名伶", "裸背長裙", "夢幻吧台"],
    identity: "星光流轉吧台紅髮夢幻名伶",
    palette: "白銀星芒、玫瑰紅髮、暖橘金光、紫花點綴",
    costumeCore: "白銀閃片星芒多層荷葉裙擺長裙，深V裸背設計，金色星形刺繡，裙擺拖地，超長紅粉飄逸長髮",
    jewelry: "細金耳墜、金色星形鑲嵌高跟涼鞋",
    prop: "水晶紅酒杯（吧台場景合理持物，手舉杯與肩齊）",
    place: "奢華吧台，玻璃酒架與鮮花背景",
    foreground: "吧台木質台面淺焦虛化",
    midground: "人物背向鏡頭坐於吧台椅，頭部側回，紅髮飄散成視覺主軸",
    background: "玻璃酒瓶排列、紫色花束、暖橘燈光光柱",
    action: "人物背向鏡頭坐於吧台椅，一手舉起紅酒杯與肩齊，另一手自然扶台，側回頭，超長紅髮飄逸，裙擺落地",
    lighting: "吧台暖橘光主光、玻璃折射星光、裙面閃片漫反射",
    atmosphere: "夢幻吧台奇幻禮服電影海報，以超長紅髮與裙擺曲線為視覺焦點，吧台場景持酒杯合理",
  },
  {
    id: "style-ref-purple-holographic-crystal-bar",
    title: "紫幻全息・吧台水晶星鑽女王",
    parentCategory: "現代都市夜景",
    series: "風格範例轉卡／紫光全息吧台",
    themeHint: "紫霓虹 全息水晶短裙 白羽毛 吧台 持酒杯 賽博奇幻",
    aliases: ["紫霓虹", "全息水晶", "白羽毛外套", "夜店吧台", "賽博奇幻"],
    identity: "紫幻全息吧台水晶星鑽女王",
    palette: "紫色霓虹、全息彩虹、白銀星芒、珠光膚色",
    costumeCore: "全息透明水晶短裙，星形金色刺繡，白色羽毛皮草外套，星鏈裙腰，水晶高跟涼鞋",
    jewelry: "紫色珠寶發帶、水晶鏈耳飾、金色星鏈手鍊",
    prop: "白葡萄酒水晶杯（吧台場景合理持物）",
    place: "都市高空吧台，紫色霓虹燈光，落地窗夜景",
    foreground: "粉紫花卉淺焦虛化",
    midground: "人物斜坐吧台高腳椅，雙腿交疊，一手舉持酒杯，側面略仰視角",
    background: "紫色霓虹反射、玻璃酒瓶排列、都市夜景落地窗",
    action: "人物斜坐吧台椅，雙腿交疊，一手舉持白酒杯，另一手撐臉側靠，目光仰視鏡頭，表情慵懶",
    lighting: "紫色霓虹主光、都市夜景冷光、水晶折射彩虹光斑",
    atmosphere: "賽博紫光全息吧台奇幻封面，以霓虹色彩與水晶折射為視覺核心，吧台持酒杯合理",
  },
  {
    id: "style-ref-pink-fairy-lavender-creek-sunset",
    title: "薰衣草溪畔・粉紗花仙",
    parentCategory: "花園童話 / 自然精靈",
    series: "風格範例轉卡／薰衣草花仙",
    themeHint: "薰衣草花田 溪畔 日落 粉紗花仙 透明裙 夢幻",
    aliases: ["薰衣草", "花田溪畔", "日落花仙", "粉紗仙子", "夢幻花田"],
    identity: "薰衣草溪畔粉紗花仙",
    palette: "粉紫薰衣草、玫瑰粉、白色野花、橙金日落、溪流藍",
    costumeCore: "粉色透明薄紗花仙長裙，交叉肩帶，胸口立體碎花刺繡，多層飄逸裙擺",
    jewelry: "白色碎花髮夾、花形長吊耳墜、細鑽項鍊",
    prop: "周圍薰衣草與野花自然環繞，非手持道具",
    place: "薰衣草花田，溪流旁，遠山輪廓",
    foreground: "薰衣草與野花淺焦虛化，花瓣點綴前景",
    midground: "人物站於花田溪畔，上半身至腰線，正面構圖，夢幻柔焦",
    background: "薰衣草叢、白色野花、玫瑰、溪流水光、遠山與日落天際線",
    action: "人物站於花田，上身微前傾，雙手自然垂落或輕扶薄紗裙擺，眼神直視鏡頭，神情柔美夢幻",
    lighting: "橙粉日落逆光主光、溪面反射暖光、薄紗透光補光",
    atmosphere: "薰衣草花田日落花仙夢幻電影封面，道具為自然花卉環繞非手持，以光影與裙擺飄動為視覺重點",
  },
  {
    id: "style-ref-black-gold-peony-qipao-study",
    title: "黑金牡丹・書閣旗袍名媛",
    parentCategory: "東方旗袍夜宴",
    series: "風格範例轉卡／黑金旗袍書閣",
    themeHint: "黑金牡丹 短袖旗袍 書閣 水墨字畫 真人寫真",
    aliases: ["黑金旗袍", "牡丹刺繡", "書閣旗袍", "中式書房", "水墨"],
    identity: "黑金牡丹書閣旗袍名媛",
    palette: "黑色、金牡丹暗紋、暖棕木色、淺膚色",
    costumeCore: "黑底金牡丹暗紋緞面短袖旗袍，盤扣立領，合身剪裁至膝下",
    jewelry: "花形髮夾（側別馬尾）、珍珠長耳墜",
    prop: "書閣古典傢俬作背景陳設，非手持",
    place: "中式傳統書房，水墨字畫、深色實木傢俬",
    foreground: "深色實木桌角淺焦虛化",
    midground: "真人名媛四分之三側身站立，臉部至腰線，側面視角，真人攝影感",
    background: "水墨山水畫卷、古典花器、實木書架、暖棕調環境",
    action: "人物四分之三側身站立，頭部微側望向側前方，雙手自然垂落，神情內斂優雅",
    lighting: "室內暖棕側光主光、環境漫反射補光、臉部明亮",
    atmosphere: "中式書閣旗袍真人寫真電影感封面，服裝端正合身，不做低視角或身體特寫",
  },
  {
    id: "style-ref-paris-cafe-cream-blouse-afternoon",
    title: "巴黎午後・甜點咖啡館奶油白衫",
    parentCategory: "現代都市 / 街拍電影",
    series: "風格範例轉卡／巴黎咖啡館",
    themeHint: "巴黎 甜點咖啡館 奶油白荷葉邊 持咖啡杯 生活寫真 真人",
    aliases: ["巴黎咖啡館", "奶油白衫", "甜點咖啡", "午後生活寫真", "落地窗"],
    identity: "巴黎午後甜點咖啡館奶油白衫",
    palette: "奶油白、暖金、草莓粉、玫瑰米色",
    costumeCore: "奶油白荷葉邊長袖寬鬆上衣，深V領口，微透薄棉質感，休閒優雅",
    jewelry: "無明顯配飾，自然素顏感妝容",
    prop: "雙手捧拿鐵咖啡杯（咖啡館場景合理持物）、桌面草莓蛋糕、馬卡龍、提拉米蘇、玫瑰花瓶",
    place: "巴黎高端甜點咖啡館，落地窗採光",
    foreground: "桌面甜點與花瓶淺焦虛化",
    midground: "真人名媛坐於窗邊，臉部至胸口，正面輕俯視角，生活攝影感",
    background: "大理石桌面、甜點展示架、巴黎街景落地窗外、暖金吊燈",
    action: "人物坐於窗邊，雙手捧咖啡杯輕靠嘴邊，目光直視鏡頭，神情寧靜愉悅，手與杯不遮五官",
    lighting: "落地窗自然日光主光、白色桌面反射補光、暖金吊燈環境光",
    atmosphere: "巴黎咖啡館午後生活寫真電影感，以甜點與花卉陳設為前景層次，咖啡館場景持杯合理",
  },
  // ─── 2026-06-12 風格範例批次分析新增角色卡 ──────────────
  {
    id: "style-ref-phoenix-gold-empress",
    title: "鳳儀皇后・金鳳宮廷華冠",
    parentCategory: "中國歷代服裝／泛朝代總覽",
    series: "風格範例轉卡／鳳儀皇后",
    themeHint: "金鳳冠 宮廷華服 珍珠流蘇 皇后 金色刺繡",
    aliases: ["鳳儀皇后", "金鳳冠", "宮廷華服", "珍珠流蘇", "皇后"],
    identity: "鳳儀皇后金鳳宮廷華冠",
    palette: "金色、紅色、黑色、珍珠白與金屬光澤",
    costumeCore: "精緻金色刺繡鳳凰圖案宮廷禮服、多層次華麗設計、完整安全內襯、紅色底色與金線刺繡",
    jewelry: "華麗鳳冠、珍珠串飾、金色步搖、流蘇耳環、額飾與多層頸飾",
    prop: "宮殿金色裝飾與傳統圖騰作背景陳設",
    place: "金色宮殿內景，傳統圖騰裝飾牆面",
    foreground: "金色裝飾、珍珠流蘇與鳳冠細節柔焦",
    midground: "真人皇后上半身至腰線，正面構圖，鳳冠與服飾細節清楚",
    background: "金色宮殿背景、傳統圖騰裝飾、暖色調宮燈",
    action: "人物端坐或站立，雙手自然疊於前方，姿態端莊威儀，正視鏡頭",
    lighting: "warm palace golden key、soft jewelry sparkle、facial highlight",
    atmosphere: "宮廷皇后華麗電影封面，以鳳冠與金色刺繡為視覺核心，莊嚴華貴",
    cupSize: "正常比例",
  },
  {
    id: "style-ref-purple-mist-fairy",
    title: "紫霄仙子・夢幻仙俠飄渺",
    parentCategory: "仙俠神話 / 古裝陸劇",
    series: "風格範例轉卡／紫霄仙子",
    themeHint: "淡紫色 粉色 仙俠 夢幻 飄逸薄紗 光暈",
    aliases: ["紫霄仙子", "夢幻仙俠", "淡紫薄紗", "飄渺仙姬", "仙氣"],
    identity: "紫霄仙子夢幻仙俠飄渺",
    palette: "淡紫色、粉色、白色漸層、金色點綴與柔光暈",
    costumeCore: "輕盈飄逸的紫粉漸層薄紗仙服、多層次設計、寬袖飄帶、完整安全內襯",
    jewelry: "精緻紫晶髮簪、額飾、粉晶耳墜、細金項鍊與腰間飾品",
    prop: "夢幻光暈與柔光粒子作場景效果",
    place: "夢幻虛空仙境，光暈環繞",
    foreground: "柔光粒子、薄紗飄帶與光暈虛化",
    midground: "真人仙子上半身或四分之三身，薄紗飄逸，臉部清楚",
    background: "夢幻虛空、紫粉光暈、柔和光球與星點",
    action: "人物站立或微浮，雙手自然舉起或輕托薄紗，仙氣飄渺姿態",
    lighting: "soft purple-pink haze glow、dream light diffusion、fairy rim light",
    atmosphere: "仙俠夢幻飄渺電影封面，以紫粉光暈與飄逸薄紗為視覺核心",
    cupSize: "正常比例",
  },
  {
    id: "style-ref-dark-gothic-duchess",
    title: "暗夜女爵・哥德黑玫瑰",
    parentCategory: "暗黑墮天使",
    series: "風格範例轉卡／暗夜女爵",
    themeHint: "哥德式 黑色蕾絲 銀色 深紫 黑玫瑰 神秘",
    aliases: ["暗夜女爵", "哥德式", "黑蕾絲", "黑玫瑰", "神秘女王"],
    identity: "暗夜女爵哥德黑玫瑰",
    palette: "深黑色、銀色、深紫色、金屬光澤",
    costumeCore: "黑色蕾絲與金屬材質結合的華麗哥德禮服、高領設計、完整安全內襯、立體花朵裝飾",
    jewelry: "黑曜石與銀色金屬頭冠、黑玫瑰髮飾、銀色頸鍊、長耳環",
    prop: "黑玫瑰花束與金屬裝飾作陳設",
    place: "暗色調哥德式背景，神秘氛圍",
    foreground: "黑玫瑰花瓣、蕾絲紋理與金屬光澤",
    midground: "真人女爵上半身或四分之三身，哥德服飾輪廓清楚",
    background: "暗色調背景、哥德式裝飾、深紫霧氣",
    action: "人物站立，一手自然扶於胸前或腰側，姿態高貴冷豔，正視鏡頭",
    lighting: "low-key side light、silver metal highlights、purple rim glow",
    atmosphere: "哥德式暗黑女爵電影封面，神秘高貴，不做低俗暗黑風格",
    cupSize: "K",
  },
  {
    id: "style-ref-jade-green-classical",
    title: "碧蓮仙姬・青綠水墨雅韻",
    parentCategory: "中國歷代服裝／泛朝代總覽",
    series: "風格範例轉卡／碧蓮仙姬",
    themeHint: "青綠色 水墨 傳統漢服 素雅 清新",
    aliases: ["碧蓮仙姬", "青綠漢服", "水墨風", "素雅古裝", "清新"],
    identity: "碧蓮仙姬青綠水墨雅韻",
    palette: "青綠色、白色、淡金色、水墨灰",
    costumeCore: "清雅青綠色漢服、素淨簡潔設計、細緻刺繡點綴、完整端莊剪裁",
    jewelry: "簡約玉石髮簪、小型玉飾耳環、細緻腰帶",
    prop: "水墨畫般的山水背景作環境陳設",
    place: "水墨山水背景，清雅自然",
    foreground: "淡色花瓣或水墨暈染效果",
    midground: "真人仙姬上半身或半身，青綠服飾清楚，臉部明亮",
    background: "水墨山水、淡色雲霧、遠山輪廓",
    action: "人物站立，雙手自然垂落或輕扶袖口，姿態清雅端莊",
    lighting: "soft natural diffused light、jade fabric highlights、clean beauty fill",
    atmosphere: "傳統水墨風格古裝電影封面，清新淡雅，以青綠與水墨為視覺基調",
    cupSize: "正常比例",
  },
  {
    id: "style-ref-red-gold-wedding-phoenix",
    title: "鳳冠新娘・紅金喜慶華服",
    parentCategory: "高訂婚紗禮服",
    series: "風格範例轉卡／鳳冠新娘",
    themeHint: "紅色喜服 金色刺繡 鳳凰 新娘 喜慶",
    aliases: ["鳳冠新娘", "紅金喜服", "鳳凰刺繡", "喜慶婚服", "中式新娘"],
    identity: "鳳冠新娘紅金喜慶華服",
    palette: "鮮豔紅色、金色、白色、珍珠光澤",
    costumeCore: "精緻紅色喜服、大量金色鳳凰刺繡、多層次設計、完整安全內襯",
    jewelry: "紅金鳳冠、珍珠流蘇、金色步搖、紅寶石耳環",
    prop: "金色背景裝飾與喜慶陳設",
    place: "金色喜慶背景，華麗氛圍",
    foreground: "紅色裙擺、金色刺繡細節與珍珠流蘇",
    midground: "真人新娘上半身或四分之三身，鳳冠與喜服清楚",
    background: "金色背景、喜慶裝飾、暖色調燈光",
    action: "人物端坐或站立，雙手疊於前方，姿態端莊喜悅，微笑看向鏡頭",
    lighting: "warm golden celebration light、red fabric highlights、pearl sparkle",
    atmosphere: "中式喜慶婚禮電影封面，華麗喜慶，以鳳冠與紅金配色為視覺核心",
    cupSize: "正常比例",
  },
  {
    id: "style-ref-white-green-nature-fairy",
    title: "清荷仙子・白綠自然清新",
    parentCategory: "花園童話 / 自然精靈",
    series: "風格範例轉卡／清荷仙子",
    themeHint: "白色 淡綠 自然 清新 花卉 飄逸",
    aliases: ["清荷仙子", "白綠古裝", "自然清新", "花卉仙子", "飄逸"],
    identity: "清荷仙子白綠自然清新",
    palette: "白色、淡綠色、金色點綴、柔光",
    costumeCore: "白色輕薄古裝、綠色系飾品點綴、自然飄逸剪裁、完整安全內襯",
    jewelry: "花卉頭飾、簡約耳環、綠色玉石配飾",
    prop: "花卉與自然植物環繞作場景效果",
    place: "柔和光暈自然背景",
    foreground: "花卉、葉片與柔光虛化",
    midground: "真人仙子上半身或半身，白色服飾飄逸，臉部清楚",
    background: "柔和光暈、自然綠意、淡色花卉",
    action: "人物站立，雙手自然垂落或輕觸花卉，姿態清新自然",
    lighting: "soft natural key light、white fabric glow、green nature bounce",
    atmosphere: "自然清新仙子電影封面，以白綠配色與花卉環繞為視覺特色",
    cupSize: "正常比例",
  },
  {
    id: "style-ref-blue-purple-mystic-witch",
    title: "星辰女巫・藍紫神秘奇幻",
    parentCategory: "暗黑墮天使",
    series: "風格範例轉卡／星辰女巫",
    themeHint: "深藍 紫色 銀色 魔法 神秘 奇幻",
    aliases: ["星辰女巫", "藍紫奇幻", "神秘魔法", "冷色調", "女巫"],
    identity: "星辰女巫藍紫神秘奇幻",
    palette: "深藍色、紫色、銀色、星光點綴",
    costumeCore: "華麗藍紫色魔法禮服、帶有奇幻元素設計、完整安全內襯、星光裝飾",
    jewelry: "精緻星辰皇冠、寶石飾品、銀色耳環",
    prop: "神秘星光與魔法效果作場景陳設",
    place: "神秘深邃背景，星辰點綴",
    foreground: "星光粒子、紫色霧氣與魔法光效",
    midground: "真人女巫上半身或四分之三身，魔法服飾清楚",
    background: "深邃背景、星辰點綴、紫藍霧氣",
    action: "人物站立，一手輕舉或引導魔法能量，姿態神秘自信",
    lighting: "cool blue-purple mystical light、silver star sparkle、magical glow",
    atmosphere: "奇幻魔法女巫電影封面，神秘冷豔，以藍紫星光為視覺核心",
    cupSize: "K",
  },
  {
    id: "style-ref-modern-black-gold-queen",
    title: "都市女王・現代黑金華麗",
    parentCategory: "現代都市 / 街拍電影",
    series: "風格範例轉卡／都市女王",
    themeHint: "現代時尚 黑色 金色 紅色 華麗禮服",
    aliases: ["都市女王", "現代時尚", "黑金禮服", "華麗", "舞台"],
    identity: "都市女王現代黑金華麗",
    palette: "黑色、金色、紅色、金屬光澤",
    costumeCore: "現代感強烈的華麗禮服、金色圖案裝飾、時尚剪裁、完整安全內襯",
    jewelry: "現代感頭飾、大型耳環、金屬配飾",
    prop: "暗色舞台背景作陳設",
    place: "暗色背景，突出人物",
    foreground: "金色裝飾細節與光斑",
    midground: "真人女王上半身或四分之三身，現代禮服清楚",
    background: "暗色調背景、舞台燈光效果",
    action: "人物站立，姿態自信霸氣，正視鏡頭",
    lighting: "strong stage spotlight、black-gold contrast、dramatic rim light",
    atmosphere: "現代時尚女王電影封面，強烈對比，以黑金配色為視覺核心",
    cupSize: "正常比例",
  },
  {
    id: "style-ref-pink-cherry-princess",
    title: "櫻花公主・粉色夢幻少女",
    parentCategory: "花園童話 / 自然精靈",
    series: "風格範例轉卡／櫻花公主",
    themeHint: "粉紅色 白色 甜美 少女 花朵 夢幻",
    aliases: ["櫻花公主", "粉色夢幻", "甜美少女", "花朵", "浪漫"],
    identity: "櫻花公主粉色夢幻少女",
    palette: "粉紅色、白色、淡金色、柔光",
    costumeCore: "粉色系華麗服飾、甜美浪漫設計、多層薄紗、完整安全內襯",
    jewelry: "花朵頭飾、珍珠飾品、粉晶耳環",
    prop: "花朵與夢幻光暈作場景效果",
    place: "柔和粉色背景，夢幻氛圍",
    foreground: "花瓣、粉色光暈與柔焦效果",
    midground: "真人公主上半身或半身，粉色服飾清楚，臉部明亮",
    background: "粉色夢幻背景、花朵裝飾、柔和光球",
    action: "人物站立或微坐，雙手自然垂落或輕觸花朵，甜美微笑",
    lighting: "soft pink diffused light、dreamy glow、flower highlights",
    atmosphere: "甜美夢幻少女電影封面，以粉色與花朵為視覺核心",
    cupSize: "正常比例",
  },
  {
    id: "style-ref-silver-ice-queen",
    title: "寒冰女王・銀白冰雪奇幻",
    parentCategory: "仙俠神話 / 古裝陸劇",
    series: "風格範例轉卡／寒冰女王",
    themeHint: "銀白色 冰藍色 冰雪 冷豔 透明質感",
    aliases: ["寒冰女王", "銀白冰雪", "冰晶", "冷豔", "冰雪奇幻"],
    identity: "寒冰女王銀白冰雪奇幻",
    palette: "銀白色、冰藍色、透明質感、冷光",
    costumeCore: "冰晶般的銀白色華服、帶有冰雪元素設計、透明薄紗、完整安全內襯",
    jewelry: "冰晶皇冠、銀色飾品、冰藍寶石",
    prop: "冰雪效果與冷光作場景陳設",
    place: "冷色調冰雪背景",
    foreground: "冰晶粒子、雪花與冷光虛化",
    midground: "真人女王上半身或四分之三身，冰雪服飾清楚",
    background: "冰雪背景、冷藍霧氣、銀白光芒",
    action: "人物站立，姿態冷豔高貴，一手輕舉引導冰雪能量",
    lighting: "cool ice-blue key light、silver rim glow、crystal sparkle",
    atmosphere: "冰雪女王奇幻電影封面，冷豔清透，以銀白冰晶為視覺核心",
    cupSize: "正常比例",
  },
  {
    id: "style-ref-orange-gold-sunset-fairy",
    title: "落日仙姬・橙金暖陽古風",
    parentCategory: "仙俠神話 / 古裝陸劇",
    series: "風格範例轉卡／落日仙姬",
    themeHint: "橙色 金色 暖黃 古風 夕陽 溫暖",
    aliases: ["落日仙姬", "橙金古風", "暖陽", "夕陽", "溫暖"],
    identity: "落日仙姬橙金暖陽古風",
    palette: "橙色、金色、暖黃色、夕陽光暈",
    costumeCore: "暖色調古裝、金色刺繡點綴、飄逸剪裁、完整安全內襯",
    jewelry: "金色頭飾、暖色系配飾、橙色寶石",
    prop: "夕陽光暈與溫暖光效作場景陳設",
    place: "溫暖光暈背景，夕陽氛圍",
    foreground: "暖色光暈、金色粒子與柔焦效果",
    midground: "真人仙姬上半身或半身，暖色古裝清楚",
    background: "橙金光暈、夕陽天空、溫暖雲彩",
    action: "人物站立，雙手自然舉起或輕扶服飾，溫柔姿態",
    lighting: "warm sunset golden key、orange glow、soft facial fill",
    atmosphere: "暖陽古風仙姬電影封面，溫暖柔和，以橙金夕陽為視覺基調",
    cupSize: "正常比例",
  },
  {
    id: "style-ref-crimson-palace-consort",
    title: "赤焰皇妃・深紅宮廷霸氣",
    parentCategory: "中國歷代服裝／泛朝代總覽",
    series: "風格範例轉卡／赤焰皇妃",
    themeHint: "深紅色 黑色 金色 宮廷 霸氣 華麗",
    aliases: ["赤焰皇妃", "深紅宮廷", "霸氣", "華麗", "皇妃"],
    identity: "赤焰皇妃深紅宮廷霸氣",
    palette: "深紅色、黑色、金色、金屬光澤",
    costumeCore: "深紅色華麗宮服、氣勢磅礴的設計、金色刺繡、完整安全內襯",
    jewelry: "霸氣頭冠、金屬飾品、紅寶石耳環",
    prop: "暗色調宮廷背景作陳設",
    place: "暗色調宮廷背景",
    foreground: "深紅裙擺、金色刺繡細節與光斑",
    midground: "真人皇妃上半身或四分之三身，宮服輪廓清楚",
    background: "暗色調宮廷、金色裝飾、戲劇性光線",
    action: "人物站立或端坐，姿態霸氣威儀，凝視鏡頭",
    lighting: "dramatic side light、crimson fabric highlights、gold metal sparkle",
    atmosphere: "霸氣宮廷皇妃電影封面，強烈對比，以深紅與金色為視覺核心",
    cupSize: "正常比例",
  },
  {
    id: "style-ref-cyan-blue-ethereal-lord",
    title: "青冥仙君・青藍仙俠飄逸",
    parentCategory: "仙俠神話 / 古裝陸劇",
    series: "風格範例轉卡／青冥仙君",
    themeHint: "青藍色 白色 銀色 仙俠 飄逸 雲霧",
    aliases: ["青冥仙君", "青藍仙俠", "飄逸", "雲霧", "仙氣"],
    identity: "青冥仙君青藍仙俠飄逸",
    palette: "青藍色、白色、銀色、雲霧灰",
    costumeCore: "飄逸的青藍色仙服、輕盈透明材質、寬袖設計、完整安全內襯",
    jewelry: "簡約仙氣髮飾、銀色配飾、青色玉石",
    prop: "雲霧與仙氣效果作場景陳設",
    place: "雲霧繚繞背景",
    foreground: "雲霧、薄紗飄帶與柔光虛化",
    midground: "真人仙君上半身或半身，青藍服飾飄逸清楚",
    background: "雲霧繚繞、青藍天空、遠山輪廓",
    action: "人物站立或微浮，雙手自然舉起或輕托薄紗，飄逸姿態",
    lighting: "cool cyan-blue diffused light、cloud rim glow、ethereal atmosphere",
    atmosphere: "仙俠飄逸電影封面，清冷仙氣，以青藍雲霧為視覺基調",
    cupSize: "正常比例",
  },
  {
    id: "style-ref-floral-blossom-fairy",
    title: "百花仙子・繁花盛世古風",
    parentCategory: "花園童話 / 自然精靈",
    series: "風格範例轉卡／百花仙子",
    themeHint: "多彩花卉 粉紅 綠色 金色 繁花 古風",
    aliases: ["百花仙子", "繁花", "花卉古風", "多彩", "盛世"],
    identity: "百花仙子繁花盛世古風",
    palette: "多彩花卉色、粉紅、綠色、金色",
    costumeCore: "帶有大量花卉圖案的華麗古裝、多色刺繡、飄逸剪裁、完整安全內襯",
    jewelry: "花卉頭飾、自然系配飾、花形耳環",
    prop: "花卉環繞作場景效果",
    place: "花卉環繞背景",
    foreground: "花瓣、花卉與柔光虛化",
    midground: "真人仙子上半身或半身，花卉古裝清楚",
    background: "繁花背景、綠意、春日光線",
    action: "人物站立，雙手自然垂落或輕觸花卉，姿態優雅自然",
    lighting: "bright spring sunlight、floral color highlights、soft beauty fill",
    atmosphere: "繁花盛世古風電影封面，明亮柔和，以多彩花卉為視覺核心",
    cupSize: "正常比例",
  },
  {
    id: "style-ref-purple-gold-noble-consort",
    title: "紫薇貴妃・紫金貴族華貴",
    parentCategory: "中國歷代服裝／泛朝代總覽",
    series: "風格範例轉卡／紫薇貴妃",
    themeHint: "紫色 金色 貴族 華貴 宮廷 刺繡",
    aliases: ["紫薇貴妃", "紫金貴族", "華貴", "宮廷", "精緻刺繡"],
    identity: "紫薇貴妃紫金貴族華貴",
    palette: "紫色、金色、深色調、寶石光澤",
    costumeCore: "紫金色華貴服飾、精緻刺繡、多層次設計、完整安全內襯",
    jewelry: "貴族頭冠、寶石飾品、金色配飾",
    prop: "富麗堂皇背景作陳設",
    place: "富麗堂皇背景",
    foreground: "紫金裙擺、刺繡細節與寶石光澤",
    midground: "真人貴妃上半身或四分之三身，華貴服飾清楚",
    background: "富麗堂皇背景、宮廷裝飾、華貴燈光",
    action: "人物端坐或站立，姿態高貴優雅，正視鏡頭",
    lighting: "warm palace golden light、purple fabric highlights、jewel sparkle",
    atmosphere: "貴族華貴宮廷電影封面，典雅華麗，以紫金配色為視覺核心",
    cupSize: "正常比例",
  },
];

