export const RATIOS = ["2:3", "3:2", "4:3", "3:4", "16:9", "9:16"];

export const DISTANCES = [
  { id: "full", label: "全身照", prompt: "full body cinematic portrait, complete figure visible" },
  { id: "knee", label: "膝蓋以上", prompt: "knees-up cinematic composition, natural body proportion" },
  { id: "half", label: "半身照", prompt: "half body medium shot, balanced shoulder and torso depth" },
  { id: "upper", label: "上半身近景", prompt: "upper body portrait, face clear without beauty close-up distortion" },
  { id: "wide", label: "遠景照", prompt: "wide environmental framing, person integrated with real space" },
];

export const LENSES = [
  { id: "50mm", label: "50mm 標準", prompt: "50mm full-frame cinematic lens, natural compression" },
  { id: "70mm", label: "70mm 壓縮", prompt: "70mm full-frame portrait lens, stable facial proportion" },
  { id: "35mm-safe", label: "35mm 安全廣角", prompt: "35mm environmental lens without wide-angle face distortion" },
];

export const COSTUME_LAYERS = [
  {
    id: "costumeLayer1",
    group: "structure",
    label: "Layer 1 內層貼身基底",
    placeholder: "skin-tight black silk inner lining",
  },
  {
    id: "costumeLayer2",
    group: "structure",
    label: "Layer 2 服裝基礎結構",
    placeholder: "dark embroidered corset foundation",
  },
  {
    id: "costumeLayer3",
    group: "structure",
    label: "Layer 3 胸腰支撐結構",
    placeholder: "structured velvet waist armor",
  },
  {
    id: "costumeLayer4",
    group: "silhouette",
    label: "Layer 4 裙片 / 褲裝 / 主體外層",
    placeholder: "flowing asymmetrical silk skirt panels",
  },
  {
    id: "costumeLayer5",
    group: "detail",
    label: "Layer 5 腰臀金屬飾件",
    placeholder: "obsidian metallic hip ornaments",
  },
  {
    id: "costumeLayer6",
    group: "silhouette",
    label: "Layer 6 外袍 / 披風 / 拖尾",
    placeholder: "cathedral-length outer robe draping",
  },
  {
    id: "costumeLayer7",
    group: "silhouette",
    label: "Layer 7 肩頸披肩 / 羽飾",
    placeholder: "black feathered shoulder mantle",
  },
  {
    id: "costumeLayer8",
    group: "detail",
    label: "Layer 8 珠寶鏈飾",
    placeholder: "luxury gemstone chains and gothic jewelry",
  },
  {
    id: "costumeLayer9",
    group: "detail",
    label: "Layer 9 手套 / 靴子 / 武器配件",
    placeholder: "lace gloves, sculpted boots, ceremonial blade accessory",
  },
  {
    id: "costumeLayer10",
    group: "silhouette",
    label: "Layer 10 動態布料 / 特效外掛",
    placeholder: "floating translucent ribbons and wind-responsive veil",
  },
];

export const COSTUME_LAYER_GROUPS = [
  {
    id: "silhouette",
    label: "60% 主輪廓 / 體積",
    prompt: "60% visual priority: dominant silhouette, robe, skirt volume, cape, train, shoulder mantle, and moving fabric must shape the first read of the costume",
  },
  {
    id: "structure",
    label: "25% 結構 / 支撐",
    prompt: "25% visual priority: corset, bodice, waist support, armor structure, and inner foundation define the character architecture without overpowering the face",
  },
  {
    id: "detail",
    label: "15% 細節 / 身份裝飾",
    prompt: "15% visual priority: jewelry, chains, metal ornaments, gloves, boots, and props add identity detail but must not dominate the main silhouette",
  },
];

export const PRESETS = [
  {
    id: "tang-flight",
    title: "大唐飛天旅拍",
    theme: "大唐飛天女官",
    scene: "黃昏絲路城門與飄動旌旗，前景薄霧，中景石階，遠景落日長安輪廓",
    costume: "重工刺繡襦裙，半透明披帛，金絲腰封，玉石步搖，真實絲綢垂墜",
    costumeLayer1: "ivory silk inner dress lining",
    costumeLayer2: "embroidered Tang dynasty ruqun foundation",
    costumeLayer3: "structured gold-thread waist sash",
    costumeLayer4: "flowing layered silk skirt panels",
    costumeLayer5: "jade waist pendants and small metal ornaments",
    costumeLayer6: "translucent long pibo scarf draping",
    costumeLayer7: "light shoulder gauze with wind movement",
    costumeLayer8: "jade hairpin, gold chains, delicate forehead ornament",
    makeup: "唐風花鈿，柔霧底妝，保留原始骨相與自然年齡感",
    action: "正面微側站姿，肩線放鬆，眼神看向鏡頭，臉部完整可見",
    lighting: "黃昏側逆光，髮絲輪廓光，真實空氣粒子",
  },
  {
    id: "gothic-queen",
    title: "哥德王座女王",
    theme: "暗夜王座女王",
    scene: "哥德式石柱王座廳，燭火與月光交錯，遠景高窗與黑色旗幟",
    costume: "黑色絲絨束腰禮服，多層蕾絲外袍，銀色金屬肩飾，深紅寶石頸飾",
    costumeLayer1: "black silk inner lining",
    costumeLayer2: "dark embroidered corset foundation",
    costumeLayer3: "structured velvet waist armor",
    costumeLayer4: "asymmetrical black lace skirt panels",
    costumeLayer5: "obsidian metallic hip ornaments",
    costumeLayer6: "cathedral-length velvet outer robe draping",
    costumeLayer7: "black feathered shoulder mantle",
    costumeLayer8: "ruby gemstone chains and gothic jewelry",
    makeup: "冷調電影妝，低飽和暗紅唇色，中性神態，不改變五官比例",
    action: "穩定站在王座前，手自然垂放，身體重心平衡",
    lighting: "月光側光與暖色燭光形成冷暖對比",
  },
  {
    id: "cyber-city",
    title: "霓虹未來旅拍",
    theme: "賽博都市特工",
    scene: "雨夜霓虹街道，濕潤地面反射，前景透明雨滴，中景街招，遠景高樓",
    costume: "霧面機能長外套，細節金屬扣件，透明防水層，低調發光線條",
    costumeLayer1: "matte black technical bodysuit base",
    costumeLayer2: "transparent waterproof shell layer",
    costumeLayer3: "structured utility waist harness",
    costumeLayer4: "asymmetrical tactical skirt coat panels",
    costumeLayer5: "brushed metal belt modules",
    costumeLayer6: "long rainproof cinematic trench coat",
    costumeLayer7: "raised shoulder guard with subtle neon seams",
    costumeLayer8: "low-profile glowing ear devices and chain details",
    makeup: "乾淨真實底妝，微金屬眼影，只作表面修飾",
    action: "自然向前行走，臉朝鏡頭，手部姿勢放鬆",
    lighting: "藍紫霓虹邊緣光，柔和環境反射，真實雨夜空氣感",
  },
  {
    id: "landmark-paris",
    title: "巴黎電影旅拍",
    theme: "巴黎黃昏旅拍女主",
    scene: "塞納河畔黃昏石橋，前景欄杆，中景行人虛化，遠景巴黎天際線",
    costume: "高級米白風衣，真絲襯衫，深色長裙，低調金屬耳飾，真實布料重量",
    costumeLayer1: "soft silk blouse foundation",
    costumeLayer2: "tailored ivory vest structure",
    costumeLayer3: "cinched leather waist belt",
    costumeLayer4: "dark wool long skirt with real fabric weight",
    costumeLayer5: "subtle brass belt buckle and side chain",
    costumeLayer6: "premium ivory trench coat draping",
    costumeLayer7: "light scarf moving in wind",
    costumeLayer8: "minimal gold earrings and fine necklace",
    makeup: "自然電影妝，保留皮膚紋理與臉部不對稱",
    action: "站在橋邊自然回身三分之一，臉部仍完整面向鏡頭",
    lighting: "柔和金色夕陽，環境漫反射，淺景深分離",
  },
  {
    id: "xianxia-temple",
    title: "雲海仙門旅拍",
    theme: "仙門長老",
    scene: "雲海石階與古老山門，前景流動白霧，中景石燈，遠景群山",
    costume: "月白長袍，多層薄紗外罩，玉扣腰帶，銀線暗紋，真實衣料厚薄變化",
    costumeLayer1: "white silk inner robe lining",
    costumeLayer2: "moon-white long robe foundation",
    costumeLayer3: "jade-button structured waist belt",
    costumeLayer4: "layered translucent gauze skirt panels",
    costumeLayer5: "small silver waist ornaments",
    costumeLayer6: "long outer robe with cloud-like draping",
    costumeLayer7: "soft shoulder veil and sleeve ribbons",
    costumeLayer8: "jade hairpiece and silver-thread accessories",
    makeup: "清透電影妝，淡色眉眼修飾，不少女化，不改變骨相",
    action: "穩定站於石階中央，雙手自然交疊，目光平視",
    lighting: "清晨柔光，雲霧漫射，低對比真實陰影",
  },
];

export const WORD_BANK = {
  identity: [
    "preserve the real uploaded face identity",
    "preserve original facial structure and recognizable features",
    "no AI beauty template face",
    "natural facial asymmetry and real age texture",
  ],
  body: [
    "real adult human anatomy",
    "balanced shoulder width and torso depth",
    "natural center of gravity",
    "no big-head proportion, no compressed body",
  ],
  costume: [
    "couture-level wearable costume structure",
    "real fabric weight and stitching",
    "layered textile design with cultural logic",
    "handcrafted metal and gemstone accessories",
  ],
  scene: [
    "foreground, midground, and background depth",
    "real spatial perspective",
    "cinematic environmental storytelling",
    "atmospheric haze and natural depth of field",
  ],
  safety: [
    "face fully visible",
    "no hand covering face",
    "no back-facing pose",
    "no explicit or pornographic styling",
    "no cosplay plastic texture",
  ],
};

export const NEGATIVE_PROMPT = [
  "AI beauty face",
  "internet celebrity filter",
  "doll face",
  "anime face",
  "game character",
  "cartoon body",
  "big head",
  "tiny body",
  "compressed torso",
  "extreme hourglass body",
  "wide-angle face distortion",
  "selfie angle",
  "over-smoothed plastic skin",
  "overly sexual pose",
  "pin-up pose",
  "hands covering face",
  "back to camera",
  "cosplay plastic fabric",
  "CG render look",
  "fashion editorial beauty campaign",
];
