export const TENTH_WAVE_PROFILE_DEFS = [
  {
    id: "style-ref-flower-window-qipao",
    title: "花窗牡丹・奶油白旗袍名媛",
    parentCategory: "現代都市 / 街拍電影",
    series: "風格範例轉卡／花窗旗袍",
    themeHint: "花窗 牡丹 奶油白旗袍 珍珠髮飾 室內柔光",
    aliases: ["風格範例", "花窗旗袍", "牡丹刺繡", "奶油白", "珍珠髮飾"],
    identity: "花窗牡丹奶油白旗袍名媛",
    palette: "奶油白、粉牡丹、珍珠金與柔木棕",
    costumeCore: "奶油白緞面旗袍、粉色牡丹刺繡、半透明披紗與合身但端正的室內名媛禮服輪廓",
    jewelry: "珍珠流蘇髮飾、細珍珠項鍊、玉鐲與小型金色耳飾",
    prop: "粉牡丹花枝與珍珠手包",
    place: "中式花窗室內花房",
    foreground: "粉牡丹、薄紗窗簾與柔焦花影",
    midground: "真人名媛站在木格花窗旁中景，肩頸與旗袍刺繡清楚",
    background: "木格窗、室內花器、玉石擺件與窗外綠意",
    action: "人物一手低持花枝，一手自然扶住珍珠項鍊或手包，眼神安靜看向鏡頭",
    lighting: "soft window key light、warm flower-room bounce、pearl and silk highlights",
  },
  {
    id: "style-ref-stardust-silver-evening-muse",
    title: "星塵銀紗・水晶夜宴名媛",
    parentCategory: "現代都市 / 街拍電影",
    series: "風格範例轉卡／水晶夜宴",
    themeHint: "銀鑽薄紗 晚禮服 長髮逆光 灰金 sparkle",
    aliases: ["銀鑽", "星塵", "水晶晚禮服", "逆光長髮"],
    identity: "星塵銀紗水晶夜宴名媛",
    palette: "銀白、水晶灰、香檳金與柔膚暖光",
    costumeCore: "銀白水晶刺繡晚禮服、細密珠飾、透明外紗罩裙與安全內襯結構，呈現高訂晚宴質感而非低俗禮服",
    jewelry: "水晶長耳墜、細鑽項鍊、銀色戒指與髮絲珠光飾件",
    prop: "水晶手包與香檳色薄紗披肩",
    place: "灰金夜宴露台座椅旁",
    foreground: "薄紗裙擺、水晶手包與柔焦光點",
    midground: "真人名媛端坐或站在露台座椅旁，禮服輪廓完整不以胸腰腿為主視覺",
    background: "灰金牆面、木質扶手、遠景燈球與細緻空氣粒子",
    action: "人物一手扶椅背，一手低持手包，長髮受側風帶起但不遮臉",
    lighting: "bright champagne rim light、soft facial fill、crystal sparkle highlights",
    atmosphere: "安全高訂夜宴電影海報主視覺，避免 pin-up 與身體特寫",
  },
  {
    id: "style-ref-morning-private-suite-heiress",
    title: "晨光私宅・淡紫都會名媛",
    parentCategory: "現代都市 / 街拍電影",
    series: "風格範例轉卡／私宅名媛",
    themeHint: "淡紫上衣 白裙 私宅 大面窗光 極簡室內",
    aliases: ["淡紫", "私宅", "白裙", "大面窗光", "都會名媛"],
    identity: "晨光私宅淡紫都會名媛",
    palette: "淡紫、象牙白、米金與淺木色",
    costumeCore: "淡紫交疊針織上衣、象牙白高腰短裙或及膝裙、米白短外套與細帶高跟鞋，保持現代時尚雜誌感",
    jewelry: "小珍珠耳釘、細金手鍊、白色小手包與簡約髮夾",
    prop: "白色小手包與花瓶旁的邀請卡",
    place: "晨光灑入的現代私宅客廳",
    foreground: "邀請卡、白色手包、大理石地面反光與沙發扶手",
    midground: "真人名媛站在窗邊或沙發旁，姿態端正自然",
    background: "白牆線板、米白沙發、花瓶、落地窗與斜切日光",
    action: "人物一手低提手包，一手自然整理袖口，雙腳重心穩定",
    lighting: "clear morning window light、cream wall bounce、soft marble reflections",
  },
  {
    id: "style-ref-liquid-chrome-cyber-curator",
    title: "液態銀環・未來展廳指揮官",
    parentCategory: "賽博機甲 / 科幻戰姬",
    series: "風格範例轉卡／液態銀科幻戰姬",
    themeHint: "銀色金屬 透明管線 科幻展廳 冷藍高光",
    aliases: ["液態銀", "透明管線", "未來展廳", "chrome fashion"],
    identity: "液態銀環未來展廳指揮官",
    palette: "鏡面銀、冰藍、透明玻璃與冷白色",
    costumeCore: "鏡面銀短外套、銀色機能長裙或長褲、透明防護披層與高領軟甲內搭，保留 chrome 反光但避免低角度性感構圖",
    jewelry: "透明耳機模組、銀色耳扣、光學頸環與手腕控制器",
    prop: "透明控制環與液態金屬資料板",
    place: "冷白玻璃未來展廳",
    foreground: "透明控制環、玻璃反射與銀色地面光帶",
    midground: "真人指揮官站在展廳中心，身體完整入鏡",
    background: "冰藍玻璃柱、反射牆、漂浮透明管線與冷色城市剪影",
    action: "人物一手操作透明控制環，一手低持資料板，正面或微側正面看向鏡頭",
    lighting: "clinical white key、icy blue rim light、chrome specular highlights",
    atmosphere: "未來時裝電影主視覺，避免腿部、胸腰或低角度成為主視覺",
  },
  {
    id: "style-ref-sunset-bay-white-shirt-traveler",
    title: "落日海灣・白衫旅人",
    parentCategory: "世界景點旅拍",
    series: "風格範例轉卡／落日海灣",
    themeHint: "海邊夕陽 白色休閒造型 橙金海面 自然笑容",
    aliases: ["海邊", "夕陽", "白衫", "度假旅拍", "水面反光"],
    identity: "落日海灣白衫旅人",
    palette: "夕陽橙、海水金、白色與柔沙色",
    costumeCore: "白色棉質背心或短袖襯衫、白色高腰短褲或輕便長裙、薄防曬外衫與度假涼鞋",
    jewelry: "貝殼耳飾、細金手鍊、草編髮繩與小項鍊",
    prop: "草編帽與小型防水相機",
    place: "落日海灣淺灘",
    foreground: "浪花、水珠、草編帽與濕沙反光",
    midground: "真人旅人站在淺灘邊，笑容自然，肩頸與白色造型清楚",
    background: "橙金夕陽、海面光路、遠方島影與柔焦浪線",
    action: "人物一手低持相機，一手自然扶住被海風吹動的外衫",
    lighting: "golden sunset backlight、warm facial fill、ocean sparkle reflections",
  },
  {
    id: "style-ref-peach-pavilion-tang-court-lady",
    title: "桃花宮苑・粉金盛唐宮姬",
    parentCategory: "中國歷代服裝",
    series: "風格範例轉卡／盛唐花苑",
    themeHint: "粉金唐風 高髻花冠 珍珠流蘇 宮苑花亭",
    aliases: ["盛唐", "桃花", "宮苑", "粉金", "珍珠流蘇"],
    identity: "桃花宮苑粉金盛唐宮姬",
    palette: "桃粉、米金、珍珠白與柔水綠",
    costumeCore: "粉金齊胸襦裙、透明繡花外衫、寬袖披帛與真絲多層垂墜",
    jewelry: "高髻花冠、珍珠流蘇步搖、金色額飾、玉佩與細金腰飾",
    prop: "桃花枝與小型香囊",
    place: "盛唐宮苑桃花花亭",
    foreground: "桃花枝、薄紗袖口、宮苑石欄與花影柔光",
    midground: "真人宮姬坐於花亭石欄旁或站在花影中景",
    background: "園林池水、太湖石、桃花樹與柔焦亭台",
    action: "人物一手低持桃花枝，一手自然扶袖，臉部正面清楚",
    lighting: "warm garden key light、water reflection fill、pearl and embroidery highlights",
  },
  {
    id: "style-ref-blooming-garden-bridal-queen",
    title: "繁花秘園・皇冠花嫁",
    parentCategory: "花園奇幻／森林精靈／電影童話",
    series: "風格範例轉卡／花園花嫁",
    themeHint: "花園婚紗 皇冠 頭紗 花束 粉紫花廊 夕陽逆光",
    aliases: ["花嫁", "皇冠", "頭紗", "花束", "粉紫花廊"],
    identity: "繁花秘園皇冠花嫁",
    palette: "薔薇粉、薰衣草紫、嫩葉綠、象牙白與夕陽金",
    costumeCore: "粉紫花朵刺繡婚紗、象牙白安全內襯、透明花瓣披紗、長拖尾與柔軟花園裙擺",
    jewelry: "細鑽皇冠、珍珠耳墜、花瓣手鏈與白金項鍊",
    prop: "粉紫玫瑰花束與絲帶",
    place: "夕陽繁花秘園石階花廊",
    foreground: "花束、飄落花瓣、石階與透明拖尾",
    midground: "真人花嫁站在花廊中央，全身輪廓完整",
    background: "粉紫花牆、樹影、遠景石階與夕陽光球",
    action: "人物雙手抱花束低於胸口，頭紗和披紗受微風帶起但不遮臉",
    lighting: "golden garden backlight、soft bridal facial fill、sparkle veil highlights",
    atmosphere: "花園童話婚紗電影主視覺，禁止畫面文字與過度透明焦點",
  },
  {
    id: "style-ref-dunhuang-golden-crown-feitian",
    title: "敦煌金冠・碧紗飛天舞姬",
    parentCategory: "中國神話",
    series: "風格範例轉卡／敦煌飛天",
    themeHint: "敦煌 飛天 金冠 綠松石 橙青披帛 壁畫佛龕",
    aliases: ["敦煌", "飛天", "壁畫", "綠松石", "金冠"],
    identity: "敦煌金冠碧紗飛天舞姬",
    palette: "沙金、孔雀青、蜜桃橙與壁畫赭色",
    costumeCore: "敦煌飛天舞衣、碧色與橙色長披帛、金線胸衣外層與透明但有安全內襯的舞用長裙",
    jewelry: "金冠、綠松石耳飾、額飾、臂釧、金鏈腰飾與流蘇步搖",
    prop: "長披帛與小型金鈴",
    place: "敦煌壁畫佛龕舞台",
    foreground: "橙青披帛、金鈴、塵光與壁畫色塊",
    midground: "真人飛天舞姬在佛龕前舞動，臉部正面或微側正面清楚",
    background: "敦煌壁畫佛像、古老洞窟紋樣、金色浮塵與暖暗牆面",
    action: "人物雙臂舞動長披帛，手部遠離臉部，舞姿有真實重心",
    lighting: "warm cave skylight、gold dust glow、turquoise jewelry catchlight",
  },
  {
    id: "style-ref-red-moon-nine-tail-fox-queen",
    title: "紅月狐火・九尾花海妖后",
    parentCategory: "中國神話",
    series: "風格範例轉卡／紅月九尾",
    themeHint: "紅月 九尾狐后 白狐巨獸 彼岸花 暗黑東方神話",
    aliases: ["九尾狐", "紅月", "白狐", "彼岸花", "狐火"],
    identity: "紅月狐火九尾花海妖后",
    palette: "血紅、月黑、雪白狐毛與暗紫夜色",
    costumeCore: "深紅花瓣刺繡長裙、黑紅披紗、完整安全內襯與巨大拖尾，形成暗黑東方神話女王輪廓",
    jewelry: "紅晶花冠、細金額飾、黑紅耳墜與狐火紋腰飾",
    prop: "紅晶花枝與狐火符紋",
    place: "紅月廢城彼岸花海",
    foreground: "彼岸花、紅色花瓣、狐火線條與裙擺拖尾",
    midground: "真人妖后站在白狐守護獸旁，姿態端正有壓迫感",
    background: "紅月、廢城剪影、巨大白狐幻影與暗紫夜雲",
    action: "人物一手低持紅晶花枝，一手自然垂落，白狐在身側守護",
    lighting: "red moon backlight、cool facial fill、white fur rim light and crimson haze",
    atmosphere: "暗黑東方神話電影主視覺，不做遊戲 boss 化或低俗女王造型",
  },
  {
    id: "style-ref-amber-rock-occult-countess",
    title: "岩金密紋・琥珀長袍女爵",
    parentCategory: "西方古典 / 歐陸史詩",
    series: "風格範例轉卡／黑金岩紋",
    themeHint: "黑金 岩紋 琥珀光 長袍 室內沙發 歐式密教",
    aliases: ["黑金", "岩紋", "琥珀", "密教", "歐式室內"],
    identity: "岩金密紋琥珀長袍女爵",
    palette: "岩石黑、琥珀金、茶棕與暗銅色",
    costumeCore: "黑金幾何刺繡長袍、琥珀色真絲內搭、高領披肩與完整長裙結構，取代原參考的內衣商品感",
    jewelry: "幾何金屬項鍊、琥珀耳墜、黑金腰鏈與古銅戒指",
    prop: "岩紋手札與琥珀酒杯",
    place: "暖暗歐式書房皮革沙發旁",
    foreground: "手札、酒杯、皮革扶手與黑金披紗",
    midground: "真人女爵站在沙發前或端坐椅側，長袍完整覆蓋身體輪廓",
    background: "木質書房、窗簾逆光、暗金壁燈與古典地毯",
    action: "人物一手低持手札，一手扶住長袍披肩，微側正面看鏡頭",
    lighting: "warm amber window beam、leather bounce、subtle gold embroidery highlights",
    atmosphere: "安全黑金高訂密教電影主視覺，不保留內衣、商品文字或性感商品頁構圖",
  },
  {
    id: "style-ref-waterfall-green-gauze-nymph",
    title: "幽潭瀑影・青衣水仙",
    parentCategory: "中國神話",
    series: "風格範例轉卡／幽潭水仙",
    themeHint: "瀑布 水潭 青紗 森林 冷色水光",
    aliases: ["瀑布", "青紗", "水仙", "幽潭", "森林"],
    identity: "幽潭瀑影青衣水仙",
    palette: "冷青綠、霧白、水石灰與深林黑",
    costumeCore: "青綠古風長裙、半透明外紗、濕潤質感披帛與完整內層襯裙，保持神話水仙氣質",
    jewelry: "青玉髮簪、水滴耳飾、細銀臂環與小玉佩",
    prop: "青玉水盞與水草花枝",
    place: "森林瀑布幽潭石岸",
    foreground: "潭水漣漪、濕石、水草與青紗袖口",
    midground: "真人水仙坐在石岸或半跪於水邊，身體支撐點合理",
    background: "瀑布、深林岩壁、冷色水霧與水面高光",
    action: "人物一手扶石岸，一手低持水盞，臉部抬起看向鏡頭",
    lighting: "cool waterfall skylight、water reflection fill、misty rim light",
    atmosphere: "幽潭神話電影主視覺，避免濕身性感化",
  },
  {
    id: "style-ref-pink-pet-clinic-nurse",
    title: "甜粉診療所・貓耳看護",
    parentCategory: "現代都市 / 街拍電影",
    series: "風格範例轉卡／甜粉看護",
    themeHint: "粉白制服 貓耳 看護 蝴蝶結 寵物診療所",
    aliases: ["粉白", "貓耳", "看護", "蝴蝶結", "寵物診療"],
    identity: "甜粉診療所貓耳看護",
    palette: "嫩粉、純白、櫻花粉與柔灰色",
    costumeCore: "粉白短袖看護制服、圓領安全內搭、愛心腰帶、蝴蝶結圍裙與膝上制服裙，呈現可愛制服而非情趣化 cosplay",
    jewelry: "粉色髮夾、愛心項圈式頸飾、名牌、白色短手套與小耳釘",
    prop: "愛心聽診器與病歷夾",
    place: "明亮寵物診療所接待區",
    foreground: "病歷夾、聽診器、粉白櫃台與小型醫療器具",
    midground: "真人看護站在接待櫃台旁，制服輪廓端正",
    background: "白色診間門、粉色標示牌、玻璃藥櫃與柔和燈箱",
    action: "人物一手低持病歷夾，一手自然扶櫃台，貓耳髮飾不遮臉",
    lighting: "bright studio clinic light、soft pink bounce、clean fabric highlights",
    atmosphere: "可愛寵物診療電影角色卡，不做商品頁文字排版或低俗制服化",
  },
  {
    id: "style-ref-blue-sleeve-spring-forest-lady",
    title: "春林藍袖・古風花影仕女",
    parentCategory: "中國歷代服裝",
    series: "風格範例轉卡／藍袖花林",
    themeHint: "寶藍漢服 金繡 林間 花瓣 暖色樹影",
    aliases: ["寶藍漢服", "春林", "花瓣", "金繡", "古風仕女"],
    identity: "春林藍袖古風花影仕女",
    palette: "寶藍、象牙白、金繡色與森林綠",
    costumeCore: "寶藍交領古風長衫、白色內裙、金色花紋刺繡與寬幅透明長袖",
    jewelry: "珍珠金簪、白玉耳飾、細金髮扣與小玉佩",
    prop: "白花枝與藍色披帛",
    place: "春日林間花瓣小徑",
    foreground: "花瓣、藍袖披帛、樹根與柔焦葉影",
    midground: "真人仕女站在老樹旁，抬手整理長袖但不遮臉",
    background: "老樹、暖色穿林光、落花與淡霧小徑",
    action: "人物一手低持花枝，一手牽起長袖，目光微仰或看向鏡頭",
    lighting: "warm forest shaft light、green leaf bounce、blue silk highlights",
  },
  {
    id: "style-ref-blue-core-cyber-guardian",
    title: "藍核義體・戰術守衛",
    parentCategory: "賽博機甲 / 科幻戰姬",
    series: "風格範例轉卡／藍核義體戰姬",
    themeHint: "賽博 義體 藍色能量核心 短髮 戰損塗裝",
    aliases: ["賽博", "義體", "藍核", "戰術守衛", "短髮"],
    identity: "藍核義體戰術守衛",
    palette: "冷白、電光藍、金屬黑與微量警示紅",
    costumeCore: "白色戰術外套、黑色機械義體肩臂、藍色能量核心、完整防護胸甲與機能長褲，改寫為非暴露戰術造型",
    jewelry: "藍光耳機、三角晶體耳飾、金屬頸環與資料腕扣",
    prop: "短刀鞘與維修資料晶片",
    place: "雨後賽博城市維修通道",
    foreground: "資料晶片、藍光電纜、雨滴與金屬欄杆",
    midground: "真人守衛站在維修通道中景，義體肩臂與藍核清楚",
    background: "冷色柱光、濕地反射、維修機械臂與城市光點",
    action: "人物一手低持晶片，一手自然扶住外套領口，短刀只作為腰側道具",
    lighting: "blue energy key light、pink rim light、rainy metal reflections",
    atmosphere: "戰損賽博電影主視覺，使用塗裝與刮痕取代血腥，避免暴露或繃帶性感化",
  },
  {
    id: "style-ref-forest-ritual-blue-hanbok-dancer",
    title: "林間祭舞・藍白韓服舞者",
    parentCategory: "東方和風旅拍",
    series: "風格範例轉卡／藍白韓服",
    themeHint: "藍白韓服 林間祭儀 長袖飄帶 暖色樹影",
    aliases: ["韓服", "藍白", "林間祭舞", "長袖", "暖色樹影"],
    identity: "林間祭舞藍白韓服舞者",
    palette: "深海藍、象牙白、霧金與森林綠",
    costumeCore: "深藍短襦、白色高腰長裙、銀白刺繡、柔紗長袖飄帶與傳統韓服腰線",
    jewelry: "珍珠髮簪、銀色耳墜、細金髮扣與繡花髮帶",
    prop: "白色長袖飄帶與小陶瓶",
    place: "晨霧林間祭儀石案前",
    foreground: "飄帶、花瓣、陶瓶與石案邊緣",
    midground: "真人舞者在林間張開長袖，臉部正面可辨識",
    background: "老樹、彩色祭帶、柔霧、晨光與林間小徑",
    action: "人物雙臂展開長袖飄帶，手臂遠離臉部，舞姿保持真實重心",
    lighting: "warm forest morning light、soft haze、blue fabric sheen",
  },
  {
    id: "style-ref-sapphire-clockwork-queen-knight",
    title: "星藍齒輪・王庭女騎士",
    parentCategory: "蒸汽奇幻 / 機械王國",
    series: "風格範例轉卡／齒輪王庭機械王國",
    themeHint: "藍金機械王國 鐘塔 齒輪權杖 銀藍重甲 蒸汽",
    aliases: ["齒輪", "鐘塔", "女騎士", "藍金盔甲", "蒸汽王庭"],
    identity: "星藍齒輪王庭女騎士",
    palette: "寶石藍、鈦銀、古金與雲白色",
    costumeCore: "寶石藍與鈦銀全身裙甲、機械肩甲、長裙甲片、護臂、護腿與可穿戴胸甲結構",
    jewelry: "藍寶石頸飾、齒輪髮扣、金屬耳飾與騎士徽章",
    prop: "藍寶石齒輪權杖與機械盾扣",
    place: "蒸汽鐘塔王庭廣場",
    foreground: "權杖、金屬地面、齒輪紋與蒸汽薄霧",
    midground: "真人女騎士站在王庭廣場中央，全身盔甲完整入鏡",
    background: "巨大鐘塔、藍金穹頂、蒸汽管線、飛行機械與晴空雲層",
    action: "人物一手持權杖垂直落地，一手自然扶住護臂，正面凝視鏡頭",
    lighting: "bright royal daylight、blue gemstone glow、polished armor highlights",
  },
  {
    id: "style-ref-pink-cat-ear-clinic-assistant",
    title: "粉白貓耳・診療助理",
    parentCategory: "現代都市 / 街拍電影",
    series: "風格範例轉卡／粉白診療助理",
    themeHint: "粉白貓耳 看護制服 棚拍 蝴蝶結 心形飾件",
    aliases: ["粉白貓耳", "診療助理", "蝴蝶結", "心形飾件", "棚拍"],
    identity: "粉白貓耳診療助理",
    palette: "純白、櫻花粉、黑色髮飾與柔膚粉",
    costumeCore: "粉白短袖制服、白色安全內搭、蓬袖、蝴蝶結腰封與端正制服裙",
    jewelry: "貓耳髮箍、粉色蝴蝶結髮夾、心形頸飾、名牌與小耳釘",
    prop: "粉色筆型手電與小型病歷牌",
    place: "乾淨白棚寵物診療形象照場景",
    foreground: "病歷牌、粉色筆燈與白色櫃台",
    midground: "真人助理站在白棚或診療櫃台旁，臉部明亮清楚",
    background: "純白背景、柔和粉色燈帶、簡潔診療道具與乾淨地面",
    action: "人物一手低持病歷牌，一手自然放在櫃台邊，姿態端正",
    lighting: "clean white studio key、soft pink fill、gentle fabric highlights",
    atmosphere: "可愛制服電影角色卡，不做低俗制服、胸部特寫或商品頁文字",
  },
  {
    id: "style-ref-bangkok-golden-temple-traveler",
    title: "曼谷金殿・紅白旅人",
    parentCategory: "世界地標旅拍",
    series: "風格範例轉卡／曼谷金殿",
    themeHint: "泰國王宮 金色寺院 彩瓷欄杆 紅白現代套裝 日光",
    aliases: ["曼谷", "金殿", "泰國王宮", "紅白", "彩瓷"],
    identity: "曼谷金殿紅白旅人",
    palette: "朱紅、純白、寺院金與琺瑯藍綠",
    costumeCore: "紅白現代度假套裝、白色高腰裙或長褲、輕薄披肩與金色細節，符合寺院旅拍端正穿著",
    jewelry: "金色耳圈、細金手鍊、紅色絲巾扣與小型旅行胸針",
    prop: "旅行票卡與紅色絲巾",
    place: "曼谷金色寺院彩瓷欄杆旁",
    foreground: "旅行票卡、彩瓷欄杆、石階與紅色絲巾",
    midground: "真人旅人站在寺院欄杆側前方，服裝端正明亮",
    background: "金色佛塔、泰式屋簷、鑲嵌牆面與晴朗日光",
    action: "人物一手低持票卡，一手扶住絲巾或欄杆，微側正面看鏡頭",
    lighting: "bright Bangkok daylight、gold temple reflection、clean facial fill",
    atmosphere: "世界地標旅拍主視覺，不保留浮水印或畫面文字",
  },
  {
    id: "style-ref-wisteria-spring-courtyard-lady",
    title: "紫藤春庭・淡紫花姬",
    parentCategory: "中國歷代服裝",
    series: "風格範例轉卡／紫藤春庭",
    themeHint: "淡紫古風 花枝 白花背景 柔和日光",
    aliases: ["紫藤", "淡紫", "花姬", "春庭", "古風"],
    identity: "紫藤春庭淡紫花姬",
    palette: "淡紫、月白、花蕊黃與柔葉綠",
    costumeCore: "淡紫古風襦裙、白色內衫、繡花半透明外袍與柔軟長袖",
    jewelry: "紫花髮簪、珍珠流蘇、細銀耳飾與淺紫腰佩",
    prop: "紫藤花枝與小摺扇",
    place: "春日白花庭院",
    foreground: "紫藤花枝、白色花叢、袖口與柔焦花瓣",
    midground: "真人花姬站在花叢側前方，手持花枝",
    background: "白色花樹、庭院綠影、柔和日光與遠景小徑",
    action: "人物一手持紫藤花枝，一手自然扶袖，安靜看向鏡頭",
    lighting: "soft spring daylight、white flower bounce、lavender fabric highlights",
  },
  {
    id: "style-ref-flower-room-fairy-gardener",
    title: "花房瓶花・精靈園藝師",
    parentCategory: "花園奇幻／森林精靈／電影童話",
    series: "風格範例轉卡／花房精靈",
    themeHint: "花房 瓶花 白色蕾絲 彩翼精靈 窗邊暖光",
    aliases: ["花房", "精靈", "瓶花", "白色蕾絲", "窗邊"],
    identity: "花房瓶花精靈園藝師",
    palette: "奶油白、玫瑰粉、雛菊黃、葉綠與暖木色",
    costumeCore: "奶油白蕾絲長裙、薄紗袖、柔軟園藝圍裙與花瓣刺繡披肩",
    jewelry: "小花髮簪、珍珠耳飾、細金戒指與花葉手鏈",
    prop: "白色花瓶、園藝剪與粉色小花束",
    place: "午後花房木桌旁",
    foreground: "白色花瓶、園藝剪、雛菊、玫瑰與木桌紋理",
    midground: "真人園藝師坐或站在花桌旁，臉部明亮清楚",
    background: "花房窗戶、木架、盆栽、暖光與淡淡彩翼精靈光點",
    action: "人物一手整理瓶花，一手低持園藝剪，遠景小精靈只作為柔焦光點環繞",
    lighting: "warm greenhouse window light、flower color bounce、soft fairy sparkle",
    atmosphere: "真人花房童話電影主視覺，避免卡通化與插畫感",
  },
  {
    id: "style-ref-white-peony-qipao-club-lady",
    title: "牡丹白緞・會館旗袍名媛",
    parentCategory: "現代都市 / 街拍電影",
    series: "風格範例轉卡／白緞旗袍會館",
    themeHint: "白色牡丹刺繡旗袍 大理石階 暖壁燈 會館室內",
    aliases: ["白旗袍", "牡丹刺繡", "會館", "大理石階", "暖壁燈"],
    identity: "牡丹白緞會館旗袍名媛",
    palette: "珍珠白、牡丹粉、孔雀藍、暖金與大理石灰",
    costumeCore: "白色緞面旗袍、牡丹與小鳥刺繡、短袖立領、及膝或長版安全剪裁與細緻盤扣",
    jewelry: "珍珠耳飾、白色細帶鞋、玉戒與小型金色髮夾",
    prop: "牡丹刺繡手包與會館請柬",
    place: "暖金會館大理石階旁",
    foreground: "請柬、手包、大理石階面與壁燈反光",
    midground: "真人名媛站在階梯側前方或端坐階邊，構圖不以腿部為主視覺",
    background: "白金牆面線板、暖壁燈、深色木門與米色沙發",
    action: "人物一手低持請柬，一手自然扶住手包，姿態端莊",
    lighting: "warm club wall light、marble bounce、white satin highlights",
  },
  {
    id: "style-ref-crimson-peony-evening-countess",
    title: "酒紅牡丹・晚宴花園女爵",
    parentCategory: "世界花園旅拍",
    series: "風格範例轉卡／酒紅牡丹",
    themeHint: "酒紅禮服 大型牡丹 石座 暗暖棚景 花瓣",
    aliases: ["酒紅", "牡丹", "晚宴禮服", "花園棚景", "女爵"],
    identity: "酒紅牡丹晚宴花園女爵",
    palette: "酒紅、深牡丹紅、煙玫瑰、石灰灰與柔金",
    costumeCore: "酒紅絲緞晚禮服、花瓣式披肩、完整安全內襯、長裙擺與克制高訂晚宴輪廓",
    jewelry: "紅寶耳墜、細金手鐲、玫瑰金髮夾與小型寶石項鍊",
    prop: "深紅牡丹花枝與絲緞手包",
    place: "暗暖牡丹花園石座旁",
    foreground: "大型牡丹、花瓣、石座邊緣與酒紅裙擺",
    midground: "真人女爵站在石座旁或端正倚坐，禮服輪廓完整",
    background: "暗色花牆、粉紅牡丹、暖色聚光與柔焦枝葉",
    action: "人物一手低持牡丹花枝，一手扶住石座或手包，眼神平靜看向鏡頭",
    lighting: "warm floral studio key、crimson petal bounce、soft gold rim light",
    atmosphere: "酒紅花園晚宴電影主視覺，避免性感坐姿或身體特寫",
  },
];
